### ISSUE TITLE
List configuration file not being detected

### ISSUE THREAD

**Issue by Flynsarmy** [rainlab/builder-plugin#10]
I have a working (existing) plugin with a list controller, however inspecting it in the Controllers section of Builder results in a validation error as the *List configuration file* row isn't detected by default.

Replicated on the latest build of october as of time of writing (Build 316).

Steps to replicate:
* Click controllers on the left
* Open a controller
* Click 'List controller behavior' to open the inspector - List configuration file won't be detected.

![screen shot 2016-02-11 at 9 37 08 am](https://cloud.githubusercontent.com/assets/334808/12965619/53087aec-d0a3-11e5-81c8-25bd5d09c940.png)

**Comment by alekseybobkov** [comment]
Builder uses plugin-relative path notation: $/author/plugin. Before this fix - if the existing path was specified relative to the root (~/plugins/author/plugin/), Builder wasn't able to pick up the path automatically. 

We replaced the drop-down list selector with the auto-complete field, so existing values are supported now. 

Please note Builder currently doesn't show models from other plugins in the UI. If you need to use models from other plugins, edit YAML files manually.
