### ISSUE TITLE
Cannot add a NOT NULL column with default value NULL

### ISSUE THREAD

**Issue by codaha** [rainlab/builder-plugin#101]
I am using qlite as my database.

When i want to add new field to existing database and i dont specifi default value i gat this error:

SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL (SQL: alter table "tabke_name " add column "column_name" varchar not null)

Walkaround to this is to add some gibberish as default value and create another migration that removes this gibberish.

**Comment by LukeTowers** [comment]
@codaha You either have to specify that the column is nullable (add `->nullable()` to your column declaration in your migration) or specify a default value. If you don't want the column to contain `NULL` values, then specify an empty default for that column with `->default('')`, `->default(0)`, or even `->default(false)`.

**Comment by daftspunk** [comment]
Thanks @LukeTowers. Correct, this is a legitimate error caused by a structural problem. A field cannot be set to `null` when the table structure specifically says it cannot have `null` as a value! =)
