### ISSUE TITLE
can't find "apply version" after update version file.

### ISSUE THREAD

**Issue by enzewu** [rainlab/builder-plugin#103]
In the document, 
I found 
 **"You should click the "Apply version" button in the toolbar in order to apply the version and execute the update code (if applicable)."**

However, I can't find that. So that means I shall do that manually?

Thanks

**Comment by daftspunk** [comment]
I assume so, yes.

**Comment by alekseybobkov** [comment]
"Apply version" button is visible only for versions which have not been applied yet. If you want to edit and re-apply a version, you first should roll it back. If there are versions newer than the version being rolled back, they will be rolled back as well, be careful with this feature.
