### ISSUE TITLE
dynamic dropdown

### ISSUE THREAD

**Issue by junaidnasir** [rainlab/builder-plugin#107]
how can I pull list of users from rainlab/users plugin as dropdown options?
it does say "Dropdown list with static or dynamic options" but I can't find dynamic options.

**Comment by junaidnasir** [comment]
should have read the docs :| i thought dynamic dropdown were builder-plugin's feature.
for anyone else stumbling here in future. [octobercms dropdown](https://octobercms.com/docs/backend/forms#field-dropdown)
so you create a function in your Model with name of `get*field*Options` and return associative array of options. for example if field name is users

```php
 public function getUsersOptions() {
        $users = \RainLab\User\Models\User::all();
        $usersArray = [];
        foreach ($users as $user) {
            $usersArray[$user->id] = $user->name;
        }
        return $usersArray;
    }

**Comment by shoxabbos** [comment]
```
public function getUsersOptions() {
       return \RainLab\User\Models\User::lists('id', 'name');
}
```
