### ISSUE TITLE
Plugin Form Widgets

### ISSUE THREAD

**Issue by NareZ** [rainlab/builder-plugin#109]
Hello,

I have got an issue with my Plugin form widget.

so I have created widget for my plugin and I have added widget name into fields.yaml file manually. After that when I am trying to open fields.yaml from builder it shows me this error:
![widget_issue](https://cloud.githubusercontent.com/assets/20219501/18122483/c45847a6-6f7a-11e6-9365-f8fc6f21fc0f.png)

any ideas?

**Comment by japomani** [comment]
It doesn't look like builder was designed to work with custom widgets found in a plug in, is that right? If so, can we make it work with custom widgets?

I would like to distribute custom widgets in my plugin.

**Comment by daftspunk** [comment]
Please provide the form field definition file so we can see what is happening. Also make sure you register your widget as per the documentation:

http://octobercms.com/docs/backend/widgets#form-widget-registration

**Comment by NareZ** [comment]
`    public function registerFormWidgets()
    {
        return array(
            'Author\\Plugin\\FormWidgets\\RichEditor' => array('label' => 'Rich Editor', 'code' => 'richeditor'),
            'Author\\Plugin\\FormWidgets\\Widget' => array('label' => 'Step Widget','code' => 'widget'
            ),
            'Author\\Plugin\\FormWidgets\\DatePicker' => array('label' => 'Date','code' => 'datepicker'
            )
        );
    }`

and this is my Widget.php file 

`namespace Author\Plugin\FormWidgets;

use Backend\Classes\FormField;
use Backend\Classes\FormWidgetBase;
use Config;

class Widget extends FormWidgetBase
{
...
}`

also this is my fields.yaml file 

`        message_field:
            label: Message
            size: ''
            oc.commentPosition: ''
            span: left
            type: widget
            tab: Settings`

sorry what I am doing wrong? 

notise that builder requires _control-widget.htm file for my widget, but I dont know how I should insert it in builder files after my plugin install or is it the right way?

**Comment by daftspunk** [comment]
```
class Widget extends FormWidgetBase
{
...
}
```

Paste the rest of this class. Also use ``` instead of ` when quoting code. Although I think you may need to create _control-widget.htm inside plugins/author/formwidgets/widget/partial/

**Comment by NareZ** [comment]
public $vars = [
        'Title', 'Target', 'Message', 'Placment', 'Width'
    ];
    /**
     * Render the form widget
     */
    public function render()
    {
        $this->prepareVars();
        return $this->makePartial('widget');
    }

    /**
     * Load widget assets
     */
    public function loadAssets()
    {
        $this->addJs('js/jquery.js');
    }

    /**
     * Widget Config
     */
    public function init()
    {
        $this->fillFromConfig([
            'vars',
        ]);
    }

    /**
     * Prepare widget variables
     */
    public function prepareVars()
    {
        $this->vars['loadValue'] = $this->getLoadValue();

        // Allow plugins to override the configuration
        if ($config = Config::get('blossom.formwidgets::widget')) {
            if (is_array($config) && count($config) >= 1) {
                foreach ($config as $key => $value)
                    $this->vars['config'][$key] = $value;
            }
        }
    }

    /**
     * Return save value
     *
     * @return  float
     */
    public function getSaveValue($value)
    {
        if (!$input = input($this->fieldName))
            return 0;

        $input = preg_replace("/[^0-9]/", '', $input);
        $input = substr($input, 0, -2) . '.' . substr($input, -2);
        $input = floatval($input);

        return $input;
    }


yes sure, here is my widget code, I think issue is that the builder is searching the partial into his files and octobers, but as it does not have any partial with that name and it returns an error. So when I rename my widget from WIDGET to RELATION it is working, also the wirget is working like my created not RELATION

**Comment by daftspunk** [comment]
This could in fact be an issue with naming, perhaps `widget` is a reserved name.

**Comment by NareZ** [comment]
thanks, I have changed my widget name, after I got this 
![module](https://cloud.githubusercontent.com/assets/20219501/18311649/7ce40490-7516-11e6-96f8-e473634e7da4.png)
is it right?

**Comment by daftspunk** [comment]
If the error no longer occurs, I assume so. Not sure wha the screenshot here is showing.

**Comment by alekseybobkov** [comment]
Please reopen the issue if needed.
