### ISSUE TITLE
Make the builder plugin extendable like other plugins

### ISSUE THREAD

**Issue by japomani** [rainlab/builder-plugin#110]
Builder is an amazing tool. I would like to extend menu items into builder's side bar to allow us to add interfaces to builder, the way we can other plugins and the settings interface.

Specifically I want to enhance builder to go a few steps farther to pre populate models, controllers, and DB tables with a template that does 65% of the work of making components and plugins for the Delphinium framework.

The way builder is designed right now prevents us from enhancing it and seems to break the "OctoberCMS way" of allowing very flexible extensiblity to any plugin, even one you did not create your self.

**Comment by daftspunk** [comment]
Thanks! And sorry if I am missing something here because I speed read issues. Have you read this documentation?

http://octobercms.com/docs/plugin/extending#extending-backend-menu

**Comment by xNok** [comment]
I agree that "extend menu items into builder's side bar to allow us to add interfaces to builder" is easy and documented. But I don't figure out how to extends existing feature :
* Override some Scaffolding templates
* Change associates behaviors

[From the documentation](http://octobercms.com/docs/plugin/extending#extending-component), to make the builder more extensible. We should add some extensibility by firering some events.

```
class Topic extends ComponentBase
{
    public function onPost()
    {
        [...]

        /*
         * Extensibility
         */
        Event::fire('rainlab.forum.topic.post', [$this, $post, $postUrl]);
        $this->fireEvent('topic.post', [$post, $postUrl]);
    }
}
```

**Comment by daftspunk** [comment]
I'm not quite sure what can be actioned from this. We will leave it as a comment for review at a later date.

**Comment by xNok** [comment]
@daftspunk should I understand that for the moment there is no way to extend class that are not related to a Model or a Controller. For example extend a class in the `behaviors` folder or in the `classes`. 

What can I concretely, do to override `$/rainlab/builder/classes/databasetablemodel/partials/fields.yaml` ?

**Comment by daftspunk** [comment]
Fields can always be extended using `form.extendFieldsBefore` and `form.extendFields`. See the https://vimeo.com/108040919 screencast for a demonstration of this.

If this is failing, happy to explore ways in which it can be improved to meet a specific requirement. It is hard to discuss solid solutions to conceptual ideas.
