### ISSUE TITLE
How to use plugin made by builder into other project?

### ISSUE THREAD

**Issue by shajidkhn26** [rainlab/builder-plugin#113]
I have created a plugin using builder which is a movie plugin and i am very thankful for creating builder which made plugin development easy.but only problem i am facing is that the plugin which i have made in one project i am unable to use in other project.Is there any way to use it in other project?

**Comment by daftspunk** [comment]
Your plugin should be located in the `/plugins` directory, you are able to copy it from one project to another. Then to migrate it, simply log out and sign in to the back end area.

**Comment by shajidkhn26** [comment]
Hey samuel thanks for your reply.Really i like octobercms it makes my work faster and clients are also happy.
the question i want to ask is that if i copy plugin to another project then the second project also need builder plugin installed in it or it will work without builder.
Thanks again

**Comment by daftspunk** [comment]
The short answer is: no, builder is not needed for the plugin to work. 

The long answer: Builder creates *real* plugins. The plugins generated by builder have no dependencies, not unless you add them yourself! 😄

**Comment by shajidkhn26** [comment]
ohh That plugin dependency i got it +1: 
Thank you for your all support and help....

**Comment by daftspunk** [comment]
No problem, have fun

**Comment by shajidkhn26** [comment]
sorry to disturb u again i have imported plugin made by builder 
i have made plugin using builder its name is movie
its structure is
shajid/movies/classes/controllers/lang/models/updates/plugin.php/plugin.yaml
this plugin will show list of movies like this
![untitled](https://cloud.githubusercontent.com/assets/19476995/18781712/9d3672dc-81a0-11e6-9f8e-78afa165c77e.png)

when he/she click on movie he will redirect to detail page where user can see gallery and detail of movie with its genre.
now when i import this plugin in my other project it does not show any thing it looks like this
![untitled1](https://cloud.githubusercontent.com/assets/19476995/18781809/00c36346-81a1-11e6-8c9e-960e68446545.png)

this is the code in my cms page in markup section
------------------------------------------------------------------------------
{% set records = builderList.records %}
{% set records = builderList.Shajid.Movies.Movie %}
{% set displayColumn = builderList.displayColumn %}
{% set noRecordsMessage = builderList.noRecordsMessage %}
{% set detailsPage = builderList.detailsPage %}
{% set detailsKeyColumn = builderList.detailsKeyColumn %}
{% set detailsUrlParameter = builderList.detailsUrlParameter %}

<ul class="record-list">
    {% for record in records %}
        <li>
            {# Use spaceless tag to remove spaces inside the A tag. #}
            
            <h3>
            {% spaceless %}
                {% if detailsPage %}
                    <a href="{{ detailsPage|page({ (detailsUrlParameter): attribute(record, detailsKeyColumn) }) }}">
                {% endif %}
               
                {{ attribute(record, displayColumn) }}<br>
                <img src="{{record.poster.thumb(200,auto)}}">
                 

                {% if detailsPage %}
                    </a>
                {% endif %}
            {% endspaceless %}
            </h3>
            {{ html_limit(record.description, 150)|raw }}
            
        </li>
    {% else %}
        <li class="no-data">{{ noRecordsMessage }}</li>
    {% endfor %}
</ul>

{% if records.lastPage > 1 %}
    <ul class="pagination">
        {% if records.currentPage > 1 %}
            <li><a href="{{ this.page.baseFileName|page({ (pageParam): (records.currentPage-1) }) }}">&larr; Prev</a></li>
        {% endif %}

        {% for page in 1..records.lastPage %}
            <li class="{{ records.currentPage == page ? 'active' : null }}">
                <a href="{{ this.page.baseFileName|page({ (pageParam): page }) }}">{{ page }}</a>
            </li>
        {% endfor %}

        {% if records.lastPage > records.currentPage %}
            <li><a href="{{ this.page.baseFileName|page({ (pageParam): (records.currentPage+1) }) }}">Next &rarr;</a></li>
        {% endif %}
    </ul>
{% endif %}
-------------------------------------------------------------------------------------------------
this is the code that i use in php section of the page
use Shajid\Movies\Models\Movie;

function onStart()
{
  $this['records'] = Movie::orderBy('id', 'desc')->get();
}
 ---------------------------------------------------------------------------------------------
not getting where i am doing mistake

**Comment by daftspunk** [comment]
Try watching this web series for more details, there is an example plugin on github that comes with it that should work: http://watch-learn.com/series/making-websites-with-october-cms

Best of luck.

**Comment by shajidkhn26** [comment]
Hey it is done.Actually i have watched the video of watch and learn it tells how to build plugin using builder but does not tell about using it into other project.when i import plugin into other project some of the classes are missing that i used.
secondaly i have watched your video of mastering components and create components using command line and finally completed.
The plugin is working fine.Getting confidence of building new plugin for my upcoming project "online bus ticket reservation".For that i will use octobercms. Thanks for all your help and support.
