### ISSUE TITLE
Misspelling

### ISSUE THREAD

**Issue by diaa1972** [rainlab/builder-plugin#115]
Expected behavior

when creating a new list column, one of the types is "**Time Since**".

Actual behavior

It shows "**Tine Since**" with an N not M

Reproduce steps

go to "plugins\rainlab\builder\lang\en\lang.php"
replacde 'Tine since' with 'Time since'

**Comment by daftspunk** [comment]
Fixed already in 5d1b8f88cd52438c29b7ddd4e20c5615483d7ffa
