### ISSUE TITLE
Creating new db record misbehavior 

### ISSUE THREAD

**Issue by diaa1972** [rainlab/builder-plugin#116]
**Expected behavior**

when creating a new table record, onEnter or on clicking Create button, it should save the record and stay on the same page (create.htm) to enable more records creation.

**Actual behavior**

It redirects to 'update.htm'

**Solution**

one way I solved this is:
Add 'data-request-data="redirect:0' to the submit button

**Comment by daftspunk** [comment]
Your solution is fine, the default behavior to redirect to `update.htm` is also fine.
