### ISSUE TITLE
Permissions & Backend menu storm js error

### ISSUE THREAD

**Issue by Tim4c** [rainlab/builder-plugin#117]
Hi, 
I'm currently trying OctoberCms and in particular your BuilderPlugin.
I have an error Javascript when i try to open "permissions" or "Backend menu".

`Uncaught TypeError: Cannot read property 'length' of undefined =>  storm-min.js?v365:4263 `

I tried to : 
- reinstall October and BuilderPlugin => Same error
- reload js file manualy from rainlab/builder/controllers/index.php => Same error

Do you have any ideas ?
Thx a lot.

**Comment by daftspunk** [comment]
I can't seem to replicate this using Build 365 and Build 371. Please provide step by step instructions from a clean installation. Are you changing the language, installing other plugins, anything like this?

**Comment by Tim4c** [comment]
Hi, 
Thx for your prompt reply. 
I just reinstall OctoberCMS and BuilderPlugin directly on my Debian server and i can't replicate (Build 365).
Consequently, this issue is related to my local environment. (Homebrew 1.0.7, Apache 2.2.31, Mysql 5.7.15, PHP 5.6.27). I tried clean installation on three differents computers but there are using almost the same server configuration (=> same error). I tried with MAMP and it works correctly.
Still looking for solution with homebrew...

**Comment by Tim4c** [comment]
I finally found a way to solve the issue by upgrading apache and by unloading the module fastcgi.

**Comment by Tim4c** [comment]
Hi, 
I have solved the problem at my work this morning by updating my php.ini.
`always_populate_raw_post_data = -1`
By this way, it's not necessary to update apache and unload module fastgci.

@++

**Comment by daftspunk** [comment]
Does this mean I can replicate it if I set this value to `1`?

**Comment by Tim4c** [comment]
I'm not sure...
It solves the problem on two computers running the same server configuration.
I just tried on my debian but i don't use fastcgi, consequently i can't replicate.
If you try it, let me know how it goes!
