### ISSUE TITLE
Page Not Found 404 when controller not containing LIST

### ISSUE THREAD

**Issue by businesstechca** [rainlab/builder-plugin#118]
Not sure it this a bug or a "feature" however I notice that if my model only contains a form the route is redirected to a 404 when the controller is added to the menu.

**Comment by daftspunk** [comment]
This might be due to the ListController supplying the `index()` action. The fix would simply be to add an index action to the controller along with an `index.htm` view file:

```
public function index() {}
```

**Comment by alekseybobkov** [comment]
@daftspunk is right - controllers don't provide the `index()` action by default. Builder doesn't provide the `index()` action if there's no list controller, because there can be other behaviours that include that action.
