### ISSUE TITLE
Menu permission and backend menu blank

### ISSUE THREAD

**Issue by ardani** [rainlab/builder-plugin#12]
in my octobercms menu permissions and backend menu blank.
picture:
http://prntscr.com/a1o9hg
http://prntscr.com/a1o9dg

**Comment by alekseybobkov** [comment]
There are no lists for the Permissions and Backend Menu sidebar items. Click those items just opens corresponding editor tabs.

![screen shot 2016-02-10 at 17 23 09](https://cloud.githubusercontent.com/assets/481606/12967407/15a63e42-d01b-11e5-929a-ce183b033331.png)

Please make sure that you run the latest build of October.
