### ISSUE TITLE
Error when adding fields to fields.yaml

### ISSUE THREAD

**Issue by DanielHitchen** [rainlab/builder-plugin#121]
**Expected behavior**

When user clicks on "Add Control" while working with a fields.yaml, the fields options should appear to select.

**Actual behavior**

When user clicks on "Add Control" while working with a fields.yaml, the below error is shown:

![error](https://cloud.githubusercontent.com/assets/7501909/19926334/e7ca9c32-a0eb-11e6-81e0-6cfc68956938.jpeg)

**Reproduce steps:**

1. Open up a plugin within Builder
2. Navigate to Models
3. Click on "fields.yaml"
4. Click on "Add Control"

**October Version:**

378

**Builder Version**

1.0.11

**Comment by daftspunk** [comment]
Fixed by https://github.com/octobercms/october/commit/6173ff177b729081a10c086ddfef2a8ebc6baec1
