### ISSUE TITLE
Selecting the "mediafinder" form widget should show Trigger API options (it is supported)

### ISSUE THREAD

**Issue by ivandoric** [rainlab/builder-plugin#122]
Media library field is missing trigger options in the UI. But if I edit fields.yaml file and add it by hand it works as expected. 

The problem is if you make changes via the UI, those trigger options get deleted. 

Guess this would be a bug, or missing feature.

**Comment by daftspunk** [comment]
As per the contribution guidelines, please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by ivandoric** [comment]
Ok, so I want to add media finder field to my model. In the UI there is no trigger option, in my case I needed it because I wanted to show that field when I choose a specific value from some other dropdown field for example.

So there is no trigger option in UI. That is fine, I go to fields.yaml and add a trigger to media finder. And everything works. But if go to the UI again make some change, and save it, the trigger that I added to media finder field in fields.yaml is now gone. And I would have to add it again.

The way I see it obvious solution would be to just add trigger option to media finder in UI. Because as I understand it, every time you hit Save in the UI it overwrites fields.yaml file. And since there is no option for the trigger in the UI that option gets overwritten.

Please let me know if you need anymore info.

**Comment by daftspunk** [comment]
Hey @ivandoric, thanks for the detailed report. We just need some simple steps to follow that will reproduce the issue, along with the expected and actual behavior.

> We work hard to process bugs that are reported, to assist with this please ensure the following details are always included:
> 
> - **Bug summary**: Make sure your summary reflects what the problem is and where it is.
> 
> - **Request location**: Enter the URL where this bug occurs, if applicable.
> 
> - **Reproduce steps**: Clearly mention the steps to reproduce the bug.
> 
> - **Expected behavior**: How OctoberCMS should behave on above mentioned steps.
> 
> - **Actual behavior**: What is the actual result on running above steps i.e. the bug behavior - **include any error messages**.

Feel free to submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it *using the test plugin*.

**Comment by ivandoric** [comment]
I already provided detailed steps. But ok. Here are the steps for reproducing the bug in numbered form :) .

1. Builder -> Plugin -> Models -> Fields 
2. Add a Media Finder field.
3. Realize that Media Finder doesn't have trigger options

![no-trigger](https://cloud.githubusercontent.com/assets/6043540/20130477/541d63e0-a657-11e6-8e25-5595e8baa065.jpg)

4. Go to plugins/author/plugin/models/model-name/fields.yaml
5. Add trigger there by hand. For example:

```yaml
trigger:
    action: show
    field: block_chooser
    condition: 'value[mob_text]'
```

6. Trigger now works - yaaay :)
7. Go back to Builder -> Plugin -> Models -> Fields in the backend UI
8. Make any kind of change and save
9. Trigger now does not work because the fields.yaml file got overwritten 


**Solution:** Add Trigger options to the UI of Media finder field.

**Comment by daftspunk** [comment]
Got it! It took less than 10 seconds this time! Thanks for the detailed explanation, there is only limited attention span I can give each issue.
