### ISSUE TITLE
Empty list of plugins while there are plugins already created

### ISSUE THREAD

**Issue by meysammahfouzi** [rainlab/builder-plugin#123]
The list of plugins is empty, unless I click on the filter button (next to "+ Create plugin") causing all of the plugins to appear. 

![dashboard](https://cloud.githubusercontent.com/assets/14848008/20456672/462e0956-ae90-11e6-8c1c-a332a82d72a7.png)

**Comment by daftspunk** [comment]
The filter will show plugins that you "own", determined by your namespace. This can be updated via **Settings > Misc > Builder**. Make sure there is a value stored in here and that the value matches the namespace of the plugins you own and thus are displayed when the filter is applied.

**Comment by meysammahfouzi** [comment]
@daftspunk You are right. After fixing the namespace name via **Settings > Misc > Builder**, everything worked as expected. Thank you :)
