### ISSUE TITLE
How create component in my plugin

### ISSUE THREAD

**Issue by bahman2216** [rainlab/builder-plugin#125]
I made plugin with builder but it does not create component! I made component manually, But in CMS page got error: Class \Author\MyPlugin\Components\MyComponent does not exist

I run october:up and also dump-autoload but still have error

**Comment by TimFoerster** [comment]
Make sure that you registered the component:
see https://octobercms.com/docs/plugin/components#component-registration

**Comment by SchneiderDe** [comment]
Hi,

Exactly thats the reason why I created the following Issue:

https://github.com/rainlab/builder-plugin/issues/131

**Comment by alekseybobkov** [comment]
Please follow the component development documentation. Builder does not provide any features for creating or managing plugin components.
