### ISSUE TITLE
Please provide a Wizard to create a plugin!

### ISSUE THREAD

**Issue by SchneiderDe** [rainlab/builder-plugin#131]
Hello,

Currently most of the features and functions are already there. Any experienced user will be able to create a plugin with lots of features and functions right away with the Builder plugin. However, it took me - as a newbie - hours to find things out what I needed to do and where, while working with the Builder plugin.

I suggest that you provide a Wizard to give a guided process step by step. Not too difficult. 

It helps everyone to invoke a new plugin process and keep on feeding values.

It should lead to pages which requires an input first.

It should also help in establishing relationships to other existing plugins and components as well as pulling values from other tables, i.e. especially using dependent drop downs with values that are based on other internal database tables.

This means a special feature, which says "Create an extended plugin of an existing one". With this, for e.g., I could create an extended plugin that is based on User or Location plugin. Consequently, the original Rainlab plugin remains intact and the Builder only creates respective details, data and linkages based on the existing ones with new names, etc.

**Comment by LittleTom** [comment]
`http://octobercms.com/support/article/ob-18`
This is what you need.

**Comment by SchneiderDe** [comment]
Hi LittleTom,
Thanks for the hint.
A short answer is "NO". I have placed this message only after watching these Videos.
I have successfully built my own plugin that works without problems. Only because of my experience to work with the Builder Plugin and acquiring sufficient knowledge, I have opened the issue, which I consider have done so after sufficient investigation myself, training overall the required and giving a deep thought on the process of making a new plugin.
Thus any further suggestion by anyone, or even by the developers, that draws attention away from my Issue opened is not supportive or helpful at all.

**Comment by alekseybobkov** [comment]
I think this is more a question of learning and experience than the Builder implementation. Even if the Wizard existed, there's always a room for questions and the trial and error method. Builder is a complex development tool which incapsulates many plugin development tasks into a single user interface. Spending several hours to grasp concepts of a new system is expected.
