### ISSUE TITLE
Feature Request - Add "readOnly" option to fields

### ISSUE THREAD

**Issue by gavinworks** [rainlab/builder-plugin#134]
Currently there is no way to set fields to "readOnly: true" via Builder. Each time the field is updated via Builder the "readOnly" flag is removed from the field definition in the fields.yaml file. Small annoyance which would be nice to have fixed :)

**Comment by LukeTowers** [comment]
@gavinworks feel free to make a PR adding it to the default field properties. See https://github.com/rainlab/builder-plugin/blob/master/classes/ControlLibrary.php#L159

**Comment by bennothommo** [comment]
This is now available as of 95f34514d7e7e64383a0fcb3b0b467d1cdb121dc.

**Comment by gavinworks** [comment]
We love @bennothommo !!
