### ISSUE TITLE
Required is not required

### ISSUE THREAD

**Issue by Zmove** [rainlab/builder-plugin#135]
Hello,

I'm testing the builder plugin and I followed the video tutorial (with acme.library) plugin.

I can have a my list of books, it works well, except that the required fields are not required. 

I checked the "required" checkbox in the model > fields.yaml file, I can see the little red dot in the backend when I create a new book, but I can save the form with all values empty and october accept it.

Did I miss something ?

Thanks

Alex

**Comment by Zmove** [comment]
Found the answer [here](https://octobercms.com/docs/backend/forms#form-fields), it's said that the required value is just to display the small red dot, but the field is not really required...

I know that one of the basic concept of the builder plugin is to don't touch php file, but I also know that it's purpose is to make developper life easier and coding fun again, and to me, there is a conflict here.

Would it be possible, when creating the model php file, to have small automatic snippet added that loop throught fields in the .yaml file, set required validation for required fields. It would be always the same code, so it's not really 'touching php file'.

Alex

**Comment by daftspunk** [comment]
We do plan to make `required: true` enforceable, rather than aesthetic. For now the `Validation` trait should be used.
