### ISSUE TITLE
Slug depending on 2 fields

### ISSUE THREAD

**Issue by Zmove** [rainlab/builder-plugin#136]
Hello,

Is it possible to automatically generate slug field depending on 2 fields ?

For example, I have a firstname and lastname field, I want the slug to be "lastname-firstname"

Thanks

**Comment by seanthepottingshed** [comment]
public function beforeSave()
{
    $this->slug = Str::slug($this->first_name . ' ' . $this->last_name);
}

**Comment by Zmove** [comment]
Thank you for your answer. But it seems to transform the slug before saving it in the database. I would like to see the slug field with dynamic auto input, like the books of the demo.

**Comment by seanthepottingshed** [comment]
Use JavaScript

**Comment by Zmove** [comment]
Hmm ok, so I have to write my custom javascript to concatenate the slug for the 2 fields? There are no way to do that just using the UI or editing yaml files ?

**Comment by seanthepottingshed** [comment]
I guess if that's important to you then I would assume so

**Comment by Alex360hd** [comment]
Ok thanks for your answers.

**Comment by LukeTowers** [comment]
@Zmove presently there isn't a way to concatenate inputs to form a slug. You can however take the value for a slug from a single other field: http://octobercms.com/docs/backend/forms#field-input-preset

**Comment by Zmove** [comment]
Thanks for the answer, I think we can close the issue as there are solution. And it's probably too specific to be handled by default.

**Comment by paishin** [comment]
Sorry to comment on such an old thead. I am faced with a similar issue and I was wondering if there is any way to create custom input presets.
(In my case I just want to convert to uppercase)

**Comment by w20k** [comment]
JS or beforeSave ;)

**Comment by paishin** [comment]
I am actually doing it using a custom input form field with javascript that converts input to uppercase. I just thought it would be much better if I could create my own presets i.e. uppercase, lowercase, capitalize, kebab, integer, float, currency etc or the ability to add regex rules instead of creating a custom input field for each one.
