### ISSUE TITLE
Image display option with media finder widget type

### ISSUE THREAD

**Issue by Zmove** [rainlab/builder-plugin#137]
Hello,

I continue my tests with the builder plugin and I noticed one annoying thing.

The media finder plugin is extremly useful to not force people to upload an image that would be already present on the server.

However, there are some missing options like image cropping, compared to the file upload widget.

I chose a 1000x1000px image in my media finder library, and the backend display my 1000x1000px image. I would like to have some options to limit the size of the image in the backend, exactly like the file upload widget provide.

Thanks

**Comment by LukeTowers** [comment]
Support implemented in https://github.com/octobercms/october/commit/92a5b9ab229ffffd3e7ea56cd8a00c2b6bfcc90d and https://github.com/rainlab/builder-plugin/commit/46cb38b4f8acd27eaf633b64ca20575c75b00566
