### ISSUE TITLE
Media finder for multiple images

### ISSUE THREAD

**Issue by Alex360hd** [rainlab/builder-plugin#139]
Hello,

The media finder is a great widget for image upload or selection in a model form, but it would be great to be able to use it to manage several images which doesn't seems possible actually.

What do you think about it ? Can it be planned, or will you wait for a pull request to consider it ?

Thanks

**Comment by LukeTowers** [comment]
@Alex360hd Use it within a repeater and boom done :)

**Comment by Alex360hd** [comment]
Hello,

I will try to find some examples on google with media finder and repeaters. I'm discovering october cms and, more generally, laravel, so I have to learn a lot of things. ^^

thank you for the answer !

**Comment by LukeTowers** [comment]
http://octobercms.com/docs/backend/forms#widget-repeater

**Comment by Alex360hd** [comment]
Thanks, it works.

However the UI is not very good, you have to add a new element, then open the media finder to select one image, then add a new element, then open the media finder etc....

It would be far better to be able to select several files directly with the finder, but maybe low priority as the job can be done actually.

**Comment by LukeTowers** [comment]
Yup, it isn't the greatest for UX, but we'd need to build multi image support into the mediafinder widget itself in October to change that. You're more than welcome to work on implementing that functionality and make a PR for it if you'd like :)

**Comment by Alex360hd** [comment]
I will when I will have the level to do that. Actually, I'm learning October and Laravel at the same time, so I'm far to work on things like this (but it will come... one day ^^)

**Comment by gwonzhang** [comment]
I did have the same question, now I know how to do it. Thank you guys for above answers.

**Comment by daftspunk** [comment]
We have this on our internal tracker to implement already

**Comment by PubliAlex** [comment]
Would it be possible to get an ETA of this ? I think it would not be a huge thing to save the images in an array rather than a single string when the media manager is in a "multiple" mode, but maybe I'm underestimating the complexity of it.

**Comment by daftspunk** [comment]
Probably next feature release (v2.2)

**Comment by PubliAlex** [comment]
How, that would be awesome !
