### ISSUE TITLE
Database prefix

### ISSUE THREAD

**Issue by janvandelaar** [rainlab/builder-plugin#143]
When I set a prefix in database.php before installing the installprocess works just fine. Databasetables are created with the desired prefix, When I create my plugin with Builder and add a new databasetable, the table is created with the prefix as well (as i can see in phpmyadmin), but when I want to save it again Builder throws an exeption stating that the table doesn't exist. The table name shown in the exeption is written without the prefix. Is there a way to avoid this?

**Comment by grafxflow** [comment]
Unsure if I am experiencing the same issue? I install the October CMS then change the config and prefix after. In the builder plugin it actually creates the database tables fine, but they don't appear in the builder plugin dashboard. If I try again I get an error saying it already exists which they via phpMyAdmin.

**Comment by LukeTowers** [comment]
@grafxflow see #181

**Comment by grafxflow** [comment]
Cheers LukeTowers. Sorts the issue :)

**Comment by daftspunk** [comment]
Fixed by #181
