### ISSUE TITLE
Orange header with tabs like the rainlab blog plugin

### ISSUE THREAD

**Issue by Alex360hd** [rainlab/builder-plugin#145]
Hello,

I'm creating a module using the builder plugin and I would like to have the same orange heading (with title and slug) and dark tabs row.

I organised my fields the same way than the blog plugin (I opened the blog plugin in the builder to see how it was done) but I don't have the same result. All my fields are in the light grey area which is not very sexy....

What did I miss, how can we have the same styling than the rainlab blog plugin ?

Thanks

**Comment by LukeTowers** [comment]
Look at the controller views for the blog plugin, and the controller for the blog plugin. You'll see how it's done.
