### ISSUE TITLE
Right sidebar in model form

### ISSUE THREAD

**Issue by Alex360hd** [rainlab/builder-plugin#146]
Hello,

It would be great to be able to put form elements into a right sidebar in backend.

(See an example with this plugin)[https://octobercms.com/plugin/netsti-frontend]

I looked at the module, actually, it's done by "hacking" the secondary tabs element. It would be great to have a real sidebar wrapper in model form to create interfaces like this without any hacking.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
