### ISSUE TITLE
Using the Location Address Finder Widget in Builder

### ISSUE THREAD

**Issue by chrisvidal** [rainlab/builder-plugin#147]
The Rainlab Location plugin is providing an AddressFinder widget.
How can i use this widget in a model fields.yaml with the builder ?
thanks

**Comment by LukeTowers** [comment]
@chrisvidal you would have to extend this plugin from the RainLab.Location plugin to define the AddressFinder widget. See https://github.com/rainlab/builder-plugin/blob/master/Plugin.php#L122 to start.
