### ISSUE TITLE
Scrolling is broken when adding lots of fields to the column.yaml

### ISSUE THREAD

**Issue by priitperna** [rainlab/builder-plugin#149]
The table view used for creating the model list only works if you have less rows that can fit on the screen. If you have, lets say, a hundred rows there, the table is scrolled to the bottom and the top section (the orange part) is not visible. You cannot scroll up.

The same thing works in the database table view.

It seems that the model list view is missing some js scrolling functionality.

If you give me a directon on where to fix it, I could create a PR myself.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
