### ISSUE TITLE
Invalid Model Class Name when creating a Page

### ISSUE THREAD

**Issue by woodgates** [rainlab/builder-plugin#150]
Hi.
This plugin looks awesome, and has worked ok for me in all the backend process. I can create and delete items.
But when I design the front end pages I get an "Invalid Model Class Name" in the "Records Detail" and in the "Records List" Components.
I get to see the information on the front page but the error is very annoying. 

![invalid_class_name](https://cloud.githubusercontent.com/assets/5682960/24415658/902527dc-13b8-11e7-87e2-4b900085c488.png)

**Comment by qroft** [comment]
Me too. And i can not een find where i can change the Model Class within the code

**Comment by LukeTowers** [comment]
Exception is thrown here: https://github.com/rainlab/builder-plugin/blob/986bbea1b0d6bc163c0316c5fcdbe4c93acd4255/classes/ModelYamlModel.php#L33-L35

What class names are you using that would trigger this?

**Comment by zaxap83** [comment]
And I had the same problem. Exception is thrown in ComponentHelper (ModelModel::validateModelClassName). Method validateModelClassName has string "return preg_match('/^[A-Z]+[a-zA-Z0-9_]+$/', $modelClassName)", so a first letter in the class name must be upcase. First part in the class name is an author name, so its first letter must be upcase.

**Comment by vkscorpion1986** [comment]
I'm also getting the same issue, any suggestions or solution?

**Comment by LukeTowers** [comment]
> What class names are you using that would trigger this?
@vkscorpion1986

**Comment by zaxap83** [comment]
@vkscorpion1986 

> Method validateModelClassName has string "return preg_match('/^[A-Z]+[a-zA-Z0-9_]+$/', $modelClassName)", so the first letter in the class name must be upcase. First part in the class name is an author name, so its first letter must be upcase (Woodgates, Qroft, Zax etc).

**Comment by LukeTowers** [comment]
@qroft still getting this?

**Comment by tleish** [comment]
See workaround on #202

**Comment by LukeTowers** [comment]
Fixed in https://github.com/rainlab/builder-plugin/commit/7efae36016f980a6383f6cb308893311efbf1618
