### ISSUE TITLE
Ability to ReOrder the records from listing

### ISSUE THREAD

**Issue by mittultechnobrave** [rainlab/builder-plugin#152]
I have been using this plugin to create my plugins and I found it very useful indeed.

However, I have one requirement which I would like to implement in one my plugins called as "Slider" and here below I mentioned what I want to deal with.

My Slider plugin simply contains an ability to upload images from admin (backend) and it is showing up front-end of the website. 

Currently I have made a database query at front end to either show it in Ascending or Descending order but I want something like [this](https://jqueryui.com/sortable/) . Client should be able to sort those slider images which he/she has been added from admin and it will show up front based on this updated list. 

It is possible as of now or do I need to update plugin or need to find another way to implement this ? 

Any help or suggestion will be highly helpful for me. 

Thanks

**Comment by CptMeatball** [comment]
Not sure how you've structured this plugin, but if you've attached the images through the `attachMany` relation, the sort order can be easily done by rearranging the photos in the upload form.

**Comment by rhonz10** [comment]
You need to enable Reorder controller behavior on your slider controllers when you created it.

Check this out:
https://octobercms.com/docs/backend/reorder

Also take note that your slider table should have a sort_order field.
https://octobercms.com/docs/database/traits#sortable

You need to add this link button on your _list_toolbar.htm as it is not added by default.
`<a href="<?= Backend::url('bdsoft/team/team/reorder') ?>" class="btn btn-primary oc-icon-sort">Reorder Members</a>`

 Replace the url to with the correct one.

I hope this helps.

**Comment by mittultechnobrave** [comment]
Well I need to reorder by drag an drop and show updated order list something like this https://jqueryui.com/sortable. Not sure your provided links do this.

**Comment by rhonz10** [comment]
I gave the link for you to check if your controllers implements reorder behavior, and your models use sortable traits, and your slider table have sort_order field. Without those, reorder by drag and drop won't work, even if you have the button added on your _list_toolbar.htm partial.

Go ahead and check them out first, then add the `<a>` tag on your _list_toolbar.htm partial, which I mentioned on my previous reply.

**Comment by mittultechnobrave** [comment]
Thank you. I will check and get back to you on this thread by mentioning you if I anything goes wrong or any query. 
Thanks. Appreciated.

**Comment by tsioukas** [comment]
Now you can use reorder only with reorder trait using /reorder page. Maybe it is better for future implementation to add the functionality to reorder directly from record list and not from a different page.

**Comment by rhonz10** [comment]
I agree with you.
