### ISSUE TITLE
Builder array to string conversion by viewing fields.yaml

### ISSUE THREAD

**Issue by marschiaan** [rainlab/builder-plugin#156]
By opening the inspector in a form to view the settings of a formfield (fields.yaml), and this form belongs to a model with database-tabel defined as "protected"

`protected $table = "tablename";`

following error is shown:

`Array to string conversion in octobercms/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php:36`

because the defined tablename is empty.

![bildschirmfoto 2017-04-22 um 18 56 49](https://cloud.githubusercontent.com/assets/21959411/25306437/8d99b30a-278d-11e7-8b9b-db654fa7c149.png)

Some debugging later i came to file `RainLab\Builder\Classes\ModelFileParser.php line 44`:

```
if ($tokenCode == T_PUBLIC) {
                $tableName = $this->extractTableName($stream);
                if ($tableName === false) {
                    continue;
                }

                if ($tableName === null) {
                    return null;
                }

                $result['table'] = $tableName;
            }
```

By changing line 44 to:
`if ($tokenCode == T_PUBLIC || $tokenCode == T_PROTECTED)`

it would solve the described error.

Would it make sense to change that in core? 
Or will be more senseful fo the future to define `$table` as `public` ?

**Comment by LukeTowers** [comment]
It would make more sense to fix the bug as the [official October docs](http://octobercms.com/docs/database/model#defining-models) say to define the table name as protected. Could you please make a pull request to fix that?

**Comment by LukeTowers** [comment]
Never mind, fixed it myself. Thanks for finding this!
