### ISSUE TITLE
Show ReOrder button on the backend list when Reorder behavior is enabled on controllers.

### ISSUE THREAD

**Issue by rhonz10** [rainlab/builder-plugin#157]
Hi! 
First of all, thanks for this great plugin. It helped me a lot in understanding how to create my own plugin.

My issue is that builder does not add the reorder link to the _list_toolbar.htm. I have to manually add a link to the toolbar partial to have it displayed.

`<a href="<?= Backend::url('bdsoft/team/team/reorder') ?>" class="btn btn-primary oc-icon-sort">Reorder</a>`

Am I doing it wrong from the start, or it's a missing feature, or intentionally left like that? A bug maybe?

Thanks.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

**Comment by LukeTowers** [comment]
Fixed by #197
