### ISSUE TITLE
Table Editor not scrollable

### ISSUE THREAD

**Issue by alxy** [rainlab/builder-plugin#16]
I just figured, that the columns editor is not scrollable. That is a problem when dealing with a bigger amount of columns: https://www.dropbox.com/s/bbst5wros52kz4h/Screenshot%202016-02-11%2017.45.39.png?dl=0

As you can see, it cuts the columns at the bottom and there is no chance to scroll down.

**Comment by filipac** [comment]
ran into this issue too :) :+1:

**Comment by alekseybobkov** [comment]
It's planned. Thanks!

**Comment by tsioukas** [comment]
Also it's better add sort feature on Models Lists columns for default sorting.

**Comment by jonoirwinrsa** [comment]
quick/dirty fix is to search for fancy-layout and set overflow to scroll. - not sure if that would help anyone but thought I would say anyways :)

**Comment by alekseybobkov** [comment]
This was fixed in the version 1.0.7.
