### ISSUE TITLE
Add taglist to form widget

### ISSUE THREAD

**Issue by Zmove** [rainlab/builder-plugin#160]
Hello,

October CMS include a "taglist" form element that allow dropdown multiselect, but you can't find it in the widget selection of the builder. I think it should be added as it's a very  useful form element.

Regards,

Alex

**Comment by LukeTowers** [comment]
Feel free to add it yourself and make a PR: https://github.com/rainlab/builder-plugin/blob/master/classes/StandardControlsRegistry.php#L39.

**Comment by bennothommo** [comment]
This is now available as of 9757a91748e6c8d34ec195682561d5b44ed52187. It will be released with v1.0.24 of the Builder plugin.
