### ISSUE TITLE
stdClass::$column_name while creating new model

### ISSUE THREAD

**Issue by darki73** [rainlab/builder-plugin#161]
Hello, just installed this plugin and trying to work with it. However, when i try to create new model, im getting the following error:
`"Undefined property: stdClass::$column_name" on line 18 of D:\WebServer\Projects\Univer\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\MySqlProcessor.php`

**What i did:**

1. Created new database table (through the builder)
2. Tried to create new model (builder can see new database table)
3. Upon clicking on the OK button, im getting error i've mentioned above

**Comment by darki73** [comment]
Okay, i've found error:
Illuminate\Database\Query\Processors\MySqlProcessor.php line 18:
`return $r->column_name;`
However, object contains column_name in upper case, so the following piece of code fixes problem:
`return $r->COLUMN_NAME;`
BUT, this is vendor package, so the error somewhere in the builder plugin

**Comment by stefina** [comment]
I ran into the same problem and I could reproduce that the code-change @darki73 suggested fixed it.

**Comment by LukeTowers** [comment]
Fixed by https://github.com/laravel/framework/pull/21037
