### ISSUE TITLE
Error when saving a table when using a PostgreSql

### ISSUE THREAD

**Issue by nozreh** [rainlab/builder-plugin#163]
I'm creating a new Plugin using the Builder Plugin and adding a new table but I'm not able to save it due to some error, see below.

`"Unknown database type json requested, 
Doctrine\DBAL\Platforms\PostgreSqlPlatform may not support it." on line 423 of /var/www/omh.dev/public/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php`

**Comment by LittleTom** [comment]
You can edit this file `'\vendor\doctrine\dbal\lib\Doctrine\DBAL\Platforms\PostgreSqlPlatform.php`'
find  `function initializeDoctrineTypeMappings()`,
insert` 'json' => 'text', 'jsonb' => 'text'` to solve the error.

**Comment by nozreh** [comment]
@LittleTom Thanks for the info, problem solved!
