### ISSUE TITLE
Repeater : Option to automatically collapse them

### ISSUE THREAD

**Issue by Zmove** [rainlab/builder-plugin#165]
Hello,

The repeater widget is an awesome addition to october CMS.

However, it would be really useful to have some options to manage default behaviors of collapse/expand system.

Basically, when I enter my model form, I would like to see all repeater item as collapsed for a better global view. Also, when I add a new repeater item, I would like to collapse it immediatly for easier ordering.

The best solution would be to be able to confiture that behaviors directly in the builder plugin.

Do you think it's possible ?

Regards,

Alex

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

**Comment by martendej** [comment]
I'd like to re-open this issue, as I think being able to collapse repeater fields by default is not so much an enhancement but a necessity at times when using many fields within the repeater. I have encountered this quite a few times now. Ideas?

**Comment by LukeTowers** [comment]
@martendej could you post some gifs or screenshots demonstrating the issue?

**Comment by LukeTowers** [comment]
Will be implemented in https://github.com/octobercms/october/pull/4877
