### ISSUE TITLE
Model Icon disappeared - is a typo

### ISSUE THREAD

**Issue by ArchimedeSolutions** [rainlab/builder-plugin#166]
Hello,
in Plugin.php there's a typo, a double 'r' in permissions field:

....
    public function registerNavigation()
....

                    'models' => [
                        'label'       => 'rainlab.builder::lang.model.menu_label',
                        'icon'        => 'icon-random',
                        'url'         => 'javascript:;',
                        'attributes'  => ['data-menu-item'=>'models'],
                        'permissions' => ['rrainlab.builder.manage_plugins']

Regards, Salvatore Brosio

**Comment by LukeTowers** [comment]
Fixed by https://github.com/rainlab/builder-plugin/commit/74ab4bc9c3c9a4da5a312545cc084f98d1d2c31c. Thanks for reporting this, probably no-one spotted this because typically only super users are using this plugin.
