### ISSUE TITLE
Repeater : problem to insert data to database

### ISSUE THREAD

**Issue by mitulkoradiya** [rainlab/builder-plugin#167]
Hello,

The repeater is an awesome addition to october CMS.

I have problem to insert repeter value in database. Bellow attach the screen shot of error.

![1](https://user-images.githubusercontent.com/13043276/28586325-02513acc-7191-11e7-8d75-9b653c6e54cc.png)

![2](https://user-images.githubusercontent.com/13043276/28586336-0a4b25b2-7191-11e7-9522-c52056cf62ee.png)

What is the problem?

Thanks.

**Comment by pvullioud** [comment]
The field should be "jsonable" see documentation https://octobercms.com/docs/database/model#standard-properties

```php
class YourClass  extends Model
{
...
    protected $jsonable = ['images'];
...
}
```
