### ISSUE TITLE
Front end record display won't sort correctly

### ISSUE THREAD

**Issue by agrantham** [rainlab/builder-plugin#17]
I have a model with a  column "order" as an "int" data type. I have been trying to set the records to be displayed by that column and it does not work. I have changed the data type to a string to see if that changed anything by having them sorted alphabetically but that did not work either. I also added this into my controller:
`public function listExtendQuery($query,$definition = null) 
{ 
  $query->orderBy("order","sac");
}
`

Nothing I do seems to change the order of the records on the front end. 

Any help or anyone else run into this issue? 

Thanks!

Austin

**Comment by alekseybobkov** [comment]
Hi Austin, can you show the code of the page where you use the RecordList component? I would like to take a look at the component configuration code. Example:

```
title = "Book list"
url = "/books/:page?"

[builderList]
modelClass = "RainTest\MyLibraryPlugin\Models\Book"
sortColumn = "order"
displayColumn = "title"
noRecordsMessage = "No records found"
==
{% component 'builderList' %}
```

**Comment by agrantham** [comment]
Here it is:
```
title = "Test page Two"
url = "/test-page-two"
layout = "sub-page"
is_hidden = 0

[builderList]
modelClass = "Agrantham\Promotions\Models\ListItems"
scope = "-"
displayColumn = "order"
noRecordsMessage = "No records found"
detailsPage = "-"
detailsUrlParameter = "id"
pageNumber = "{{ :page }}"
sortColumn = "order"
sortDirection = "asc"
==
{% set records = builderList.records %}
{% set displayColumn = builderList.displayColumn %}
{% set noRecordsMessage = builderList.noRecordsMessage %}
{% set detailsPage = builderList.detailsPage %}
{% set detailsKeyColumn = builderList.detailsKeyColumn %}
{% set detailsUrlParameter = builderList.detailsUrlParameter %}

<!-- ... -->
        <ol class="carousel-indicators  hidden">
           {% for record in records %}
                    <li data-target="#carousel-example-generic" data-slide-to="{{loop.index0}}" {% if loop.first %}class="active" {% endif %}></li>
            {% endfor %}
        </ol>
        <div class="carousel-inner" role="listbox">
            {% for record in records %}
                     <div class="item {% if loop.first %}active {% endif %}">
                        <a href="{{record.target_url}}" >
                            <img src="/storage/app/media{{record.src}}" alt="{{record.name}}">
                        </a>
                    </div>
            {% endfor %}
        </div>
```

**Comment by alekseybobkov** [comment]
The code looks good to me. What values you have in the `order` column? Builder (and OctoberCMS in general) doesn't support any automatic sorting methods. Your models should maintain the sorting column values. Usually records are sorted by the creation date, or id, or some title column.

**Comment by artras** [comment]
I also have thise problem 
My code is : 
`
[builderList]
modelClass = "Cunami\CarCatalog\Models\Car"
scope = "-"
displayColumn = "id"
noRecordsMessage = "No records found"
detailsPage = "transports"
detailsKeyColumn = "id"
detailsUrlParameter = "id"
pageNumber = "{{ :page }}"
sortColumn = "id"
sortDirection = "desc"
[builderList]
modelClass = "Cunami\CarCatalog\Models\Car"
scope = "-"
displayColumn = "id"
noRecordsMessage = "No records found"
detailsPage = "transports"
detailsKeyColumn = "id"
detailsUrlParameter = "id"
pageNumber = "{{ :page }}"
sortColumn = "id"
sortDirection = "desc"

==
<table>
{% for car in cars %}
        <tr onclick="document.location='{% spaceless %}{{ detailsPage|page({ (detailsUrlParameter): attribute(car, detailsKeyColumn) }) }} {% endspaceless %}';">
            <td class="catalog-table_photo">
                <a href="{% spaceless %}{{ detailsPage|page({ (detailsUrlParameter): attribute(car, detailsKeyColumn) }) }} {% endspaceless %}">
                    {% set image = car.images.first %}
                    <img src="{{ image.path }}" alt=""></a>
            </td>
            <td>{{ car.marka}} {{ car.modelis}} </td>
            <td class="hidden-xs">{{ car.atrumkarba |_}}</td>
            <td class="hidden-xs">{{ car.motors }} {{ car.dzinejs |_}}</td>
            <td>{{ car.gads}}</td>
            <td class="catalog-table_content visible-md visible-lg">{% filter slice(0,135) %}{{ car.apraksts | striptags}}{% endfilter %}...</td>
            <td>  {% if car.akcijascena %}{{ car.akcijascena}} € {% else %} {{ car.cena}} €{% endif %}
                <span class="catalog-table_lizing hidden-xs">
                    <a href="{{ '/lizings' |app }}" class="text-gold"> {{ 'Izdevīgs līzings!!'|_}}</a>
                </span></td>
        </tr>
{% endfor %}
</table>

`



Byt list do not sort by ID

**Comment by agrantham** [comment]
I originally tried it as an 'integer' data type and storing values of 0, 5, 10, 15, 20, and so on in the field for each item. Sorting on the column didn't work so I changed the column's data type to a 'varchar' and made the values a, b, c, d, e, and so on and it still did not work.  I haven't modified much of anything else as far as sorting with the exception to filter out records that have past the set expired date. 

Let me know what your thoughts are or if I should just manually sort the record list from the model before pushing it through to the front end.

**Comment by agrantham** [comment]
Some more details. I just recently tried implementing the Reorder feature into the items and I can visibly see the items on the reorder page on the backend end. It even looks like I am successfully reordering them but when displayed on the front end no order is changing.

**Comment by alekseybobkov** [comment]
It's fixed now. Thanks!
