### ISSUE TITLE
Add balloon selector to the widget list

### ISSUE THREAD

**Issue by Alex360hd** [rainlab/builder-plugin#170]
Hello,

October CMS provide a nice balloon selector form widget as an alternative to the dropdown list. It would be great to add it to the Builder widget list to avoid to manually edit the fields.yaml file.

It would be even better to add some exclusive options for that widget, like the others.

Not important or urgent issue, but need to be done one day for coherence.

**Comment by LukeTowers** [comment]
@Alex360hd feel free to make a PR to add it yourself. See https://github.com/rainlab/builder-plugin/blob/master/classes/StandardControlsRegistry.php#L32

**Comment by LukeTowers** [comment]
@Alex360hd finally got around to adding it myself, was a huge pain (had to implement a fix to the auto generation of fieldNames as a part of this!)

**Comment by LukeTowers** [comment]
Took around 2 hours to get everything sorted out (which also included issues with symlinking just one plugin and generating public asset paths). If everything had worked fine it probably only would have taken half an hour to do.

**Comment by LukeTowers** [comment]
But I digress, it's available now.
