### ISSUE TITLE
How to implement lazy loading / infinite scrolling in Builder's recordList component?

### ISSUE THREAD

**Issue by scazzy** [rainlab/builder-plugin#174]
I'm using Builder Plugin and it's recordList component to display the data list. While pagination works fine, I wanted to implement load more to implement pagination which would fetch data and partial using october's ajax handler and append below the list.

**Comment by Alex360hd** [comment]
Hello,

I could do this with some javascript :

    function formPaginate() {
	if($('form[data-request]').length) {
		
		$('.pagination a').off().on('click change', function(e) {
			e.preventDefault();
			var form = $('form[data-request!=""]');
			var request = form.attr('data-request');
			var partials = jQuery.parseJSON('{ '+form.attr('data-request-update')+' }');
			var page = $(this).attr('href').split('/').pop().trim();
	
			// On effectue la requête ajax
			form.request(request, {
				data: { 'page': page },
				update: partials,
			});
			
		});
		
	}
    }

The idea behind this code is that when you have a form with data-request attribute, it means it's an ajax form, so, when you click on your pagination link, you prevent the url redirection, you extract the page number from that URL, and you trigger the ajax request by passing the page argument.

Hope that help
