### ISSUE TITLE
Can't use underscore as the first character for field names

### ISSUE THREAD

**Issue by datune** [rainlab/builder-plugin#176]
In order to prevent a field from being submitted, an underscore can be added to the name (https://octobercms.com/docs/backend/forms#prevent-field-submission), however, the builder plugin throws an error message:

"The field name can contain only Latin letters, digits, underscores, dashes and square brackets."

**Comment by LukeTowers** [comment]
Thanks for reporting this, I've fixed it in https://github.com/rainlab/builder-plugin/commit/d49a17283bed36ebb9fc5838e6e241b958b7c0b5.
