### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by coder1coder** [rainlab/builder-plugin#177]
Hello. I use an automatic translator, so the translation may not be correct. 

1. Please tell me why adding the attribute "Required" form elements don't give any results? I think the system should warn the user about not properly filling the forms.

2. I created one "Realtion" that contains categories and the second "Dropdown", which contains groups of these categories. I made a Dropdown dependent on the Relation. When you create a new instance of the class "Dropdown" does not load the list. Only when you manually refresh the "Relation".

I would be grateful if you could help me.

**Comment by Alex360hd** [comment]
Hello,

1. The required option you put to the builder is only for showing the little red dot that show the field is required, but you have to edit the $rules variable in your model class to really make the field required. Something like that

    public $rules = [
        'title' => 'required',
        'slug' => 'required'
    ];

2. for the relation, it's the same thing, you have to write some code in your model class to configure the relation. [See here](https://octobercms.com/docs/database/relations#relationship-types)

**Comment by LukeTowers** [comment]
Thanks @Alex360hd. Does this answer your questions @coder1coder?
