### ISSUE TITLE
SQL Error when removing the plugin, 

### ISSUE THREAD

**Issue by niquedegraaff** [rainlab/builder-plugin#179]
Step  1) Install plugin
Step 2) Remove plugin

Produces this error:

`"SQLSTATE[HY000]: General error: 1 no such column: touch_move (SQL: CREATE TEMPORARY TABLE __temp__peterhegman_slickslider_slide_shows AS SELECT id, slide_show_title, slide_show_content, autoplay, accessibility, adaptive_height, autoplay_speed, arrows, prev_arrow, next_arrow, center_mode, css_ease, dots, dots_class, draggable, fade, focus_on_select, easing, edge_friction, infinite, initial_slide, lazy_load, pause_on_focus, pause_on_hover, pause_on_dots_hover, responsive, rows, slides_per_row, slides_to_show, slides_to_scroll, speed, swipe, touch_move, use_css, use_transform, vertical, vertical_swiping, rtl, wait_for_animate, z_index, center_padding FROM peterhegman_slickslider_slide_shows)" on line 664 of /home/vagrant/Code/projectnamehere/vendor/laravel/framework/src/Illuminate/Database/Connection.php`

**Comment by LukeTowers** [comment]
This is an error with the `peterhegman_slickslider` plugin
