### ISSUE TITLE
Add CSS class to Tabs

### ISSUE THREAD

**Issue by ghost** [rainlab/builder-plugin#180]
Hello,

It would be great to be able to add CSS class to primary and secondary tabs on backend form.

For example to manage padded-pane tabs, I noticed that you had to use javascript in you rainlab blog plugin in order to put some padding to tabs that does not contain the markdown widget.

To me, it's an ugly way to do and adding the possibility to put custom CSS class to tabs would be better.

What do you think about it ?

Regards,

**Comment by LukeTowers** [comment]
Currently October only supports adding css classes to the tab or secondaryTab **container** as a whole, does this still fit what you have in mind?

**Comment by Alex360hd** [comment]
Not sure, the idea is to be able to add "padded-pane" class to tabs that require some padding when you create your form with the "fancy-layout" style (same than rainlab blog with orange header) without javascript.

Not a big issue as you have tools to add some javascript to backend, but using javascript to do that is not very elegant.

**Comment by LukeTowers** [comment]
Well the way tabs currently work in October you can't really specify a per tab config item within a container as the individual tabs within a container are just generated from the fields that say they use the applicable tabs.
