### ISSUE TITLE
Slug not updating on edit

### ISSUE THREAD

**Issue by Wachem** [rainlab/builder-plugin#183]
This is probably a general 'OctoberCMS'-issue but still, when you use the preset field to generate a slug, this works perfectly on new inputs. When you edit your entry and change the source-field for the slug, the slug isn't updated...

**Comment by LukeTowers** [comment]
That's a conscious design decision, we don't want to automatically update the slug of an existing record as then the URL to that record would change without notice. If you want to be able to update a slug, then add that field to the form for the user to change manually.
