### ISSUE TITLE
Builder deletes maxItems onSave from repeater widget

### ISSUE THREAD

**Issue by datune** [rainlab/builder-plugin#186]
After manually adding maxItems to a repeater field in fields.yaml file, it's basically no longer possible to use the Builder plugin, because making any changes to it using the Builder UI deletes the maxItems entry from fields.yaml. 

In fact, this begs another question, why is maxItems configuration setting missing from the repeater widget?

**Comment by LukeTowers** [comment]
Because it was recently added to core and hasn't been added to the Builder. Feel free to make a PR to make the builder plugin support it.
