### ISSUE TITLE
"Plugin not selected"

### ISSUE THREAD

**Issue by D3m1urg0** [rainlab/builder-plugin#19]
it keeps alerting me with "plugin not selected" also if i created and repeatedly clicked over a new (created with the builder) plugin

**Comment by daftspunk** [comment]
This should have been fixed in v1.0.2?

**Comment by D3m1urg0** [comment]
i just installed the plugin by "settings" tab.. i just noticed it's only 1.0.1

**Comment by D3m1urg0** [comment]
I confirm it's fixed in 1.0.2,
the backend installs the old version, then is necessary to launch the "upgrade plugin" to get the last one..

i close the issue
