### ISSUE TITLE
I keep getting this error after upgrading to 426

### ISSUE THREAD

**Issue by ayumihamsaki** [rainlab/builder-plugin#190]
Hi,

I keep getting this error in my Stack Event Logs after updating to 426.

`getGroupStatus is deprecated. Please update getCollapseStatus instead. Class: RainLab\Builder\Widgets\ModelList`

Need some help to pin point the error and correct it huhuhu. Or maybe the plugin needs updating?

I tried re-installing builder to 1.0.21

Moved from here: https://github.com/octobercms/october/issues/3193

**Comment by LukeTowers** [comment]
See the changes from https://github.com/rainlab/pages-plugin/pull/290 and then make them as required in a PR to this repo and I'll review and merge it.

**Comment by ayumihamsaki** [comment]
@LukeTowers  I see what you are saying, the trouble is I never made a PR yet, and not sure how to do it?

Can I do this instead:

```
File Location:
https://github.com/rainlab/builder-plugin/blob/master/widgets/modellist/partials/_model-list.htm

Line 7:
data-group-status-handler="<?= $this->getEventHandler('onGroupStatusUpdate') ?>"

Changed to:
data-group-status-handler="<?= $this->getEventHandler('onSetCollapseStatus') ?>"

File Location:
https://github.com/rainlab/builder-plugin/blob/master/widgets/modellist/partials/_items.htm

Lines 12, 13, 14:
$modelGroupStatus = $this->getGroupStatus($modelGroup);
$formsGroupStatus = $this->getGroupStatus($formsGroup);
$listsGroupStatus = $this->getGroupStatus($listsGroup);

Changed to:
$modelGroupStatus = $this->getCollapseStatus($modelGroup);
$formsGroupStatus = $this->getCollapseStatus($formsGroup);
$listsGroupStatus = $this->getCollapseStatus($listsGroup);
```

Haven't tested it yet, but this is what I found that needs updating. Could you send me a link so I can learn to do a PR. Then I can help you guys out in the future.

**Comment by LukeTowers** [comment]
https://help.github.com/articles/creating-a-pull-request/

**Comment by ayumihamsaki** [comment]
@LukeTowers  Sorry for delay have been sick, just done the Pull Request for you now, thanks for the info link.

**Comment by LukeTowers** [comment]
Awesome, thanks for your work @ayumihamsaki!
