### ISSUE TITLE
Use of multiple values for displaycolumns in relations formwidget

### ISSUE THREAD

**Issue by maartenmachiels** [rainlab/builder-plugin#199]
Hi, I'm using the builder plugin to create a Booking-plugin in which there is a one-to-one relation. 
A booking `belongsTo` one `user ` (Rainlab User plugin) and `belongsTo` one `resource `(custom plugin). 

In my booking model, I have defined:

```
    /**
     * Relations
     */

    public $belongsTo = [
        'resource' => 'Chocolata\Bookingsystem\Models\Resource',
        'user' => 'Rainlab\User\Models\User'
    ];
```

With the builder plugin, I can choose which displaycolumn the relation formwidget should use. As for `resource`, I only need to show the title of the resource. As for `user`, I'd like to show **both surname and name**. As far as I can see the builder plugin **only allows me to choose one displaycolumn**, not a concatenation of multiple columns. I've been digging through the documentation but did not find a reference to multiple displaycolumns.

Do you please know a way to have my user relation formwidget display more than one displaycolumn? I'd like the admin to be able to search the list of users and find the one he's looking for. Thanks.

Really appreciate October & the builder plugin. Thank you for your continued work on this project.

**Comment by LukeTowers** [comment]
@maartenmachiels look at http://octobercms.com/docs/backend/forms#widget-relation. You can always go in and edit your fields.yaml manually. If you want to continue editing the form in the builder after editing it manually and the `select` property gets removed, then you will need to add support for the select property in the definition for the relation formwidget in this plugin. Look at recent pull requests to get an idea of what is required for that.

**Comment by maartenmachiels** [comment]
Thank you for the clarification, Luke. This works perfectly. Was looking in the wrong place.
