### ISSUE TITLE
Misspelled LICENCE.md in root, should be LICENSE.md

### ISSUE THREAD

**Issue by adrenth** [rainlab/builder-plugin#20]
A small issue, but worth mentioning right?

**Comment by daftspunk** [comment]
Pretty sure it's LICENCE, but we go in circles about this often according to the region. As far as I know:

LICENCE is the noun / LICENSE is the verb.

When you LICENSE software you give someone a LICENCE.

**Comment by dshoreman** [comment]
Correct - in *English*, License is the verb and verb only. In *American* it doubles as a noun, but they can't spell "colour" correctly either and thus can't be trusted :grin: 

![2016-02-11-214026_1920x1042_scrot](https://cloud.githubusercontent.com/assets/1521802/12991741/89a2b9d6-d108-11e5-9ed6-e9a6cba49743.png)

I'd side with the majority, but I'm biased.

**Comment by adrenth** [comment]
Agreed. We should let it rest now ;-) I really prefer color over colour... haha.
