### ISSUE TITLE
Third party column type detection

### ISSUE THREAD

**Issue by Alex360hd** [rainlab/builder-plugin#201]
Hello,

I built a plugin thanks to the builder some times ago, everything worked perfectly until I update october and builder plugin to the latest version. (build 428).

Now, when I edit my plugin and try to save the columns.yaml in the models tabs, I get the following error : 

> "strlen() expects parameter 1 to be string, array given" on line 163 of /plugins/rainlab/builder/classes/ModelListModel.php

To reproduct, you probably have to create a plugin using the builder before the laravel 5.5 update, then update october and the builder, then try to edit columns.yaml and save it (It's unnecessary to make changes, just save the just opened columns.yaml will trigger the error).

All the plugin I created thanks to the builder trigger that same error.

Best regards,

Alex

**Comment by Alex360hd** [comment]
Found the origin of the error. I have an image column that have "thumb" type provided by the [Image resizer plugin](https://octobercms.com/plugin/toughdeveloper-imageresizer)

As the "thumb" column type is not on the dropdown list of available column types, it throw an error when I try to save it.

Maybe it's too complex to "scan" for all others plugins to extend the dropdown list of available column types, so simpler fix would be to allow users to manually fill the field type. 

In term of UX, an autocomplete field would be more appropriate. You already have that kind of autocomplete fields to manage labels (it scan for translation key when you start to fill it, but you can still write whatever you want). That behavior would be perfect for the type column.

What do you think about it ?

**Comment by LukeTowers** [comment]
@Alex360hd this plugin provides methods for other plugin authors to register their custom formwidgets and column types as available for the builder plugin to use, try getting in touch with the author of the image resizer plugin for them to register their colum type.

**Comment by Alex360hd** [comment]
Ok thank you, I didn't know you can register your own column type, will see that with the image resizer author.
