### ISSUE TITLE
Permissions issue - question

### ISSUE THREAD

**Issue by KengooMurzik** [rainlab/builder-plugin#205]
Hi

I've created plugin with Builder at one instance of OctoberCMS.
Then I copied this plugin to another instance of OctoberCMS (and another project) on another PC.
And now I can't edit my plugin on the second instance with Builder. 
I set the correct author in builder's settings.  

Is there a way to resolve this problem?

Thanks in advance

**Comment by LukeTowers** [comment]
Triple check your author settings for the builder plugin and the actual author name of the plugin you are trying to modify. As well, you could just click on the filter button in the builder plugin list to see all plugins on the system.
