### ISSUE TITLE
Decimal Unsigned

### ISSUE THREAD

**Issue by Edodums** [rainlab/builder-plugin#206]
First of all thanks for this plugin.
Second of all , I don't really know if this is an issue or not but I tried to save an attribute as an decimal unsigned but it's not permitted by the builder ( "flash error : only integer type is permitted to be unsigned")
As a solution I've made it from phpmyadmin , and here comes the question : 
is a bad practice to save an attribute as a decimal unsigned ?

**Comment by LukeTowers** [comment]
See https://stackoverflow.com/a/32830394/6652884. It's unnecessary, as the column will take up the same amount of space either way.
