### ISSUE TITLE
Watermark

### ISSUE THREAD

**Issue by Edodums** [rainlab/builder-plugin#207]
Is there anyway to modify or extend the fileupload widget to make every image you upload watermarked?
Because I tried to use Invervention in FileUpload.php ( I know that's not the right way but I'm a beginner 👶 )

**Comment by LukeTowers** [comment]
Yes, extend System\Models\File in your own plugin, do the watermark processing on creation of the file, and then use your extending model as the attachment relationship model instead.

```php
public $attachOne = ['watermarked' => ['MyAuthor\MyPlugin\Models\WatermarkFile']];
```

**Comment by Edodums** [comment]
Sorry to bother you again , but I couldn't answer before , how can I access a file ( images or files ) during his creation ?
Because I can't find a way neither a function , could you please please tell me?
For now I can only create watermarked images after they are uploaded.

**Comment by LukeTowers** [comment]
```php
namespace MyAuthor\MyPlugin\Models;

class WatermarkFile extends \System\Models\File
{
    public function setDataAttribute($uploadedFile)
    {
        // Do processing on the uploaded file
        $watermarkedFileContents = $uploadedFile;
        $this->attributes['data'] = $watermarkedFileContents;
    }
}
