### ISSUE TITLE
Repeater example

### ISSUE THREAD

**Issue by daslicht** [rainlab/builder-plugin#209]
hi,
let's say we have a cooking book plugin.
now i have a table with dishes.
Each dish shoudl have a repeater which represents the cooking steps.

How do you setup the database so that iot stores the repeater items,  please? 

~ Marc

**Comment by daslicht** [comment]
Solution 👍 

https://www.youtube.com/watch?v=m9AA59IVo-I


Should be linked in docu :)

**Comment by LukeTowers** [comment]
@daslicht make a PR to octobercms/docs to improve http://octobercms.com/docs/backend/forms#widget-repeater. A link to a YouTube video won't be accepted however :)

**Comment by daslicht** [comment]
Ok fine , so I need to create a blog post regarding this topic and :-D but fisrt my cook book plugin :-D

**Comment by LukeTowers** [comment]
No external links in the October documentation please. If you could write up an example and add that to the docs that would be great!
