### ISSUE TITLE
Relations and model definition

### ISSUE THREAD

**Issue by axomat** [rainlab/builder-plugin#21]
I dont see model relations and other model attributes supported? Have I missed something? 
Is the idea that we create the model yaml files in builder and then edit the model manually for relations, validation rules, etc

Thanks for the good work again guys, it looks really nice.

**Comment by FelixINX** [comment]
In fact, I don't think that there are relation, for now.

**Comment by alekseybobkov** [comment]
Relations are not supported at the moment - they are not displayed in the autocomplete fields and cannot be generated with the Builder. Please read about limitations in the plugin documentation: http://octobercms.com/plugin/rainlab-builder

> Is the idea that we create the model yaml files in builder and then edit the model manually for relations, validation rules, etc

@axomat  - that's correct, Builder can only edit YAML files. From the documentation:

> Builder is a productivity tool, it doesn't completely replace coding by hand and doesn't include a code editor for editing PHP files (the only exception is the version management interface). Builder never overwrites or deletes plugin PHP files, so you can rest assured knowing that the code you write never gets touched by Builder. However, Builder can create new PHP files, like models and controllers.

Support for relations in the Inspector autocomplete fields is planned.

Thanks!

**Comment by FelixINX** [comment]
@alekseybobkov I have a question, how does the "Relation" field works? and

>  Builder can only edit YAML files

It can't edit PHP? Like migrations, or only it can create them.

**Comment by alekseybobkov** [comment]
> how does the "Relation" field works

Relations can be defined manually in the model class: http://octobercms.com/docs/database/relations#relationship-types. Currently Builder can't detect model relations and display them when you enter a field name in the Inspector (for example, when you're creating a new form control), but we're planning to implement this feature.

> It can't edit PHP? Like migrations, or only it can create them.

That's correct. Builder can't edit PHP files (except Migrations). It can only create new PHP files (controllers, models, etc). There are several reasons why we choose this approach. One of them is that our primary focus is the CMS platform. Developing a complex visual development tool that can safely refactor existing PHP code would move our focus away from the main goal.

**Comment by FelixINX** [comment]
Thanks for this answer. Really appreciated!

**Comment by Zmove** [comment]
+1 for relation definition throught the UI. The builder plugin is so powerful. I would like to see some options to create an easy to use relation dropdown field between several content types.

**Comment by FlusherDock1** [comment]
i've added relation to model. How i can show that on form?

**Comment by FlusherDock1** [comment]
Алексей, вижу по имени что вы славянин. Можете помочь с связями? Я новичок в OctoberCMS, и хочется углубится в него. У меня есть плагин, который выводит список поселков из бд. Мне нужно сделать вторую бд со своей моделью для участков поселка. При создании нового участка мне нужно указать связь с поселком (выбор поселка из выпадающего списка). Я добавил код в модель участков,
```
public $hasOne = [
        'poselok_name' => ['Reazzon\Obekty\Models\Post']
]; 
```
Как мне дальше действовать?

**Comment by FelixINX** [comment]
Hello @FlusherDock1 ,

If you want help you should write in english. OctoberCMS are really busy and most of the times, you can only get support from communities members, in english.

Also, your posts are not related to this issue. For what you ask, please go to the [October CMS forum](https://octobercms.com/forum), you will get help there.

Thanks

**Comment by LucasAbella29** [comment]
Hello, is there some way to make a relation between a field (made with the model builder) and other table (and model) that has a many to many relation with?

I've been reading all the comments but is not working to me to solve my problem.

My point is that i want to construct a form into the builder but some of the fields has relations with other tables and models. This causes an error when i try to use it because it says that the fields are no related with any column in the main table.

Thanks in advance!
