### ISSUE TITLE
Add ability to consolidate migrations

### ISSUE THREAD

**Issue by LukeTowers** [rainlab/builder-plugin#211]
I would like to add a "Consolidate Migrations" feature that would use https://github.com/Xethron/migrations-generator to get the current schema of plugin tables and then create one migration file per table and put them all under version 1.0.1 Initial Setup of version.yaml.

The idea of this feature would be to allow people to simplify their migrations after a period of rapid development using the builder to clean up the plugin preparing it for release. The version tracking history of migrations doesn't make sense to retain when the plugin isn't out of the scaffolding process yet. 

The order that this feature would do things would be:
1. User scaffolds out their plugin, changing their minds on the schema numerous times during the process
2. User decides that they're getting close enough to a release or sharing the code that they want to clean things up a bit and presses the "Consolidate Migrations" button
3. We scan the schema for all the tables used by the current plugin, use the library above to generate new migrations for them, and then remove the current plugin migration information from the database (run down on all existing migrations, remove plugin_version and plugin_history).
4. We drop the newly generated migrations in the updates folder, then update version.yaml to include all the migrations in one version.

Thoughts?

**Comment by danhrrn** [comment]
This feature is needed. Should there be a button per table?

**Comment by CptMeatball** [comment]
I think this also should be available for normal plugin development. Maybe make it part of the October artisan commands.

**Comment by pvullioud** [comment]
This is a good and useful idea. I used this package before to create migration from an existing table. It works well .

**Comment by faselunare** [comment]
This is a useful function, there is some news about it?

**Comment by bennothommo** [comment]
@faselunare Not as yet, unfortunately. If you would like for it to be implemented sooner rather than later, you might want to consider [offering a bounty](https://www.bountysource.com/teams/october/issues) for it to be implemented.

**Comment by mkinternet** [comment]
Maybe instead of consolidate migrations file you can add option to create one migration file from created tables or create one migration file per table and clear created migration file?

**Comment by daftspunk** [comment]
This is a good idea. I've added this idea to the internal tracker. Thanks
