### ISSUE TITLE
[PostgreSQL 10] Creating database table

### ISSUE THREAD

**Issue by TilgalisToms** [rainlab/builder-plugin#212]
When creating database on system with PostgreSQL 10.1 I get this error:

```
"An exception occurred while executing 'SELECT min_value, increment_by FROM "migrations_id_seq"':SQLSTATE[42703]: Undefined column: 7 ERROR:  column "min_value" does not exist
LINE 1: SELECT min_value, increment_by FROM "migrations_id_seq"
              ^" on line 72 of /fakepath/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php
```

As I investigated I found that this is caused by this file:
**/fakepath/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/PostgreSqlSchemaManager** method **_getPortableSequenceDefinition**
This should be something related to _pg_sequences_ which were not before version 10 I guess.
Tried to apply fix by modifying query

`$data = $this->_conn->fetchAll('SELECT min_value, increment_by FROM pg_sequences WHERE sequencename = "' . $sequenceName . '"');

and got error like this:
```
"An exception occurred while executing 'SELECT min_value, increment_by FROM pg_sequences WHERE sequencename = "migrations_id_seq"':
SQLSTATE[42703]: Undefined column: 7 ERROR:  column "migrations_id_seq" does not exist
LINE 1: ...crement_by FROM pg_sequences WHERE sequencename = "migration...
                                                             ^" on line 72 of /fakepath/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php
```

**Comment by rosscturner** [comment]
Seeing the same issue on PostgreSQL 10.2 after migrating to a new server.

**Comment by elceka** [comment]
I have same issue on fresh install of latest versions OctoberCMS and Builder plugin.
Database is based on PostgreSQL version 10.1.

```php
"An exception occurred while executing 'SELECT min_value, increment_by FROM "migrations_id_seq"': SQLSTATE[42703]: Undefined column: 7 ERROR: column "min_value" does not exist LINE 1: SELECT min_value, increment_by FROM "migrations_id_seq" ^" on line 72 of /var/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php
```

Database table with name "migrations_id_seq" doesn't exist in the database.

**Comment by elceka** [comment]
I have it. Problem is structure of "table" "public.migrations_id_seq", now have this columns:

- last_value
- log_cnt
- is_called

When i change this lines 292 and 294 on the file /doctrine/dbal/lib/Doctrine/DBAL/Schema/PostgreSqlSchemaManager.php from this

```php
$data = $this->_conn->fetchAll('SELECT min_value, increment_by FROM ' . $this->_platform->quoteIdentifier($sequenceName));

return new Sequence($sequenceName, $data[0]['increment_by'], $data[0]['min_value']);
```

to this

```php
$data = $this->_conn->fetchAll('SELECT last_value, log_cnt FROM ' . $this->_platform->quoteIdentifier($sequenceName));

return new Sequence($sequenceName, $data[0]['log_cnt'], $data[0]['last_value']);
```

then all is OK and migration of database table has been created.

As we can see, this is not a issue of Builder plugin, but is a issue of Doctrine library.

**Comment by elceka** [comment]
Library "october/rain" use version 2.5.* of library "doctrine/dbal", this issue has been fixed in version 2.6 of that library.

**Comment by unizhu** [comment]
I have the same issue with PostgreSQL 10.x.  Is this bug is waiting for the octobercms core's update?

**Comment by w20k** [comment]
@unizhu Someone should provide PR to fix this and tests. You could be the one 👍

**Comment by LukeTowers** [comment]
@w20k that would be up to @daftspunk, bring it up in #sharktank. It is EOL now

**Comment by w20k** [comment]
@unizhu @elceka @rosscturner @TilgalisToms - It's not yet possible to move on from PHP 7.0. 
We have to find another way to fix this issue on our side or ask doctrine to patch it.

PR's are welcomed 😄 Thanks!

**Comment by sebalaini** [comment]
same problem here, fresh installation of octoberCMS with postgreSQL 11.2 on macOS X and PHP 7.3.4

`"An exception occurred while executing 'SELECT min_value, increment_by FROM "migrations_id_seq"': SQLSTATE[42703]: Undefined column: 7 ERROR:  column "min_value" does not exist LINE 1: SELECT min_value, increment_by FROM "migrations_id_seq" on line 72 of /Users/username/Sites/october/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php`

**Comment by bennothommo** [comment]
We are investigating the possibility of moving to Laravel 5.9 LTS in the future, which will include (at the very least) an upgrade of `doctrine/dbal` to 2.6. Given this, we will likely focus our efforts on this upgrade as opposed to trying to fork `doctrine/dbal` and fixing this issue directly. If you are able to find a workaround that can be done directly in the Builder plugin, please feel free to submit a PR.

**Comment by pablorq** [comment]
I'm facing the same problem, using octobercms docker `build.469` (latest) with PostgreSQL. This is not fixed yet.

I'll have to back to MySQL/MariaDB to avoid this problem.

Can you please set a Reame.md file to warn about this issue? It could be good for save a lot of time!

**Comment by LukeTowers** [comment]
@pablorq just upgrade to October v1.1, that's the latest supported version and it should resolve the issue.

**Comment by pablorq** [comment]
@LukeTowers how can I upgrade to October v1.1?

I'm using it with a docker container (aspendigital/octobercms:build.469). Is there a new docker container with October v1.1?

**Comment by LukeTowers** [comment]
@pablorq doesn't look like that docker image supports 1.1 yet. I've emailed the author of it to check in on the status, but in the meantime you'll have to use something else.

**Comment by bennothommo** [comment]
@pablorq @LukeTowers I noticed that @daftspunk has been working on a Docker image for October CMS as well - https://github.com/daftspunk/docker-october. You could potentially use that - you would just need to update the Dockerfile to use the Composer install as opposed to the October CMS API install.

**Comment by pablorq** [comment]
@bennothommo thank you for the info! It seems a good solution.

Right now I've to go on with the development, so I'll switching back to MariaDB. When it be advanced enough I'll be switching again to PostgreSQL and test this option.
