### ISSUE TITLE
Feature Request - Ability to Filter Record List

### ISSUE THREAD

**Issue by danhrrn** [rainlab/builder-plugin#213]
I feel like this plugin is missing a key component: record list filtering. Two properties would have to be created:
1. Filter value  - a URL parameter like :category that defines what records to search for.
2. Filter column - the column that you are filtering by.

This feature would let users, for example, create their own custom blog systems and product catalogues based on categories.

### id, name, group
1, Whippet, hound
2, Beagle, hound
3, Spaniel, gundog
4, Labrador, gundog
5, Retriever, gundog

### Component
_/dogs/:group_
Filter value = :group
Filter column = group

### Output
_/dogs/hound_
#### would display...
1, Whippet, hound
2, Beagle, hound

Could that feature possibly be added?

If it's not possible to add this, what is the easiest way it could be implemented into a plugin?

**Comment by LukeTowers** [comment]
This will be handled in #214. We'll leave it open until the change is merged.
