### ISSUE TITLE
Suggestion: auto suggest label keys

### ISSUE THREAD

**Issue by rabol** [rainlab/builder-plugin#219]
Hi

When creating labels or placeholders it would be super cool if the Builder could suggest a label key

e.g when create a label for a field in a form something like this:
myplugin.mymodel.form.label.<field>
and for the placeholser
myplugin.mymodel.form.placeholder.<field>
and for lists
myplugin.mymodel.list.label.<field>

**Comment by daftspunk** [comment]
Added this to the internal tracker for the next iteration of builder.

Thanks!
