### ISSUE TITLE
Permissions issue -- typo and none registered

### ISSUE THREAD

**Issue by JediSange** [rainlab/builder-plugin#22]
Two issues I found so far.  Firstly there appears to be a typo in `plugins/rainlab/builder/controllers/Index.php` on line 37.  The following line of code:

`public $requiredPermissions = ['rainlab.buileder.*'];`

Appears to have a typo.  However, I'm not sure if that counts as a bug since I don't see any backend permissions.  The `registerPermissions` function in Plugin.php is empty.  Is this intentional or a bug?

**Comment by FelixINX** [comment]
Solved in #23.

This is an error.

**Comment by JediSange** [comment]
Understood.  Thanks for the update on this.  What permissions should we use to control access to the Builder plugin?

**Comment by FelixINX** [comment]
As I seen, there is no permission. I think the permission is given by
default.


Félix Desjardins

2016-02-11 18:37 GMT-05:00 Austin DeVinney <notifications@github.com>:

**Comment by alekseybobkov** [comment]
The permission is implemented now. The name is fixed. Thanks!
