### ISSUE TITLE
Not possible to select custom type

### ISSUE THREAD

**Issue by rabol** [rainlab/builder-plugin#220]
It is not possible to select a 'Custom column type', even if the type is registered using the registerListColumnTypes() in the plugin class

**Comment by LukeTowers** [comment]
We'd have to hook into the form event for modifying the options defined here https://github.com/rainlab/builder-plugin/blob/b12cb8e6a6ab3a2294a1d6a4d78675e0ca3971db/classes/modellistmodel/fields.yaml#L48-L58 or switch to our own option defining method to dynamically get the column types defined by registerListColumnTypes

**Comment by blackxel** [comment]
I added this in the boot method of my plugin


```php
 Event::listen('system.extendConfigFile', function ($publicFile, $config) {
            if ($publicFile !== '/plugins/rainlab/builder/classes/modellistmodel/fields.yaml') {
                return $config;
            }
            $typeOptions = $config['tabs']['fields']['columns']['columns']['type']['options'];
            $plugins = \System\Classes\PluginManager::instance()->getRegistrationMethodValues('registerListColumnTypes');
            foreach ($plugins as $pluginName => $availableTypes) {
                foreach (array_keys($availableTypes) as $custom) {
                    $typeOptions[$custom] = $pluginName . '::' . $custom;
                }
            }
            $config['tabs']['fields']['columns']['columns']['type']['options'] = $typeOptions;
            return $config;
        });

```

**Comment by LukeTowers** [comment]
Ah yes, @blackxel I'd forgotten about that. October always blows my mind with how extensible it is.

**Comment by daftspunk** [comment]
This is fixed as part of https://github.com/rainlab/builder-plugin/pull/372
