### ISSUE TITLE
Unknown database type bit requested

### ISSUE THREAD

**Issue by bfloren** [rainlab/builder-plugin#221]
Expected behavior

Create new table via Builder

Actual behavior

table not created.

"Unknown database type bit requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it." on line 423 of /Users/brett/Code/Project11/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php

Reproduce steps

![sg](https://user-images.githubusercontent.com/2178782/36616263-0b25682a-18db-11e8-895d-18d84510c363.png)

October build

4.3.3 using mysql 5.7.21

I am just looking for the recommended method to address this problem. I am not sure why I am getting a bit issue with mysql 5.7.21 -- I read about another similar issue with october dealing with json type but I can not find anything about bit type.

**Comment by LukeTowers** [comment]
The issue is because Doctrine does not create mappings for platform specific types and `bit` cannot be cleanly converted to a boolean or binary without the potential for data loss. See https://github.com/doctrine/dbal/issues/1775. 

Where and what are you using the bit column type in your DB schema?

**Comment by bfloren** [comment]
For a temporary fix I mapped  "bit" =>  "boolean" and just to get it to work.  I literally had just installed builder, created a Plugin and was adding my first table. I could not get it to create a table even when there was nothing more than an id field of type integer.  While typing a response to you here I started to think "why?  why is it complaining about a bit field when there is not one in the table at all?  and then it clicked. I had created a table manually for storing results of a cron job that collects data from an API and stores it in a table that is used in a partial.  Because there was an unrelated table in the database that contained a bit field (only time I used a bit field by the way)  it was causing the error.  I went and changed the bit to tinyint and then removed the mapping I had added (bit=>boolean) and then the error was gone.  So the problem is solved and I wanted to share my findings with you and maybe it will help others in the future.

**Comment by LukeTowers** [comment]
Thanks very much for your follow up post @bfloren! The builder plugin scans the database's schema using Doctrine and Doctrine just barfs hardcore when it comes across types that it doesn't recognize.

Do you have any thoughts on how we could make this a better experience for the developers that encounter the issue?
