### ISSUE TITLE
Question about how to access data from different model class

### ISSUE THREAD

**Issue by Hessel91** [rainlab/builder-plugin#222]
Hello sir, 

On my webpage, I use the record list from builder component to display model class "Item"
However, inside that component I would like to use an image from another model class called "Category"
I watched a tutorial but I can't get it done. 
Can you please tell me what is wrong with my code?
I would be very thankful If you would help me with this issue.

    {% set records = builderList.records %}
    {% set displayColumn = builderList.displayColumn %}
    {% set noRecordsMessage = builderList.noRecordsMessage %}
    {% set detailsPage = builderList.detailsPage %}
    {% set detailsKeyColumn = builderList.detailsKeyColumn %}
    {% set detailsUrlParameter = builderList.detailsUrlParameter %}
    
    {% for record in records %}
           
    {% for Category in record.category %}  
        <img src="storage/app/media{{ record.mediafinder2 }}" alt=" ">
    {% endfor %}
    
    
    {% endfor %}

![how to access another modelclass](https://user-images.githubusercontent.com/7326568/38053666-09bafe82-32d5-11e8-9917-96cd16c490ab.jpg)

My models:
![models](https://user-images.githubusercontent.com/7326568/38054464-5a29db84-32d7-11e8-84ba-dec38c2c33f1.jpg)

my database:
![database](https://user-images.githubusercontent.com/7326568/38054472-6174caf2-32d7-11e8-95c8-58a98c193521.jpg)

**Comment by LukeTowers** [comment]
Your field name in the screenshot is `mediafinder1`, in your code it is `mediafinder2`. One of these is wrong.

**Comment by Hessel91** [comment]
Hi Luke, thanks for your fast reply, I changed it into 1 however it is still not working.  I would like to know what is wrong with my code to access data from that other modelClass.

**Comment by LukeTowers** [comment]
@Hessel91 what is your schema? Where on your table is the mediafinder actually supposed to store its data?

**Comment by Hessel91** [comment]
the schema is correct however I think this is wrong
    
    {% for Category in record.category %}  
    {   % endfor %}

because when I try to access data from category.title it isn't working either. 
Do you know if these parameters are correct?

**Comment by LukeTowers** [comment]
@Hessel91 I'd have to see your model file and the schema for your records table and your categories table

**Comment by Hessel91** [comment]
My English is not so good I'm sorry so I don't know another way than show you: 
https://github.com/Hessel91/Behandelingen

**Comment by LukeTowers** [comment]
`category` is a singular relationship (`belongsTo`) - https://github.com/Hessel91/Behandelingen/blob/master/models/Item.php#L26

What your code is currently doing is like saying `for number in 1`; it doesn't make sense. Just access the category properties directly:
```
{% for record in records %}
     <img src="{{ record.category.mediafinder1 }}">
{% endfor %]
```
