### ISSUE TITLE
Programatically get results of a component

### ISSUE THREAD

**Issue by Alex360hd** [rainlab/builder-plugin#225]
Hello,

I'm trying to create an universal "pagination" component that would handle pagination of records displayed thanks to the builderList component provided by this plugin.

My component have an option where I fill the alias name of the component I want to paginate. It works well when I don't use any ajax.

Now I want to be able to paginate my results using ajax. I already have my small javascript that request an "onPaginate" function that is in my component, it's triggered, no problems at all.

Here is my code in "onPaginate" function : 

    public function onPaginate() {
        // Get the alias name of the component you want to paginate
        $component = $this->property('component');
        // Apply this component to a debug variable
        $this->page['debug'] = $this->page[$component];
    }

In my default.htm file I try : 

    {{ d('debug', debug) }}

The strange thing here is that the "records" attribute of my component is empty after ajax refresh. I would like to find a way to retrieve my records in order to apply a different pagination (to inherit all component configuration) instead of building the whole request again.

Do you see a solution to this ?

Thanks

**Comment by bennothommo** [comment]
Hi @Alex360hd, I presume that you have been able to arrive at a solution as part of your PR here: https://github.com/rainlab/builder-plugin/pull/228 so I'm going to close this question.

If you still need an answer to this, feel free to post it in the same PR and we can discuss :)
