### ISSUE TITLE
Add some useful features to builderList component (code included)

### ISSUE THREAD

**Issue by ghost** [rainlab/builder-plugin#226]
Hello,

I worked on RecordList component in order to add some small feature I need for every projects. It add 2 new features : 

- Ajax pagination out of the box
- Contextual links on records (inspired from Drupal : 
to quickly access to create / update / delete url of records from the frontend)

(I added that options in the "New settings" group in order to see them all in one place).

For the moment, I quickly created another plugin that extend RecordList in order to discuss about that features. I could create a PR if you think it could be commited.

There are still some things I want to improve but my Laravel / October Skill block me actually : 

- Remove contextualUrl settings : It could be deducted automatically depending on the model we chose to list, but I don't know how to load the corresponding controller and get access to the backend url.

- Add a "delete" contextual actions : Records have a backend url to create / update the record. But as the deletion is made by checking checkbox on backend list page, there is no real delete page to link for single record deletion. I would like to find a solution to that.

Don't hesitate to give me feedback !

[backend.zip](https://github.com/rainlab/builder-plugin/files/1912171/backend.zip)

**Comment by LukeTowers** [comment]
I could see the usefulness of ajax pagination but the other stuff is a bit out of scope for this component.

**Comment by Alex360hd** [comment]
Ok I understand, would you accept a PR for the ajax pagination ?

**Comment by LukeTowers** [comment]
Sure, keep it as simple as possible and avoid making backwards incompatible changes though ;) Thanks!

**Comment by Alex360hd** [comment]
Hello,

I will try, but I also want to add support of append and prepend for ajax pagination, so I need to put records and pagination in separate partials.
 
- default.htm (to handle ajax wrappers for records and pagination)
- records.htm (to list records)
- pagination.htm (to list pagination)

I will consider ajax pagination as disabled by default for backward compatibility.

**Comment by LukeTowers** [comment]
Perfect, sounds good to me @Alex360hd.

**Comment by Alex360hd** [comment]
PR just added ^^

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
