### ISSUE TITLE
Relation with values

### ISSUE THREAD

**Issue by ZuggieTM** [rainlab/builder-plugin#231]
I have 3 databases named: Recipes, Ingrediants, Recipes_Ingrediants. The idea is to have a Recipe with a name and a description. The Ingrediants will hold the ingrediants name and price. Recipes_Ingrediants have a relation with Recipe_id and Ingrediant_id, plus Quanity.

In builder I have 2 controllers in my plugin, one to add Ingrediants and one to add Recipes. The issue I have with the builder is, that I don't quite know how to make the relation between the Ingrediants and Recipe tables, so that when I Create a new Recipe in the plugin, I can add Ingrediants and quantity as well.

Is this even doable or will I have to make a lot of custom stuff?

**Comment by LukeTowers** [comment]
The builder plugin is just for scaffolding and doesn't have many tools available for working with relationships. You'll want to read https://octobercms.com/docs/database/relations and https://octobercms.com/docs/backend/relations for more information on working with relationships in October.
