### ISSUE TITLE
How to remove "Reorder records" button

### ISSUE THREAD

**Issue by wertykid** [rainlab/builder-plugin#232]
Hello,
As the title suggests, I would like to remove the reorder records button. Can anyone help me with this please? Thank you.

**Comment by Konfuze** [comment]
You can remove the button in `<october_root>/plugins/<your_namespace>/<plugin_name>/<controller_name>/controllers/menu/_list_toolbar.htm`.

String you need to delete looks like
`<a href="<?= Backend::url('namespace/plugin/controller/reorder') ?>" class="btn btn-default oc-icon-list"><?= e(trans('backend::lang.reorder.default_title')) ?></a>`
