### ISSUE TITLE
Add Blueprint Class to builder updates files

### ISSUE THREAD

**Issue by ayumihamsaki** [rainlab/builder-plugin#234]
Hi, I did a quick check and this doesn't seem to be in a past issue, I am thinking maybe it would be a good idea to add Blueprint Class to builder updates files.

## What is the Blueprint class in Laravel?

Blueprint is the instance that used to define the new table or may use to add columns to the table.

Its use case is specifically in Laravel Migrations.

The following example shows some simple lines of code as to how a Blueprint object is utilized in the closure of the Schema facade.

```
Schema::create('users', function (Blueprint $table) {
    $table->increments('id');
});
```

Fore More understanding of the Migrations in Laravel, you can check on Laravel’s official documentation (Database: [Migrations](https://laravel.com/docs/5.6/migrations)).

## Old Code (Current):

```
<?php 

namespace Demo\Example\Updates;

use October\Rain\Database\Updates\Migration;
use Schema;

class CreateDemoExampleTable extends Migration

{
    public function up()
    {
        Schema::create('demo_example_table', function($table)
        {
			// ..		
        });
    }

    public function down()
    {
        Schema::dropIfExists('demo_example_table');
    }

}
```

## New Code (Proposed Idea):

```
<?php

declare(strict_types=1);

namespace Demo\Example\Updates;

use October\Rain\Database\Schema\Blueprint;
use October\Rain\Database\Updates\Migration;
use Schema;

class CreateDemoExampleTable extends Migration

{
    public function up()
    {
        Schema::create('demo_example_table', function (Blueprint $table)
        {
			// ..		
        });
    }

    public function down()
    {

        Schema::dropIfExists('demo_example_table');
    }

}
```

Also see the issue: [233](https://github.com/rainlab/builder-plugin/issues/233) with regards to adding PHP7 declare strict_types discussion.

**Comment by LukeTowers** [comment]
@ayumihamsaki what would be the benefit to adding the Blueprint class type hinting in?

**Comment by LukeTowers** [comment]
@ayumihamsaki no answer? 😉
