### ISSUE TITLE
New functionality: build-min.js

### ISSUE THREAD

**Issue by Chofoteddy** [rainlab/builder-plugin#235]
Hi!

I want to add new function in Js that allow to users add columns (like `addTimeStampColumns`), with focus to data integrity. But I can't found documentation of how I can generate the file `builder-plugin/assets/js/build-min.js ` to prove the functionality before a pull-request.

I made changes in: `builder.index.entity.databasetable.js`.

Can you help me please?

**Comment by LukeTowers** [comment]
@Chofoteddy added the ability to do the compilation in https://github.com/rainlab/builder-plugin/commit/0347411936a01b85f7bcc46c97570cd1603c9097. Just run `php artisan october:util compile assets` in your project root now.
