### ISSUE TITLE
Pull data from SQL database to display in checkboxlist in backend

### ISSUE THREAD

**Issue by wertykid** [rainlab/builder-plugin#237]
Hello,

I would like to ask how do I pull data from SQL database to populate checkbox options using checkboxlist in backend? 

I am currently following this code from this link:

http://octobercms.com/docs/backend/forms#field-dropdown
```php
public function getStatusTypeOptions($value, $formData)
{
    return ['all' => 'All', ...];
}
```
Any help would be gladly appreciated, thank you!

**Comment by LukeTowers** [comment]
@wertykid are you using Models or are you wanting to directly query the DB with raw SQL?

**Comment by wertykid** [comment]
Hi Luke, I’m using Models

**Comment by LukeTowers** [comment]
@wertykid then just use queries on the models and return it as an array. You'll need to understand how eloquent model queries work and how arrays work in PHP.

Below is a basic and clunky example for reference:
```php
public function getSurveyIdOptions() {
    $survey_ids = [];
    $surveys = SurveyModel::all();
    foreach ($surveys as $survey) {
        $survey_ids[$survey->id] = $survey->name;
    }

    return $survey_ids;
}
```

**Comment by wertykid** [comment]
Thanks for the help Luke!
