### ISSUE TITLE
Allow to select mode for FileUploader form widget

### ISSUE THREAD

**Issue by angay9** [rainlab/builder-plugin#238]
Hi there, thanks for a great plugin.

It would be nice if in the builder plugin inside the Models -> Forms -> fields.yaml file where we define all form widgets we could select the mode for the file uploader widget just like in the media finder widget.

Thanks again :)

**Comment by LukeTowers** [comment]
@angay9 you should already be able to??? https://github.com/rainlab/builder-plugin/blob/master/classes/StandardControlsRegistry.php#L742-L753
