### ISSUE TITLE
I get this error message when I open Builder Plugin

### ISSUE THREAD

**Issue by ayumihamsaki** [rainlab/builder-plugin#239]
See screenshot:

![sss](https://user-images.githubusercontent.com/17784082/42727361-189c29ae-879d-11e8-84a8-53d60eeeff93.png)

Maybe it's something I did wrong somewhere...? What does this error mean please.

**Comment by LukeTowers** [comment]
It means that the plugin was unable to detect the namespace from the model source file. You probably have a typo somewhere.

**Comment by ayumihamsaki** [comment]
@LukeTowers Thanks for your advice! A+++
