### ISSUE TITLE
Database original fields missing on save after updating

### ISSUE THREAD

**Issue by firemankurt** [rainlab/builder-plugin#24]
I created a table in bulider with these steps:
1 - named table "kurtjensen_profile_changes"
2 - added "user_id" (integer) and "change" (text) fields.
3 - saved - migration file looked correct except I wanted timestamps
4 - opened an existing table in builder to see what it had for timestamp fields
5 - opened my  "kurtjensen_profile_changes" table again
6 - added "id", "created_at" and "updated_at" fields
7 - saved - migration file only showed id and timestamps ( not original 2 fields ) 
See: https://drive.google.com/file/d/0BwJLIChm8ILtSHI0VC1WbnpyV1E/view?usp=sharing

**Comment by alekseybobkov** [comment]
Migrations are incremental. The second migration added 2 new fields. Can take a look at the table structure in another MySQL tool and confirm that now your table has all columns, including the timestamp fields?

**Comment by firemankurt** [comment]
Nevermind... I see that it created an update file and was not editing the create migration file.
It would be nice to have builder ask before running migration.  
Then I could continue editing the create_table file until I was ready to actually create the table.  
This would reduce the number of versions.

**Comment by alekseybobkov** [comment]
Just to clarify - it's possible to update existing migrations without creating a new version. Migrations are listed on the Migrations tab. You can rollback a migration and update its code (add new columns, etc), and apply again. Then a new version won't be needed.
