### ISSUE TITLE
Question: HTML5 datalist in builder?

### ISSUE THREAD

**Issue by ayumihamsaki** [rainlab/builder-plugin#240]
Hi,

Does the builder plugin have an option in its Model section to create a HTML5 <[datalist](https://html.spec.whatwg.org/multipage/form-elements.html#the-datalist-element)> field?

Let's say I want to create the following text field:

```
  <label for="default">Pick a programming language</label>
  <input type="text" id="default" list="languages" placeholder="e.g. JavaScript">
  
  <datalist id="languages">
    <option value="HTML">
    <option value="CSS">
    <option value="JavaScript">
    <option value="Java">
    <option value="Ruby">
    <option value="PHP">
    <option value="Go">
    <option value="Erlang">
    <option value="Python">
    <option value="C">
    <option value="C#">
    <option value="C++">
  </datalist>
```

Is there a way to do this is the builder plugin or is it better to create a custom FormWidget?

Sorry to ask question and not file an issue (just trying to learn lots of things in October right now).

**Comment by ayumihamsaki** [comment]
Going to close this - I built a formwidget instead.

**Comment by LukeTowers** [comment]
@ayumihamsaki you would create a custom formwidget for that and then you could register it to make it available to the builder plugin.
