### ISSUE TITLE
"Default from" on textfield doesn't work i.c.w. dropdown field

### ISSUE THREAD

**Issue by Syourt** [rainlab/builder-plugin#242]
I wan't to create the following layout:

- **Switch field** - Determines whether to show dropdown or manual input
- **Dropdown** - Updates (hidden) manual input field on change
- **Manual input field** - Can be filled out manually if switch field is set to manual, else it will be updated with the value selected in the dropdown.

Now when I select a value in the dropdown field, the manual input field won't be updated.

The settings in the **manual input** field are as follows:

- **Advanced > Default from**: dropdown_field
- **Advanced > Depends on**: [dropdown_field]

Am I doing something wrong, is it just not possible or have I found a bug?

**Comment by LukeTowers** [comment]
Do both of those work separately?

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
