### ISSUE TITLE
Builder Record list error

### ISSUE THREAD

**Issue by ezersky** [rainlab/builder-plugin#243]
I have a strange error - when using the Builder Record list I get a 500 error. Here is a screenshot http://joxi.ru/krD19DRiE16gwm?d=1

From errors-log: 64 limiting connections by zone "lfcgi"

**Comment by LukeTowers** [comment]
Not enough information to go on, please post your full error log.

**Comment by ezersky** [comment]
It was a problem on my server
Nginx parameter «limit_conn lfcgi» was too small
