### ISSUE TITLE
declare construct is not supported in language files

### ISSUE THREAD

**Issue by iotch** [rainlab/builder-plugin#248]
The `declare(strict_types=1)` in plugin language file makes language file invalid and rises `ApplicationException` at https://github.com/rainlab/builder-plugin/blob/master/classes/LocalizationModel.php#L52

The validation fails here: https://github.com/rainlab/builder-plugin/blob/master/classes/LocalizationModel.php#L387

I believe that should be fixed since `declare(strict_types=1)` is may be added automatically by IDEs/fixers/ etc.

**Comment by LukeTowers** [comment]
Make a PR to fix it if you'd like @iotch

**Comment by iotch** [comment]
Sorry, but I'm too new to OctoberCMS to know about all future issues my edits may cause.

**Comment by LukeTowers** [comment]
@iotch that's what I'm for ;) If you make a PR I'll review it before it gets merged to prevent any future issues :)

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
