### ISSUE TITLE
Add option to create Seeder Files

### ISSUE THREAD

**Issue by ayumihamsaki** [rainlab/builder-plugin#252]
Just an idea, why not let builder also create Database Seeder Files?

~would save us all time having to create them out manually.

**Comment by LukeTowers** [comment]
@ayumihamsaki sure, feel free to add support in a PR ;)

**Comment by ayumihamsaki** [comment]
I be honest and say I'm not sure if I got enough time to create this one. So if anyone else wants to create a PR for it please feel free. If not I will try in a few weeks time...

**Comment by ayumihamsaki** [comment]
I be honest and say I'm not sure if I got enough time to create this one. Got so much work going on right now! If anyone wants to create a PR for it, please go ahead.

**Comment by LukeTowers** [comment]
@ayumihamsaki I'm sure I don't have enough time :) I'll leave this open for now but if there isn't any other activity on it in a month I'll have to close it as abandoned.

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
