### ISSUE TITLE
Major layout break

### ISSUE THREAD

**Issue by LarBearrr** [rainlab/builder-plugin#253]
Just yesterday I did a fresh install of October and added the Builder plugin for a demonstration I am putting together at work. Everything was working perfectly.

Fast forward to today and the layout for the Builder plugin is completely broken.... and I cannot figure out why.

![image](https://user-images.githubusercontent.com/28734844/46561999-c38e6d00-c8bf-11e8-99e8-e12706678bc3.png)

Just out of curiousity, I logged into another site that uses Builder and it seems to be fine. Also, for fun, I tried on Internet Explorer and the layout is fine (minus the fact that the dropdowns for column types don't work).

**Comment by LukeTowers** [comment]
Do you have any console errors? Are you able to see what CSS rule is causing that on your browser vs IE?

**Comment by ikmespinozaIT** [comment]
Same issue I encountered yesterday. It was a fresh installation of the builder plugin.
I see no console errors though.
https://imgur.com/a/zkdGZMX

**Comment by ikmespinozaIT** [comment]
I think either of these two modifications I made that triggers the issue. Coz, for now, I didn't follow these steps, and the builder is working fine.
![image](https://user-images.githubusercontent.com/3295011/46729636-fd33ef00-cc96-11e8-822c-21fc693f1d1d.png)

**Comment by LukeTowers** [comment]
Hmm, must be something in the develop branch that's causing this. I don't really have time to look into what it is exactly though

**Comment by LarBearrr** [comment]
@tfprado You may want to look at your composer.json and move away from the `dev-develop` branches. I can't remember exactly what caused this problem, but I do remember it had to do with the comment @ikmespinozaIT made:

> @LarBearrr @LukeTowers I think either of these two modifications triggers the issue.
> 
> ![image](https://user-images.githubusercontent.com/3295011/46729636-fd33ef00-cc96-11e8-822c-21fc693f1d1d.png)
> 
> By not following the above configurations, I was able to fetched some css updates.
> Then, I installed builder plugin, and is working fine now.

**Comment by w20k** [comment]
@tfprado, @LarBearrr,@ikmespinozaIT,
It was fixed in the dev branch. It's waiting for an upcoming release 444 [(merge).](https://github.com/octobercms/october/commit/99bfae4ed076541434bf938f8ec7861505655710)

I remeber, manually change: `max-width: 100%` ->  'width:100%' for layout class.
Screenshot:
![screenshot 2018-12-14 at 13 06 25](https://user-images.githubusercontent.com/1053320/50000076-1ad84a00-ffa1-11e8-8d8a-c8a22583fe24.png)

**Comment by bennothommo** [comment]
Closing this issue as build 444 of October CMS is out. If this issue still persists in newer October CMS versions, please feel free to re-open this issue.
