### ISSUE TITLE
Add staticpagepicker into form widget

### ISSUE THREAD

**Issue by claudchan** [rainlab/builder-plugin#258]
Hi,
Please add staticpagepicker into form widget. Example screenshot below:
![builder-staticpagepicker-widget](https://user-images.githubusercontent.com/1639056/47953057-e3927880-dfb2-11e8-8b90-ba916d91f030.png)

**Comment by LukeTowers** [comment]
Submit a PR to implement this. As a note, it will have to be implemented in a way that only takes effect when the RainLab.Pages plugin is installed and active, so probably through events. See https://github.com/rainlab/builder-plugin/commit/b5a3277f66f801a28b6b2bc33fefb61fc7863674 for an example of everywhere that has to be modified to add it as a control.

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
