### ISSUE TITLE
Add Page Picker into form widget

### ISSUE THREAD

**Issue by claudchan** [rainlab/builder-plugin#259]
Hi,
Please implement page picker into form widget. This is very useful for client easily pick that page to display my custom form plugin using builder. Please consider.
![page-picker-from-widget](https://user-images.githubusercontent.com/1639056/47958739-30ef0400-e00c-11e8-8921-27e62c8a6afb.png)

**Comment by LukeTowers** [comment]
@claudchan see https://github.com/rainlab/builder-plugin/issues/258#issuecomment-435602432. Duplicate of #258.
