### ISSUE TITLE
Settings displayed to users without permission to access the builder

### ISSUE THREAD

**Issue by jfoliveira** [rainlab/builder-plugin#26]
Regular backend users (users that are not administrators and who do not have the permission 
`Builder -> Create and edit plugins` checked) are seeing the `Set your plugins namespace and author name` setting. See below:

<img width="994" alt="screen shot 2016-02-13 at 12 01 31 pm" src="https://cloud.githubusercontent.com/assets/1943318/13028017/a05e8d8e-d249-11e5-92c6-ff769b0fd9f0.png">

Is there any permission that controls the visibility of this setting?

It's not a major issue as this plugin would probably not be installed in production but I am curious if this is useful for a regular user in any ways.

**Comment by arekan127** [comment]
I think it's not a major issue, but it's really not useful tool for my clients:) So i hope guys will fix that, but for now: 
```public function registerSettings()```
```    {```
       ```]]] return [```
           ``` 'config' => [```
                ```'label'       => 'Builder',```
               ``` 'icon'        => 'icon-wrench',```
                ```'description' => 'Set your plugins namespace and author name.',```
               ``` 'class'       => 'RainLab\Builder\Models\Settings',```
              ```  'permissions' => ['rainlab.builder.manage_plugins'],```
               ``` 'order'       => 60```
          ```  ]```
   ```     ];```
 ```   }```

that will do the trick, but you can register new permission specifically for this setting.

**Comment by alekseybobkov** [comment]
This was fixed in the version 1.0.7. Thanks.
