### ISSUE TITLE
I get text 'NULL' on default input

### ISSUE THREAD

**Issue by megalogi** [rainlab/builder-plugin#266]
Hello,

I don't understand why i get text 'NULL' on input default, (see image below) 

Hello.

<img width="897" alt="capture d ecran 2018-12-22 a 17 28 13" src="https://user-images.githubusercontent.com/9659469/50376599-eef33f00-0606-11e9-91fb-095b4a124e26.png">

**Comment by megalogi** [comment]
@LukeTowers, can you please help me on this issue ?

**Comment by LukeTowers** [comment]
@megalogi it just means that the column is going to have a default value of null because you have ticked the `nullable` checkbox. NULL means no value
