### ISSUE TITLE
validator resolver code breaks other validator resolvers

### ISSUE THREAD

**Issue by alpapan** [rainlab/builder-plugin#267]
Hello

It seems that the following code found in Plugin.php

 ```
 // Register reserved keyword validation

Validator::resolver(function ($translator, $data, $rules, $messages, $customAttributes) {
            return new ReservedValidator($translator, $data, $rules, $messages, $customAttributes);
 });
```

breaks all attempts to implement our own validators in a new plugin.

**What did I expect**
When I build a new plugin, I needed new validations. I implemented them using a class. That a new validation rule would work as expected

**What did I get**
My validation rules were not found (Method validateXyz not found). Even very simple validations taken out of the documentation.
After 4 hours of digging I discovered that if I comment out the above code in the Builder plugin then new validations work ok.

No idea why that is, just reporting it.

**Comment by w20k** [comment]
@alpapan, what validations are you talking about?
You can't name your plugin using restricted words, that's why this validator is in place: https://github.com/rainlab/builder-plugin/blob/910715d2603326404940f63584775c6c5fa3b4ed/validation/ReservedValidator.php#L12.

**Comment by LukeTowers** [comment]
@bennothommo Could you look into this?

@w20k he's talking about issues with registering his own custom validator resolver rules, not with issues with that specific rule

**Comment by LukeTowers** [comment]
@bennothommo might have to switch to this method of adding a custom rule: https://github.com/luketowers/oc-pwnedpasswords-plugin/blob/master/Plugin.php#L38

**Comment by bennothommo** [comment]
@LukeTowers not a problem, I'll have a look in the next day or so.

I got the suggested Validator implementation from this doc page:
https://octobercms.com/docs/services/validation#custom-validation-rules
I might try see how this *should* be implemented and suggest some edits there if it seems to be having this sort of effect on other plugins.

**Comment by bennothommo** [comment]
@alpapan would you mind providing an example of how you are setting up your validation rule in your custom plugin? Is it part of the `boot` process?

**Comment by alpapan** [comment]
Hello!

First I created a new class at validation/BioValidator.php

```
<?php namespace alpapan\biobench\Validation;

use Illuminate\Validation\Validator;

class BioValidator extends Validator
{

    public function validateFileExists($attribute, $value, $parameters)
    {
        return file_exists($value) ? true : false;
    }

 }
```

Then this went to my Models/Software.php where the validator will apply at the top
```
use Validator;
use alpapan\biobench\Validation\BioValidator;
```
I registered the class at storage\framework\classes.php (but I'm not sure if I had to...)
```
  'alpapan\\biobench\\Validation\\BioValidator' => 'plugins/alpapan/biobench/validation/BioValidator.php',

```

and this one inside the Model extension:

```
public $rules = [
      'path_to' => 'file_exists'
    ];
```

Finally, this one went to Plugin.php on the boot function
```
       Validator::resolver(function ($translator, $data, $rules, $messages, $customAttributes) {
           return new BioValidator($translator, $data, $rules, $messages, $customAttributes);
       });
```

If I delete the Builder validator from builder plugin.php then and only then does my validator work. If however I delete the builder validator from the builder plugin.php and then re-add it to **my** plugin.php (above the Validator::resolver of my validator), then both validators work fine... go figure.

```
// from builder plugin
      Validator::resolver(function ($translator, $data, $rules, $messages, $customAttributes) {
            return new ReservedValidator($translator, $data, $rules, $messages, $customAttributes);
        });
       Validator::resolver(function ($translator, $data, $rules, $messages, $customAttributes) {
           return new BioValidator($translator, $data, $rules, $messages, $customAttributes);
       });

```

**Comment by bennothommo** [comment]
@alpapan I've replicated your issue. It appears that Laravel's Validator factory only accepts one resolver, so whichever resolver is accepted first is the one that runs, and the custom rule that you added to your model usually throws an error as the resolver is never run. The way that @LukeTowers has included a custom rule in his Pwned Passwords plugin seems to be the best implementation.

I'll submit a bug fix for the Builder plugin. It may be worth looking into using Rule objects as per https://github.com/octobercms/library/pull/365, as it seems to be Laravel's suggested way of allowing "local" custom rules.

**Comment by LukeTowers** [comment]
@bennothommo perfect, thanks. Could you submit a PR to the docs repo providing the recommended way of registering custom validation rules and explaining the caveats of the resolver method?

**Comment by alpapan** [comment]
Thanks!
FWIW, I failed to get it to work by following the library#365 issue (see below) or Luke's plugin approach... so a doc would be great...

![image](https://user-images.githubusercontent.com/608484/50533391-a7c3fb80-0b7c-11e9-94f5-02cc3afc5bfc.png)

**Comment by alpapan** [comment]
If implementing octobercms/library#365 turns out you need this in the Rule class (from https://github.com/mpociot/laravel-apidoc-generator/issues/247#issuecomment-353553829).

```
public function __toString()
{
  return 'Name of Rule';
}
```

**Comment by bennothommo** [comment]
@LukeTowers done, PR for docs is here: https://github.com/octobercms/docs/pull/346

@alpapan You would only need the `__toString()` method if you are using the API generation command as per the linked issue. I don't believe it is needed for validation.

**Comment by alpapan** [comment]
sadly i had to add the __toString to the Rule class otherwise I get the error I pasted https://github.com/rainlab/builder-plugin/issues/267#issuecomment-450464217.

I struggled also creating a message replacer. it seems the current approach only works for class validator not for rule (and Luke's approach of registering to Plugin.php is also based on the validator class rather than rule). My horse for a manual..!

**Comment by bennothommo** [comment]
@alpapan I've added some additional details and an example about the replacer to my docs PR linked above. If you need further help with this, it may be worth looking at the Laravel docs as well: https://laravel.com/docs/5.5/validation#using-rule-objects.

**Comment by alpapan** [comment]
Thanks
To help others viewing issue:
One has two options: creating a Rule class or a Validator class. The former is simpler (and what I've done so far).

However, my understanding that you need to create a Validator class if you want replace placeholders in validation messages. With a Rule class, you can define messages but it won't allow a replacer function for placeholders.

If this is right, I'll just close the ticket?

**Comment by iboved** [comment]
I have the same problem. My custom validation rules don't work if the RainLab.Builder plugin is installed. I am using the latest version of the RainLab.Builder plugin - 1.0.23.

**Comment by LukeTowers** [comment]
@iboved if you're using composer switch to `dev-master` instead. Otherwise make a PR to bump the version.yaml file to create a new release.
