### ISSUE TITLE
[Feature Request] Option to add timestamps to database tables

### ISSUE THREAD

**Issue by DanielHitchen** [rainlab/builder-plugin#27]
Checkbox option perhaps to add the "created_at" and "updated_at" timestamp fields to any database tables.

Can add them manually with a default of "0000-00-00 00:00:00" but a little checkbox that added in `$table->timestamps();` to the `up()` function would be a nice touch.

Fantastic job by the way guys with this plugin!!

**Comment by daftspunk** [comment]
`->softDeletes()` is a relative of `->timestamps()`, another table wide setting, which could be bundled in with this too.

**Comment by ametad** [comment]
Yes that would be nice! :+1:

**Comment by seanthepottingshed** [comment]
Sexytime!

**Comment by artras** [comment]
+1

**Comment by Asinox** [comment]
+1

**Comment by wilirius** [comment]
+1

**Comment by alekseybobkov** [comment]
`created_at`, `updated_at` and `deleted_at` columns can now be added with new toolbar buttons on the database table management tab. The New Model popup now has checkboxes for enabling timestamps and Soft Deleting for new models. It's not possible to create new columns right from the New Model popup as it creates complex use cases (the database table editor can be open in another tab and have unsaved changes).

**Comment by Chofoteddy** [comment]
This feature is great.

I want to add complementary button "User integrity" or maybe "Data integrity", the purpose is add two fields to the table database: `created_by` and `updated_by`.

And complementary to soft delete: `deleted_by`.

But I have a question (issue #235), I would like to have your help.
