### ISSUE TITLE
Using dynamic scope method in Record list component

### ISSUE THREAD

**Issue by VadimIzmalkov** [rainlab/builder-plugin#270]
I defined dynamic scope method but could not find it in component dropdown, there are only methods from model class

Seems to me it not possible https://github.com/rainlab/builder-plugin/blob/master/components/RecordList.php#L209

**Comment by LukeTowers** [comment]
@VadimIzmalkov you mean with `addDynamicMethod()`?

**Comment by LukeTowers** [comment]
We would need to add a method to ExtendableTrait (https://github.com/octobercms/library/blob/master/src/Extension/ExtendableTrait.php) `getClassMethods` with logic similar to the existing `methodExists` method; and then use that newly added method here. @w20k @bennothommo @daftspunk any interest in the above?

**Comment by bennothommo** [comment]
@LukeTowers sure thing, I'll implement it.

**Comment by bennothommo** [comment]
@VadimIzmalkov Could you give an example of your dynamic scope method and `addDynamicMethod()` call so I can test?

**Comment by VadimIzmalkov** [comment]
@bennothommo I need scope in [Reviews](https://octobercms.com/plugin/vojtasvoboda-reviews) plugin. For storing "HTTP_REFERER" I added additional column to Review database schema and created scope method for this column. I guess that is not simplest way to test.

```
protected function extendReviewModel()
{
    ReviewModel::extend(function($model) {
        $model->addDynamicMethod('scopeReferer', function($query, $value) {
            return $query->where('referer', $value)
                ->orderBy('created_at', 'ASC');
        });
    });
}
```

**Comment by bennothommo** [comment]
PR now submitted: https://github.com/rainlab/builder-plugin/pull/273
