### ISSUE TITLE
[Question] The plugin breaks custom validation messages for other plugins

### ISSUE THREAD

**Issue by GinoPane** [rainlab/builder-plugin#271]
I noticed that my custom validation messages are being skipped and October uses its own default messages instead.

I set up validation messages by simply providing `$customMessages` array in my model:

```
    /**
     * Validation messages
     *
     * @var array
     */
    public $customMessages = [
        'name.required' => Plugin::LOCALIZATION_KEY . 'form.tags.name_required',
        'name.unique'   => Plugin::LOCALIZATION_KEY . 'form.tags.name_unique',
        'name.regex'    => Plugin::LOCALIZATION_KEY . 'form.tags.name_invalid',
        'name.min'      => Plugin::LOCALIZATION_KEY . 'form.tags.name_too_short',
    ];
```

I tracked down the issue and here's the problem:

![image](https://user-images.githubusercontent.com/3897579/51600219-6a435b80-1ef9-11e9-963e-df36d6df8094.png)

All custom messages are being overwritten by this:

![image](https://user-images.githubusercontent.com/3897579/51600526-1d13b980-1efa-11e9-9b8b-32af82267857.png)

I see that there's a PR https://github.com/rainlab/builder-plugin/pull/265 addressing the same issue. 

@LukeTowers is it going to be released soon?

**Comment by LukeTowers** [comment]
@GinoPane make a PR to bump the version in version.yaml file, that'll trigger the marketplace to release the new version. Or, you can load it via composer instead.
