### ISSUE TITLE
Partial field type does not have a 'Label' option

### ISSUE THREAD

**Issue by paishin** [rainlab/builder-plugin#272]
Label option is missing from the 'Partial' field type options.
Adding it manually by editing the fields.yaml file works fine but 'label' attribute gets removed next time you save from Builder's interface.

**Comment by LukeTowers** [comment]
See https://github.com/rainlab/builder-plugin/blob/master/classes/StandardControlsRegistry.php#L333

**Comment by bennothommo** [comment]
@paishin Partials generally don't have labels, as they are used mainly for miscellaneous content. You can see this standard in the docs: https://octobercms.com/docs/backend/forms#field-partial

**Comment by LukeTowers** [comment]
@bennothommo It's reasonable for partials to have labels, after all they do support them. I know I've used partials with labels before, specifically for scoreboard type fields.

**Comment by paishin** [comment]
I also use labels with partials, for example when the partial contains an
input field, but I have to manually add the label tag directly to yaml file
since october's interface does not have it (but does work). Whats really
annoying is that when I make changes to the form october removes the
manually entered label. So I either have to go and add them again through
yaml or not use the builders interface.

**Comment by LukeTowers** [comment]
@paishin just remove https://github.com/rainlab/builder-plugin/blob/master/classes/StandardControlsRegistry.php#L354, test and submit a PR when you can confirm that it's working and we can merge it.

**Comment by paishin** [comment]
I have tried performing the above change, the issue is that label is a "required" attribute in builder. So when I remove it from ignored properties then all partials that do not have a label display a "Please specify the control label" error.

To make this work label needs to be optional for the 'partial' widget.


![image](https://user-images.githubusercontent.com/410381/63889317-6f194200-c9e9-11e9-979e-a2a6c41e7111.png)

**Comment by LukeTowers** [comment]
@bennothommo what do you think about removing the required validation rule for the label? https://github.com/rainlab/builder-plugin/blob/master/classes/ControlLibrary.php#L118 Technically speaking none of the fields (except for section perhaps) need a label specified, they all work without one. I often will put fields with no labels as the only occupant of tabs using the tab's label to be the label for the field.

**Comment by bennothommo** [comment]
@LukeTowers agreed - it shouldn't be required. Apparently the section fields label is optional too according to the docs - https://octobercms.com/docs/backend/forms#field-section.

**Comment by LukeTowers** [comment]
Huh, I wonder what that looks like. @paishin feel free to make the label not required anymore as well and make a single PR for both changes

**Comment by bennothommo** [comment]
@LukeTowers @paishin One thing to note - the label is used for identifying the field in the form designer in the Builder plugin. If it is removed, there's no way of indicating which field is which in the form designer.

**Comment by LukeTowers** [comment]
@bennothommo we could make it so that it also shows the name of the field in the form designer

**Comment by daftspunk** [comment]
Fixed in the next version (v1.1.1).

Thanks
