### ISSUE TITLE
Pages issue

### ISSUE THREAD

**Issue by Ladylain** [rainlab/builder-plugin#275]
Hi ,

- OctoberCMS Build: 446
- PHP Version: 7.2.2
- Database Engine: MySQL
- Plugins Installed: Rainlab.Builder, Rainlab.Users, JBonnyDev.UserPermissions

### Description:
I've created multiple CMS page with `:page` parameter on `model ID` identifier. 
All my pages have the same navigation menu (done mannually).

When i'm on a page like `http://www.example.com/list/3` and I click on a link that redirect to another page like `http://www.example.com/antoherlist/:page`, if my link has been created into the cms Page like this : 
` {{ 'anotherlist' | page }}`, it automatically adds `/3` to the link. 

To fix this, i have to change the link creation into my cms page link like this : ` {{ 'anotherlist' | page({ page : '' ]) }}`  to redirect to default url.

I don't know if it's an issue with builder component list or with october cms page

Does someone already notice this issue ? 

Best,

**Comment by Eoler** [comment]
That's how CMS pages work - by passing forward current URL params with the same name.

> To fix this, i have to change the link creation into my cms page

You can reset link parameters universally by passing: `|page(false)` into Twig filter.

**Comment by Ladylain** [comment]
Thanks for your answer @Eoler but would it be more user friendly to make that if you put `| page` it is like `|page(false) ` ?

**Comment by Eoler** [comment]
> wouldn't it be more user friendly to make that if we put `| page` is like `|page(false) ` ?

Think about what would that mean for backward compatibility...

**Comment by bennothommo** [comment]
@Ladylain The `page` Twig filter persists URL parameters across pages if they are not explicitly changed in the filter. See: https://octobercms.com/docs/markup/filter-page#persistent-parameters

If you want to suggest a change with it, it's best that you fill out an issue or PR for [October CMS core](https://github.com/octobercms/october), as the `page` filter is specified there.
