### ISSUE TITLE
Why code field is readOnly (MigrationModel)?

### ISSUE THREAD

**Issue by Air-Petr** [rainlab/builder-plugin#279]
I wonder why does `code` field in migration popup have `readOnly: true` property? Are there any reasons? It would be nice to edit code before creating migration file.

https://github.com/rainlab/builder-plugin/blob/008f3e8b4cfe357f0ebf5efb0e86f1de179c942d/classes/migrationmodel/fields.yaml#L11

**Comment by bennothommo** [comment]
@Air-Petr Since the migration is run immediately once the migration popup is closed, it may be risky to allow edits here in case the migration cannot complete.

If you want to make manual changes to the migration, it's best to do this in the **Versions** section of the Builder plugin, where errors are more thoroughly checked and you have the capability of committing and rolling back migrations.

**Comment by Air-Petr** [comment]
Yes, I know about *Versions* section. But it feels unusual a bit when migrations are applied instantly. Also, quite often I have to do a rollback right after migration file was created. So is there a way to eliminate this unnecessary step?

I see two scenarios:

1. Create a checkbox **Also apply** in the Migration popup and change name of the blue button to **Save**. So the migrations will be applied only if checkbox is checked.
2. Create a second button called **Save** (that saves files, but don't apply them).

First one seems to be more concise. I could make some changes in code and make pull request after that.

**Comment by bennothommo** [comment]
@Air-Petr I'd be happy to accept a PR that allows you to edit the migration in the popup, only if it can: a) handle if the migration is incorrect or cannot be run by showing an error and rolling back any changes made and, b) can reflect the migration's changes immediately in the database table schema editor when the popup closes.

**Comment by bennothommo** [comment]
This feature is now available as of https://github.com/rainlab/builder-plugin/commit/1f94ebe8237a481170c832ac8d1d7016650315f1.
