### ISSUE TITLE
Permissions not being registered

### ISSUE THREAD

**Issue by jfoliveira** [rainlab/builder-plugin#28]
Hi, I've just created my first plugin with Builder. Thanks for this amazing plugin!

My plugin permissions are not being registered on user permissions settings page.
If I comment the generated `Plugin.php` `registerPermissions()` method everything works fine and the permissions are registered:

```php
<?php namespace My\Plugin;

use System\Classes\PluginBase;

class Plugin extends PluginBase
{
    public function registerComponents()
    {
    }

    // by uncommenting this method permissions are not registered
    // public function registerPermissions()
    // {
    // }

    public function registerSettings()
    {
    }
}
```

Am I doing something wrong?

**Comment by alekseybobkov** [comment]
I just fixed it. The plugin class should not contain the `registerPermissions()` method. If the method doesn't exist, the system loads permissions from the plugin.yaml file.

Please update your copy of the Builder.

**Comment by jfoliveira** [comment]
Great! Thanks!
