### ISSUE TITLE
Add format as a supported property for the DatePicker widget

### ISSUE THREAD

**Issue by host138** [rainlab/builder-plugin#287]
Hello, i have a problem.
When i write `format: d.m.Y` in the fields.yaml and then use builder plugin, it rewrites fields.yaml file, but at the same time the builder doesn't have format field.
How to use it corect without rewriting?
Thank's.

**Comment by LukeTowers** [comment]
You would have to add `format` as an available property to the date picker widget in the StandardControlsRegistry here: https://github.com/rainlab/builder-plugin/blob/master/classes/StandardControlsRegistry.php#L638. Feel free to make a PR to do that.

**Comment by bennothommo** [comment]
Fixed by #288.
