### ISSUE TITLE
created_at fields are constantly updated

### ISSUE THREAD

**Issue by faselunare** [rainlab/builder-plugin#289]
Hi, i have a custom plugin and i have just discovered that the field created_at is updated together with the updated_at field (but with two hours difference), the created_at field obviously does not have to be updated.

By default in the database the configuration is: Default CURRENT_TIMESTAMP
how can i solve? 
Thanks

**Comment by bennothommo** [comment]
@faselunare Was this plugin specifically built by the Builder plugin?

**Comment by faselunare** [comment]
Yes @bennothommo 
i used the plugin builder

**Comment by faselunare** [comment]
this is the model
`<?php namespace B33\Conference\Models;

use Model;

/**
 * Model
 */
class Post extends Model
{
    use \October\Rain\Database\Traits\Validation;
    use \October\Rain\Database\Traits\SoftDelete;

    protected $dates = ['deleted_at'];
    protected $jsonable = ['urls'];
    protected $sluggable = ['title'];
    public $implement = ['RainLab.Translate.Behaviors.TranslatableModel'];
    public $translatable = ['title', ['slug', 'index' => true], 'teaser', 'body', 'tags', 'urls', 'video', 'file', 'slideshow_text', 'subheader', 'image'];
    
    public $timestamps = true;

    /**
     * @var string The database table used by the model.
     */
    public $table = 'b33_conference_posts';

    /**
     * @var array Validation rules
     */
    public $rules = [
    ];
    
    public function getExhibitorsOptions(){
        return Exhibitor::where('event_id', '=', $this->event_id)->lists('title', 'id');        
    }
    
    public function getPartnersOptions(){
        return Partner::where('event_id', '=', $this->event_id)->lists('title', 'id');        
    }
    
    public function getSessionsOptions(){
        return Session::where('event_id', '=', $this->event_id)->lists('title', 'id');        
    }
    
    public function getSponsorsOptions(){
        return Sponsor::where('event_id', '=', $this->event_id)->lists('title', 'id');        
    }
    
    public function getGuestsOptions(){
        return Guest::where('event_id', '=', $this->event_id)->lists('name', 'id');        
    }
    
    public function getSpeakersOptions(){
        return Speaker::where('event_id', '=', $this->event_id)->lists('name', 'id');        
    }
    
    public function getSpacesOptions(){
        return ExhibitionSpace::all()->lists('name', 'id');        
    }
    
    public $belongsTo = [
        'category' => 'B33\Conference\Models\PostCategory',
        'event' => 'B33\Conference\Models\Event',
        'author' => 'RainLab\User\Models\User'
    ];

    public $belongsToMany = [
        'exhibitors' => ['B33\Conference\Models\Exhibitor', 'table' => 'b33_conference_post_exhibitors', 'order' => 'title asc', 'conditions' => 'is_active = 1'],
        'partners' => ['B33\Conference\Models\Partner', 'table' => 'b33_conference_post_partners', 'order' => 'title asc', 'conditions' => 'is_active = 1'],
        'sessions' => ['B33\Conference\Models\Session', 'table' => 'b33_conference_post_sessions', 'order' => 'title asc', 'conditions' => 'is_active = 1'],
        'sponsors' => ['B33\Conference\Models\Sponsor', 'table' => 'b33_conference_post_sponsors', 'order' => 'title asc', 'conditions' => 'is_active = 1'],
        'tags' => ['B33\Conference\Models\Tag', 'table' => 'b33_conference_post_tags', 'order' => 'title asc'],
        'guests' => ['B33\Conference\Models\Guest', 'table' => 'b33_conference_post_guests', 'order' => 'name asc', 'conditions' => 'is_active = 1'],
        'speakers' => ['B33\Conference\Models\Speaker', 'table' => 'b33_conference_post_speakers', 'order' => 'name asc', 'conditions' => 'is_active = 1'],
        'spaces' => ['B33\Conference\Models\ExhibitionSpace', 'table' => 'b33_conference_post_spaces', 'order' => 'title asc', 'conditions' => 'is_active = 1']
    ];
    
    public $attachMany = [
        'photos' => 'System\Models\File',
        'photos_count' => ['System\Models\File', 'count' => true],
        'files' => 'System\Models\File',
    ];
    
    public $attachOne = [
        'image' => ['System\Models\File', 'public' => true],
        'slideshow_image' => ['System\Models\File', 'public' => true]
    ];
    
     /**
     * Translate url parameters when the user switches the active locale.
     *
     * @param $params
     * @param $oldLocale
     * @param $newLocale
     *
     * @return mixed
     */
    public static function translateParams($params, $oldLocale, $newLocale)
    {   
        $newParams = $params;
        foreach ($params as $paramName => $paramValue) {
            if ($paramName !== 'slug') {
                continue;
            }
            $records = self::transWhere($paramName, $paramValue, $oldLocale)->first();
            if ($records) {
                $records->translateContext($newLocale);
                $newParams[$paramName] = $records->$paramName;
            }
        }
        return $newParams;
    }
}`

**Comment by LukeTowers** [comment]
@faselunare can you show us your table migration script?

**Comment by faselunare** [comment]
```
<?php namespace B33\Conference\Updates;

use Schema;
use October\Rain\Database\Updates\Migration;

class B33ConferencePosts extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('b33_conference_posts', function($table)
        {
            $table->engine = 'InnoDB';
            $table->increments('id');
            $table->timestamp('created_at');
            $table->timestamp('updated_at');
            $table->timestamp('deleted_at')->nullable();
            $table->string('title')->nullable();
            $table->string('slug')->index();
            $table->text('teaser')->nullable();
            $table->text('body')->nullable();
            $table->string('video')->nullable();
            $table->integer('is_promoted')->nullable();
            $table->text('slideshow_text')->nullable();
            $table->text('subheader')->nullable();
            $table->text('urls')->nullable();
            $table->integer('category_id')->nullable();
            $table->integer('event_id')->nullable();
            $table->integer('author_id')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('b33_conference_posts');
    }
}
```

**Comment by faselunare** [comment]
![Schermata 2019-07-13 alle 18 07 48](https://user-images.githubusercontent.com/39338657/61173856-350af280-a599-11e9-9489-9b74a210419d.png)

**Comment by LukeTowers** [comment]
@faselunare all your timestamps have to be marked as nullable.

**Comment by faselunare** [comment]
<img width="694" alt="Schermata 2019-07-13 alle 19 39 40" src="https://user-images.githubusercontent.com/39338657/61174826-03e4ef00-a5a6-11e9-83a1-f1780a425c83.png">
i get this error when i try to update the table with the builder ..

**Comment by faselunare** [comment]
<img width="667" alt="Schermata 2019-07-13 alle 19 41 57" src="https://user-images.githubusercontent.com/39338657/61174851-4c9ca800-a5a6-11e9-8a4a-5b50be9257f8.png">

**Comment by bennothommo** [comment]
@faselunare Which database software are you using? If it's MySQL, `timestamp` should be a valid column type.

**Comment by faselunare** [comment]
yes mysql
there is other way to change this fields without breaking the plugin?

**Comment by faselunare** [comment]
Just found this 
https://github.com/laravel/framework/issues/16526

**Comment by faselunare** [comment]
I have modified the fields by hand wit phphpmyadmin and I have just found that the in the 'attribute' there is an 'on update current timestamp' option selected...  how can I fix with the builder?

**Comment by bennothommo** [comment]
@faselunare Thanks for that link - it definitely sheds some light on this. I must admit, I wasn't aware that `timestamp` is a field type only supported by certain databases.

You cannot edit attributes like that one in the Builder, as the Builder table designer is supposed to be a simplified editor for table schema. I would suggest removing it through PHPMyAdmin, or making a raw SQL query in one of your migrations to remove it.

**Comment by faselunare** [comment]
Thanks!
I will change it by hand for now.
do you have any idea how the field was set to 'on update current timestamp'?

**Comment by faselunare** [comment]
ok, I think is a bug because in my plugin every created_at field is set to 'on update current timestamp'
and update_at not...

**Comment by bennothommo** [comment]
@faselunare I'm not entirely sure how the field defaulted to use "current_timestamp" on update - as a guess, it's possible it's a default with MySQL itself with the `timestamp` field. I generally use `datetime` fields as they are more widely supported and I believe most October functions use the same.

**Comment by faselunare** [comment]
@bennothommo thanks for the suggestion but the timestamp is added by the builder when in the model you use the 'add timestamp' and 'add soft delete'.

**Comment by bennothommo** [comment]
@faselunare I believe `timestamp` in the migrations files, and Doctrine itself, is converted to a `datetime` field in the database anyway - it seems to be the case for many of the plugins I've done through the Builder plugin.

Besides this, there is no way that I'm aware of that allows you to add the "current_timestamp" flag through the migrations or through the Builder plugin (besides doing a raw SQL query), so I believe this is due to a configuration or default value in your MySQL server settings.
