### ISSUE TITLE
Any setting to add breadcrumb to controller views?

### ISSUE THREAD

**Issue by jfoliveira** [rainlab/builder-plugin#29]
When a controller is generated by the builder the breadcrumb generator block is not included on the generated view files `create | preview | update`.

The code block I am mentioning is:

```php
<?php Block::put('breadcrumb') ?>
    <ul>
        <li><a href="<?= Backend::url('my/plugin/dummies') ?>">Dummies</a></li>
        <li><?= e($this->pageTitle) ?></li>
    </ul>
<?php Block::endPut() ?>
```

This block is included in the views when a controller is generated by command line:
```
php artisan make:controller my.plugin Dummies
```

Are there any settings to include the breadcrumb block on the generated views?

**Comment by daftspunk** [comment]
Fixed by #36

**Comment by Hambern** [comment]
Is there a chance to get the word "Dummies" on the row `<li><a href="<?= Backend::url('my/plugin/dummies') ?>">Dummies</a></li>`translatable?

**Comment by daftspunk** [comment]
@Hambern take a look at the documentation for more info on how to translate values: http://octobercms.com/docs/plugin/localization

If you pass the locale key to the "name" field, it will be translated.
