### ISSUE TITLE
end of line issue in database update (migration) files

### ISSUE THREAD

**Issue by orcu** [rainlab/builder-plugin#292]
The builder plugin seems to be creating files with CRLF file endings, while my editor and OS uses LF endings and all other files in my project has LF endings. The file endings messes up with git repository and causes convenience (https://stackoverflow.com/questions/25597104/git-pull-error-your-local-changes-to-the-following-files-would-be-overwritten-b#comment67807650_25597104)

**Comment by bennothommo** [comment]
@orcu As per [this line](https://github.com/rainlab/builder-plugin/blob/master/classes/TableMigrationCodeGenerator.php#L23), the Migration generator uses the default line break of the operating system to ensure compatibility. If you are running a Windows server, it will use CRLF line endings.

You will either need to change your hosting environment to use LF line endings. Alternatively, you can provide a PR to the plugin to make this configurable.
