### ISSUE TITLE
Error message upon successfully deleting table through Builder GUI

### ISSUE THREAD

**Issue by anthonymccourt** [rainlab/builder-plugin#294]
When deleting a table through the Builder GUI, October throws a message that it can't find the table after it successfully deletes it. 

Details - 
When deleting a table the window for 'Save and Apply / Cancel' is overridden by this error message after pressing 'Save and Apply'. After dismissing the error message, the original 'Save and Apply / Cancel' window remains. However, pressing 'Cancel' at this point merely dismisses the window because the table has already been successfully dropped. You must also now refresh the page to see the table disappear.

![drop_table_error](https://user-images.githubusercontent.com/4533726/63108123-1031e280-bf7e-11e9-82af-02b0ec52e83a.png)

**Comment by bennothommo** [comment]
This has been fixed as of https://github.com/rainlab/builder-plugin/commit/1f8c5abb30f4f00d4b06dd88751c02577815dc9f and has been released with v1.0.26 of the Builder plugin.
