### ISSUE TITLE
Undefined index: primary_key (FIXED)

### ISSUE THREAD

**Issue by marcelboere** [rainlab/builder-plugin#297]
When your database form contains too many characters a dialog pops up on save saying: Undefined index: primary_key. This is a very confusing Error message. From the php logs it becomes clear this is due to the fact that php variable max_input_vars has been set too low. You should increase the value in php.ini. 
It would be convenient if the plugin checks max_input_vars against the number of vars in the form and leaves a useful error message instead, for example: Unable to commit form, increase the value for max_input_vars in your php configuration.

**Comment by bennothommo** [comment]
@marcelboere If you feel there is a good way to warn users in the circumstance that the `max_input_vars` PHP setting is too low, please feel free to submit a PR of your proposed change.

**Comment by daftspunk** [comment]
This is a common problem throughout and we've solved it by switching to JSON serialization.

Added this to the internal tracker so it can be addressed in the next design of builder.

Thanks
