### ISSUE TITLE
Menu item requiring permissions not registered - Server URL prepended to permission key

### ISSUE THREAD

**Issue by jfoliveira** [rainlab/builder-plugin#30]
I generated a plugin with a single menu item that requires permission to be accessed.
The required permissions has been granted to users groups but the menu is not being registered.

There seems to be an issue on `modules/system/classes/PluginBase.php` that prepends the server URL not only to the controller URL but also to the `permissions` array elements.

```php
public function registerNavigation()
{
    ...
    if (is_array($navigation)) {
        array_walk_recursive($navigation, function(&$item, $key){
            if ($key == 'url') {
                // $item = Backend::url($item); //: bug: prepends URL to permissions' items
                return Backend::url($item); // works: only prepends URL to 'url' key
            }
        });
    }
    return $navigation;
    }
}
```

Other possible solution would be to not pass the `item` parameter of the closure by reference and keep the inner code as it is:
```php
public function registerNavigation()
{
    ...
    if (is_array($navigation)) {
        // array_walk_recursive($navigation, function(&$item, $key){ // by reference, bug
        array_walk_recursive($navigation, function($item, $key){ // by value, works
            if ($key == 'url') {
                $item = Backend::url($item);
            }
        });
    }
    return $navigation;
    }
}
```

I am not sure if this is the right place to fix this issue thus I'd better not sending a pull request myself. 
Hope this helps on reproducing and fixing this issue.

**Comment by alekseybobkov** [comment]
Thanks. This will be fixed in the next build. 

Commit: https://github.com/octobercms/october/commit/d58b6d4d51d85a10c5a6c47fa1a151bb1d915273
