### ISSUE TITLE
Provide documentation on how to register a custom widget with the Builder plugin

### ISSUE THREAD

**Issue by multiwebinc** [rainlab/builder-plugin#303]
See https://github.com/octobercms/october/issues/3666 for reference.

It doesn't appear that the plugin description is on Github. I'm guessing you need to manually update it on the plugins repository on the October website. 

How is this for a start?

Adding a custom widget
-

To add a custom widget to the Builder plugin, you must first [register a backend form widget](https://octobercms.com/docs/backend/widgets#form-widget-registration) for your plugin. 

Once it is registered, define a list of properties within your plugin in the Plugin registration class `boot()` method and register the custom control. For example:

```php
public function boot() {
    $properties = [
        'max_value' => [
            'title' => 'The maximum allowed',
            'type' => 'builderLocalization',
            'validation' => [
                'required' => [
                    'message' => 'Maxium value is required'
                ]
            ]
        ],
         'mode' => [
            'title' => 'The plugin mode',
            'type' => 'dropdown',
                'options' => [
                    'single' => 'Single',
                    'multiple' => 'Multiple',
                ],
            'ignoreIfEmpty' => true,
        ]
    ];

    Event::listen('pages.builder.registerControls', function($controlLibrary) {
        $controlLibrary->registerControl(
            'yourwidgetname',
            'My Widget',
            'Widget description',
            ControlLibrary::GROUP_WIDGETS,
            'icon-file-image-o',
            $controlLibrary->getStandardProperties([], $properties),
            'Acme\Blog\Classes\ControlDesignTimeProvider'
        );
    });
}
```

> Note: See the `getStandardProperties()` method in the `rainlab/builder/classes/ControlLibrary.php` file for more examples.

Now, we need the `ControlDesignTimeProvider` class referenced above. Save the following as `class/ControlDesignTimeProvider.php` within your plugin's directory (replacing `'yourwidgetname'` with what you used in your Plugin registration class `boot()` method).

```php
<?php namespace Acme\Blog\Classes;
use RainLab\Builder\Widgets\DefaultControlDesignTimeProvider;

class ControlDesignTimeProvider extends DefaultControlDesignTimeProvider {
    public function __construct(){
        $this->defaultControlsTypes[] = 'yourwidgetname';
    }
}
```

Then save the following as `class/controldesigntimeprovider/_control-yourwidgetname.htm` within your plugin's directory, and customize it how you like. Again, `yourwidgetname` in the file name must match:

```html
<div class="builder-blueprint-control-text">
    <?= e(trans('acme.blog::lang.mywidget.placeholder')) ?>
</div>
```

You should now be able to add and configure your custom widget within the Builder plugin just like any other plugin.

**Comment by LukeTowers** [comment]
@multiwebinc added it to the plugin documentation section on the marketplace, thanks!

**Comment by multiwebinc** [comment]
@LukeTowers Double check it. It got HTML encoded.

**Comment by LukeTowers** [comment]
@multiwebinc that's a known bug with the marketplace, it's super irritating but I can't do anything about it.

**Comment by multiwebinc** [comment]
@LukeTowers Wow. That's just terrible... You'd think the fix for something like that would be relatively trivial.

**Comment by LukeTowers** [comment]
You'd think, but I don't have access to the marketplace code base. Only @daftspunk and @alekseybobkov have access.

**Comment by joshuadesierto** [comment]
after adding the custom control in the frontend i get an error  `"Class 'Solas\Researchresources\Classes\ControlDesignTimeProvider' not found" on line 141 of /var/www/html/myoctober/solas/plugins/rainlab/builder/formwidgets/FormBuilder.php`
i just did whats in the documentation but i guess i probably miss something or maybe a file path miss placement. I saved the "ControlDesignTimeProvider" file inside class/ of my custom plugin folder

this is the code inside ControlDesignTimeProvider:
```
<?php namespace Solas\Researchresources\Classes;
use RainLab\Builder\Widgets\DefaultControlDesignTimeProvider;

class ControlDesignTimeProvider extends DefaultControlDesignTimeProvider {
    public function __construct(){
        $this->defaultControlsTypes[] = 'Categories';
        $this->defaultControlsTypes[] = 'Tags';
    }
}
```
need help fixing this, scanning it through my codes and the document many times all over again.

**Comment by daftspunk** [comment]
Everything looks fine here @joshuadesierto. The error suggests it cannot find your class that should be located in

plugins/solas/researchresources/classes/ControlDesignTimeProvider.php

Double check the file path

**Comment by joshuadesierto** [comment]
@daftspunk thanks. i fixed it already. it's the documents typo from the builder plugin saying saving it to 'class/ControlDesignTimeProvider.php' instead of 'classes/ControlDesignTimeProvider.php'.

**Comment by daftspunk** [comment]
@joshuadesierto Thanks, I've fixed the docs
