### ISSUE TITLE
Error on creating new plugin or setup default name and namespace

### ISSUE THREAD

**Issue by semasping** [rainlab/builder-plugin#305]
"Undefined offset: 1" on line 2619 .../vendor/laravel/framework/src/Illuminate/Validation/Validator.php

Builder v1.0.26

OctoberCMS v1.0.459

**Comment by LukeTowers** [comment]
@semasping what was the issue?

**Comment by semasping** [comment]
The outdated version of octoberCMS due to php version 5.6 in the console.
