### ISSUE TITLE
[Feature Request] When using the File Upload widget

### ISSUE THREAD

**Issue by DanielHitchen** [rainlab/builder-plugin#31]
Hi guys,

When adding a File Upload widget to a model could we have an option (maybe a dropdown) to make it "attachOne" or "attachMany" which would also add the relevant code to the model file like:
```
public $attachOne = [
    'field_name' => ['System\Models\File']
];
```
and (maybe with a sort order option too?)
```
public $attachMany = [
    'field_name' => ['System\Models\File', 'order' => 'sort_order']
];
```
Cheers

**Comment by alekseybobkov** [comment]
Hi Daniel. Builder doesn't edit or delete PHP files, it's one of the design concepts. Please read the [plugin documentation](http://octobercms.com/plugin/rainlab-builder) and discussion in the issue #21

**Comment by DanielHitchen** [comment]
Hi @alekseybobkov, again I think you misunderstand me, I don't mean to delete any files, but when you create your modal in builder, a modal PHP file is created for you & should be edited/added to with the relevant code for that form element when you choose different form fields, shouldn't it?

As my example above, when you select a file upload widget for your form, if you then go to your backend plugin page & try to create a new item, you will get an error because the $attachOne or $attachMany does not exist in your modal file unless you manually put it in.

**Comment by DanielHitchen** [comment]
Ah have just seen the relation note in the docs - has that always been there ;)

**Comment by DanielHitchen** [comment]
I've checked the docs where it states: 

![builder plugin october cms](https://cloud.githubusercontent.com/assets/7501909/13072241/118bc6c8-d490-11e5-9100-af5aa33f8479.jpeg)

I just think that for anyone who's not familiar with building modals/plugins from scratch, which is who I thought the builder plugin might be aimed at to a certain degree - how would they know to add the relation to the modal class manually, or what a relation looked like, or where to add it etc?

I get what you're saying regarding the concept of the builder plugin, I guess I'm just trying to come at it from an none developer point of view ( i.e new to Laravel/October ), whereby if I added a form widget I'd not know what code to add to the modal etc, or that I even needed to add any code in the first place - I'd just be greeted with an error when I tried to create something with my plugin like the following:

![exception](https://cloud.githubusercontent.com/assets/7501909/13072611/38d45040-d492-11e5-8313-11c617fa3f01.jpeg)

It's absolutely fine though if manually adding certain relations & other code elements is required as I know how to do that. Again, apologies if I have misunderstood the concept of the builder plugin, I'm not trying to cause any issues, just trying to help :)
