### ISSUE TITLE
Invalid length value of Big Integer in ID column when using MySQL

### ISSUE THREAD

**Issue by tsyvs** [rainlab/builder-plugin#311]
Builder shows Big Integer length 10 instead of real 20 (Builder UI)

![Screenshot from 2019-11-12 13-02-19](https://user-images.githubusercontent.com/4626977/68666554-cc368580-054c-11ea-8147-effe331399f4.png)

But real MySQL data structure is generated as desired (PhpMyAdmin)

![Screenshot from 2019-11-12 13-09-43](https://user-images.githubusercontent.com/4626977/68668259-7532af80-0550-11ea-890d-041acdaff402.png)

Steps to recreate:
1. Create table using Builder
2. Add single column "id" by hitting `"Add ID"` button
3. Click `"Save"` button to save table
4. Drop all tables with `php artisan october:down` command
5. Replace `$table->increments('id')->unsigned();` with `$table->bigIncrements('id');` in the correspondent `up()` function.
6. Recreate all tables with `php artisan october:up` command
7. Go to Builder and check table structure within

**Comment by daftspunk** [comment]
This is confirmed. Thanks

**Comment by daftspunk** [comment]
Looks like this is a defect in doctrine (`Doctrine\DBAL\Schema\Table`) when returning the column length, so outside of the scope of this plugin.
