### ISSUE TITLE
Order Error - Implement the NestedTree or Sortable traits. 

### ISSUE THREAD

**Issue by jcbbuller** [rainlab/builder-plugin#313]
I have my fields set so they can be reordered and my controller has reordering capabilities, but when I click the reorder button when accessing the custom plugin I built using RainLab Bulder, I get an error page with the following:

"The model must implement the NestedTree or Sortable traits. /Users/jacobbuller/Desktop/Sites/bullernotbuellercms/modules/backend/Behaviors/ReorderController.php line 225"

Anyone know how to fix this issue?

**Comment by jcbbuller** [comment]
So I did a little research and added use \October\Rain\Database\Traits\Sortable; to the extended model of my plugin, but now I'm getting an "Unknown column 'sort_order' in 'order clause'" error when I click the reorder button. 

Any solutions?

**Comment by bennothommo** [comment]
@jcbbuller You need to add a `sort_order` column to the database table that your model uses. That's how the `Sortable` trait keeps track of item ordering :)

**Comment by jcbbuller** [comment]
That worked! You'd think the plugin would add sort_order automatically when I select ordering as an option when building the plugin. I added sort_order and set it as an integer and set the default value to null. Works now! Thanks!

**Comment by bennothommo** [comment]
@jcbbuller That's a fair point. We'll take the suggestion under advisement. :)
