### ISSUE TITLE
:id not added automatically to details url

### ISSUE THREAD

**Issue by jcbbuller** [rainlab/builder-plugin#314]
I noticed when I created a single page using the Records Details component it didn't automatically add the identifier value to the url integer in the .htm file. Instead of url="/movies-page/:id" it just had url="/movie-page". I had to go in and manually add it to the file. Any reason why this might be?

**Comment by LukeTowers** [comment]
Adding components to pages shouldn't modify the page's URLs automatically. Any reason why you thought it should?

**Comment by LukeTowers** [comment]
FYI, not being sarcastic, legitimately curious 😄

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
