### ISSUE TITLE
Make the Inspector popup resizable by the user

### ISSUE THREAD

**Issue by ayumi-cloud** [rainlab/builder-plugin#315]
Firstly, thank you to Luke who will correct my title! haha.

I will try to explain the problem I'm seeing.

Take the following screenshot example:

![image](https://user-images.githubusercontent.com/57409060/70916032-dc8dc480-2012-11ea-94b0-24380de253c1.png)

Make the container re-sizable, like this gif:

![ezgif-5-656dc8473f7b](https://user-images.githubusercontent.com/57409060/70916145-18288e80-2013-11ea-8c09-14c62e71d37c.gif)

I'm sure it's easy to do, never done it before, any ideas?

Hopefully it would be a good feature to have.

I always run into this issue, every time I use Builder plugin.

**Comment by ayumi-cloud** [comment]
I see it's a jQuery UI feature: https://jqueryui.com/resizable/

**Comment by ayumi-cloud** [comment]
I see it's a jQuery UI feature: https://jqueryui.com/resizable/

Vanilla JS and Pure CSS (Not working in IE11): https://stackoverflow.com/questions/8960193/how-to-make-html-element-resizable-using-pure-javascript

```css
div.control-popover {
    resize: both;
    overflow: auto;
}
```

When I try to add the above css code and click on the resize the container keeps closing due to the javascript code.

**Comment by LukeTowers** [comment]
This is something that would have to be done in the core. I don't mind it as long as it's a proper progressive enhancement that only shows up on browsers that would support it and doesn't break any existing uses of it.

**Comment by ayumi-cloud** [comment]
Going to close this and investigate adding it to the core instead.
