### ISSUE TITLE
Reorder feature doesn't show plugin list fields, just hamburgers. 

### ISSUE THREAD

**Issue by jcbbuller** [rainlab/builder-plugin#317]
I'm having an issue with the plugin not showing the title of each element when I go to the Reorder tab.

I've created a sort_order field in the database and it works on the front end, as far as changing the numerical value in that field will adjust the hierarchy of elements on the site. But when I access the database using the Builder plugin and navigate to Reorder Records I see three hamburgers and nothing else to identify the three records I currently have in my database. If I go back to the Record List I'll see the titles, which I indicated I wanted to see on the list when building the plugin. I just don't see those same record titles in the Reorder window, which makes it hard to reorder. Attached is a screenshot. 
<img width="1342" alt="Screen Shot 2019-12-25 at 6 48 58 PM" src="https://user-images.githubusercontent.com/39416698/71452208-43645980-2748-11ea-8048-4d5afbc5d3e6.png">

**Comment by mjauvin** [comment]
Did you properly set "nameFrom" as explained here in the docs? https://octobercms.com/docs/backend/reorder#configuring-reorder

**Comment by jcbbuller** [comment]
That worked, for the record everyone, you have to put the title of the field name after nameFrom. The one shown on the October's site says nameFrom: title. But since in my database it was feature_title, I had to add nameFrom: feature_title to the config_reorder.yaml. The config_reorder.yaml file can be found in your custom plugin controllers folder.
