### ISSUE TITLE
Updating Table problem, 'null' default value (only on Windows- mariadb)

### ISSUE THREAD

**Issue by reunior** [rainlab/builder-plugin#319]
When i try to add/remove/update some field from Builder -> Database I get error, because my default  nullable value is string null ( **'null'** ) not just **null**.  And i get error for fields that is not string (exp. _Invalid default value for the integer column 'temp_old_id'. The allowed formats are '10', '-10'._)
This only happens on windows os, linux working fine.
When i try to change from **'null'** to just **null**, than it recognize that field as changed, and i don't wont that.

**Comment by reunior** [comment]
![image](https://user-images.githubusercontent.com/49398361/74857875-a76c5e00-5344-11ea-8ea9-cac88304713b.png)

**Comment by bennothommo** [comment]
@reunior This is the same issue as reported in some comments here: #295. I will take a look at this along with the initial issue in that report.

**Comment by reunior** [comment]
> @reunior This is the same issue as reported in some comments here: #295. I will take a look at this along with the initial issue in that report.

Ok, great. Thanks

**Comment by faselunare** [comment]
Hi, this problem (same of the #295) occur also on linux (my dev env is on raspberry)

PHP 7.3.11-1~deb10u1 (cli) (built: Oct 26 2019 14:14:18) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
with Zend OPcache v7.3.11-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies

DB: 10.3.17-MariaDB-0+deb10u1 Raspbian 10

OctoberCms Build 465
Builder 1.026

**Comment by pittss** [comment]
Hi, try this plugin https://octobercms.com/plugin/cubecamp-doctrine , may be help you

**Comment by faselunare** [comment]
hi @pittss, I did a quick test, it seems to work!
Thank you

**Comment by reunior** [comment]
> Hi, try this plugin https://octobercms.com/plugin/cubecamp-doctrine , may be help you

Great, thank you! 

@bennothommo use this fix(plugin) to solve this problem!
