### ISSUE TITLE
Add Delete button to the controller's index page if the controller implements the List Behavior

### ISSUE THREAD

**Issue by DanielHitchen** [rainlab/builder-plugin#32]
At the moment there is only the "Create" button that appears, but could also do with the delete button to delete multiple items from the list, or at least the option to add it.

Cheers

**Comment by alekseybobkov** [comment]
Hi Daniel. Builder doesn't edit or delete PHP files, it's one of the design concepts. Please read the [plugin documentation](http://octobercms.com/plugin/rainlab-builder).

**Comment by DanielHitchen** [comment]
Hi @alekseybobkov, I think you misunderstand me, I don't mean to delete PHP files, i mean to delete modal table items. Once you've created your modal, fields.yaml & columns.yaml and hooked up your controller, when you navigate to your plugin page in the backend there is only a create button, but once you created a few items in your plugin database table, there's then no way to delete multiple items other than to go into each one & delete it - hope that makes more sense?

**Comment by DanielHitchen** [comment]
Ah, thanks for updating the title, that explains it better ;)

**Comment by alekseybobkov** [comment]
This feature is already implemented: 

![delete-selected](https://cloud.githubusercontent.com/assets/481606/22006439/ef93e38c-dc1f-11e6-8a89-61dfb904a2b5.png)
