### ISSUE TITLE
Instead of Timestamp, the Builder creates a Date and Time column type

### ISSUE THREAD

**Issue by igor-tv** [rainlab/builder-plugin#320]
Also, if you try to change the column type from Date and Time to Timestamp, after saving it displays the message "There are no changes to save".

Apache
PHP Version 7.4.1
MySQL 5.7.26

**Comment by bennothommo** [comment]
@igor-tv The `TIMESTAMP` column type in MySQL is basically an alias of `DATETIME`. If you want to store UNIX timestamps, you should generally use an `INT` column.

See here: https://dev.mysql.com/doc/refman/8.0/en/datetime.html
