### ISSUE TITLE
New "Roles" spec is getting stripped

### ISSUE THREAD

**Issue by dathwa** [rainlab/builder-plugin#321]
Hi Guys. Seems it's not possible to add ROLES to permissions. See `https://octobercms.com/docs/backend/users`. 
If I manually add roles, e.g.
`permissions:
    acme.events.manage_events:
        tab: Events
        label: 'Manage Events'
        roles: 
            - 'xxx'
            - 'publisher'`
the edit gets over-written next time i edit the permissions.
If I delete permissions in the yaml, and use "registerPermissions" in the boot file, then I don't seem to have access to the registered permissions to assign to a menu-item or controller.
Any ideas? Thank-you.

**Comment by LukeTowers** [comment]
@bennothommo this should just be an edit to widget's configuration to allow the roles property through correct?

**Comment by bennothommo** [comment]
@LukeTowers possibly - will take a look soon.

**Comment by daftspunk** [comment]
Hi @dathwa,

This should be fixed in v1.1.3 of the builder plugin

Thanks
