### ISSUE TITLE
Support for "titleFrom" and "style" attributes in repeater widgets missing

### ISSUE THREAD

**Issue by bennothommo** [rainlab/builder-plugin#324]
Reported by forum user **guglielmana34864** here: https://octobercms.com/forum/post/style-collapsed-via-builder?page=1#post-30752

**Comment by ivang76** [comment]
Hi @bennothommo, I'm wondering if you have a timeline about this fix.
Thank you

**Comment by bennothommo** [comment]
@ivang76 The fix is now deployed, and will be released with version 1.0.27 of the Builder plugin. This will hopefully be out in the next couple of days.

**Comment by ivang76** [comment]
perfect, thank you Ben!
