### ISSUE TITLE
Support for "nestedform" type

### ISSUE THREAD

**Issue by ivang76** [rainlab/builder-plugin#325]
Actually it's possible to group fields of the forms only with the repeater (maybe setting to max 1 item) but this needs a cta from the user to "add new item" to open and show the fields. Not so nice from a UI point of view, in particulary on complex multisection backend interfaces.

It seems the only form widget of October not yet implemented in OctoberCms is the "**nestedform**", so as adviced by Luke in the forum (https://octobercms.com/forum/post/nestedform) here I'm to ask if would be possible to add this to a next build.

**Comment by Eoler** [comment]
> Actually it's possible to group fields of the forms only with the repeater (maybe setting to max 1 item) but this needs a cta from the user to "add new item" to open and show the fields. Not so nice from a UI point of view, in particulary on complex multisection backend interfaces.

You have recently added `minItems` option for nicer UX:
https://octobercms.com/docs/backend/forms#widget-repeater

**Comment by ivang76** [comment]
That's a nice tips @Eoler, thanks, but unfortunately doesn't work if you have multiple repeaters nested the main one and that are activated by triggering states

**Comment by bennothommo** [comment]
@ivang76 Nested form might be a difficult one to pull off in the context of the Builder plugin - it requires the user to have written a form config to load with the nested form. While that's indeed possible - from a UI perspective, I'd assume people would want to see the fields of the nested form visible in the "preview" of the form.

Would you be willing to provide a PR for it?

**Comment by ivang76** [comment]
ok I understand... well, I'll try to make some tests and if will find a good way I'll open a PR

**Comment by bennothommo** [comment]
@ivang76 Awesome! Let me know if you need any assistance.

**Comment by LukeTowers** [comment]
@bennothommo can't we reuse a bit of the existing code for repeater support? That doesn't require a separate config to exist, and technically neither does the nested form.

**Comment by bennothommo** [comment]
@LukeTowers I'd imagine so - but I haven't really delved into that side of the code too deeply yet.

**Comment by daftspunk** [comment]
Added this to the internal tracker for the next iteration of builder.

Thanks Ivan
