### ISSUE TITLE
Error in parsing model builder options:true. Field: Tag List 

### ISSUE THREAD

**Issue by webkotlas** [rainlab/builder-plugin#326]
**storm-min.js?v=465:5499 Uncaught Error: The string list value should be an array. Property: options at StringListEditor.BaseEditor.throwError ...**

From the documentation:
https://octobercms.com/docs/backend/forms#widget-taglist

> **options** - specifies a method or array for predefined options. Set to **true** to use model get*Field*Options method. Optional.

Please correct the model validation for fields.yaml. After setting the options to true, the model builder stops working.

**Comment by bennothommo** [comment]
@maxim-web-dev would you be able to provide us with more info - was this when you had created the tag list for the first time, or edited afterwards? Would you be able to clarify the steps you took for the error to occur?

**Comment by maxim-web-dev** [comment]
> @maxim-web-dev would you be able to provide us with more info - was this when you had created the tag list for the first time, or edited afterwards? Would you be able to clarify the steps you took for the error to occur?

In the video, I showed when an error occurs:
https://youtu.be/0zS3ft86Z_I

**Comment by bennothommo** [comment]
@maxim-web-dev Thanks for that - so it happened with an already-created form with a taglist widget. Would you be able to show us what was saved in the `models/product/fields.yaml` file by the Builder plugin?

**Comment by maxim-web-dev** [comment]
@bennothommo It normally saves the file if you do not click on the sheet tag settings.
`    fields:
        city_id:
            label: 'Cities'
            mode: array
            separator: comma
            customTags: 0
            options: true
            useKey: 1
            span: auto
            type: taglist`

**Comment by daftspunk** [comment]
This is a known issue. If the builder outputs an array, it expects an array. Some values are hybrids and it results in these JS issues. Added this to the internal tracker for the next iteration of builder.

Thanks!

**Comment by daftspunk** [comment]
Fixed as part of https://github.com/rainlab/builder-plugin/pull/372
