### ISSUE TITLE
Add New Column - Invalid default value for the integer column

### ISSUE THREAD

**Issue by MattMcManis** [rainlab/builder-plugin#327]
I built an OctoberCMS site on a Local VirtualBox LAMP server and moved it and the MySQL database to A2 Shared Hosting.

---

### Error

The live site is working fine, but when I use the Builder plugin to add a new database column and save, I get the error:
```
Invalid default value for the integer column 'sort_order'. The allowed formats are '10', '-10'.
```
But the value is `10`.

![database](https://i.stack.imgur.com/bNLfi.png)

![error](https://i.stack.imgur.com/XRRhR.png)

---

### Server

My **Local VirtualBox Server** is running `MySQL 5.7.29-0ubuntu0.18.04.1`.

The **A2 Hosting Server** is running `MySQL 10.3.22-MariaDB-cll-lve`.

---

### Database Connection

The `database.php` config file looks like this, with the database name, username, and password filled in.

```
'mysql' => [
    'driver'     => 'mysql',
    'engine'     => 'InnoDB',
    'host'       => 'localhost',
    'port'       => 3306,
    'database'   => '',
    'username'   => '',
    'password'   => '',
    'charset'    => 'utf8mb4',
    'collation'  => 'utf8mb4_unicode_ci',
    'prefix'     => '',
    'varcharmax' => 191,
],
```

---

### Question

Why does saving the new column not work?
Does it have something to do with MySQL on the local server and MariaDB on the A2 server?

**Comment by LukeTowers** [comment]
Set the default value of the sort_order column to 0.
