### ISSUE TITLE
Ajax not work when create new string

### ISSUE THREAD

**Issue by codebugs** [rainlab/builder-plugin#33]
Hello All,

Is it only me who has problem with new (localization) string creation?
When I try to create the new string the AJAX just keeps loading endless...

Could you please help me?

If you would have any question do not hesitate to ask me...
Thank you

**Comment by codebugs** [comment]
I seems it was some PHP version issue beucase after PHP version update (from 5.4 to 5.6 it works fine now). Thanks!

**Comment by beysong** [comment]
Excuse me, but this error still exist with me.

**Comment by alekseybobkov** [comment]
@beysong - does it happen always, or sometimes? Please post a list of steps to reproduce the problem.
