### ISSUE TITLE
Preload a field with User profile info ?

### ISSUE THREAD

**Issue by Incremental92** [rainlab/builder-plugin#330]
Hello, in a Builder form, how is it possible to pre-load a "user name" field with the logged user info given by the User Plugin ?
Is this User info accessible from anywhere in October and how ?
Thanks

**Comment by bennothommo** [comment]
@Incremental92 that's outside the scope of the Builder plugin. You would want to use the `form.extendFields` event in a plugin to set the default value to be the username of the currently logged-in user.

**Comment by Incremental92** [comment]
Thanks a lot !
