### ISSUE TITLE
Display record without url parameter

### ISSUE THREAD

**Issue by mskraban** [rainlab/builder-plugin#333]
I'm wondering if it's possible to display builder record on my landing page without passing url parameters (because it's landing page). I have column called published, that is linked to switch. If switch is true, then that record would be displayed. 

**So it's maybe possible to display record details if database column parameter is active, or should I use record list for this case?**

**Comment by iMateo** [comment]
You can use Record list with "published = true" filter as simplest solution for your case.
Or you may spend several hours to learn how to work with Laravel Models and Eloquent :)
