### ISSUE TITLE
dependsOn option in fields generator not working

### ISSUE THREAD

**Issue by digitreadmedia** [rainlab/builder-plugin#336]
**OctoberCMS Build: 468**

When trying to add a dependson option to fields, a popup opens with raw HTML and no close button.

![dependson](https://user-images.githubusercontent.com/48868778/90904401-86f28e80-e3cf-11ea-81c6-aa0648aea5d0.png)

**Comment by bennothommo** [comment]
@digitreadmedia Could you please run `php artisan october:util compile js` from the command line, inside your project folder, and try again?

**Comment by digitreadmedia** [comment]
@bennothommo I've installed a completely new build and ran php artisan october:util compile js but it made no difference.

**Comment by daftspunk** [comment]
Hello, I was unable to confirm this bug using October v2.1.31. I recall there was a core issue that was fixed that may have been causing this problem. If it is still an issue, feel free to contact us via the professional support channel: https://octobercms.com/contact

Best regards
