### ISSUE TITLE
Trouble with path url when deploy to server develop

### ISSUE THREAD

**Issue by khoanndang** [rainlab/builder-plugin#342]
I have a trouble with path url
In local: 
- everythings okay.
Ex: 
- In Backend: enter to menu Builder Plugin with path url http://localhost/vgaming-octobercms/backend/rainlab/builder => Ok

==================================
In server develop:
- When I enter to menu Builder (Builder Plugin - http://my-domain/backend/rainlab/builder) in navigation bar, October CMS return 404 not found page. I don't know what wrong is here
- Most of the functions are working properly, but there are some areas where the path url has problems. 

======================================
Sorry for my english

**Comment by bennothommo** [comment]
@khoanndang Are you sure your `app.url` configuration value is set correctly on the server? You could also try running `php artisan cache:clear` on the server if you have copied any cache files to the server.

**Comment by khoanndang** [comment]
> @khoanndang Bạn có chắc chắn `app.url`giá trị cấu hình của mình được đặt chính xác trên máy chủ không? Bạn cũng có thể thử chạy `php artisan cache:clear`trên máy chủ nếu bạn đã sao chép bất kỳ tệp bộ đệm nào vào máy chủ.

Ya, I checked again variable url in config/app.php . Everythings ok. I have also run the command `php artisan cache:clear` `php artisan cache:config` . And nothing changes :(

**Comment by khoanndang** [comment]
I cannot imagine where the problem is arising from, because in local server everything is very smooth
Additional:
- In local: Window 10, xampp, php version 7.4
- In develop server: Linux Ubuntu 18.04, nginx, php version 7.3

*************************
Is there a solution to handle this situation without having to re-deploy the code from scratch

**Comment by khoanndang** [comment]
- In local server (window 10):
Enter to menu Builder (Builder Plugin)
![ok1](https://user-images.githubusercontent.com/39475107/102958216-04a9e080-450f-11eb-99a8-a4b1ffeed988.PNG)
![ok2](https://user-images.githubusercontent.com/39475107/102958232-0a072b00-450f-11eb-9027-a8f913b963c4.PNG)

Enter to view detail News
![ok6](https://user-images.githubusercontent.com/39475107/102958256-15f2ed00-450f-11eb-9b92-067fc0fce961.PNG)
![ok7](https://user-images.githubusercontent.com/39475107/102958261-18eddd80-450f-11eb-8423-3df303e7fc2e.PNG)


==================================
- In develop server (linux Ubuntu 18.04)

 Bug in backend - enter to menu Builder (Builder Plugin)
![bug2](https://user-images.githubusercontent.com/39475107/102957776-edb6be80-450d-11eb-997e-70d366d8c3b3.PNG)
![bug3](https://user-images.githubusercontent.com/39475107/102957784-f14a4580-450d-11eb-994c-b7f36a6e85f5.PNG)

 Bug in frontend - enter to view detail News => url change, but layout the same, not directly
![bug6](https://user-images.githubusercontent.com/39475107/102957982-77ff2280-450e-11eb-921d-35e6f13852f6.PNG)
![bug7](https://user-images.githubusercontent.com/39475107/102957993-7cc3d680-450e-11eb-9f6b-dd8b49b1c19d.PNG)

**Comment by khoanndang** [comment]
Define page for list News and Pagination
![check2](https://user-images.githubusercontent.com/39475107/102958666-0cb65000-4510-11eb-81aa-35ca668f22da.PNG)

Define page for view detail News with slug
![check1](https://user-images.githubusercontent.com/39475107/102958697-1b9d0280-4510-11eb-8b21-1c49255e8e71.PNG)

==============================================
Hope everyone has enough information to understand my problem. Thanks all

**Comment by khoanndang** [comment]
Hope everyone has enough information to understand the problem I'm having. Tks all

**Comment by LukeTowers** [comment]
@khoanndang enable app.debug to see what the problem is. Looks to me like you're encountering a server error (500), but your theme does not have a 500 error page configured so instead it's showing the 404 error page instead.

**Comment by khoanndang** [comment]
> @khoanndang bật app.debug để xem vấn đề là gì. Có vẻ như tôi đang gặp phải lỗi máy chủ (500), nhưng chủ đề của bạn không có trang lỗi 500 được định cấu hình nên thay vào đó nó hiển thị trang lỗi 404.

![bug1](https://user-images.githubusercontent.com/39475107/103071411-20d47d00-45f6-11eb-9b30-882750d09bb9.PNG)
I've do it, Can u show me where can I see the problem.

**Comment by LukeTowers** [comment]
@khoanndang go to the URL that you were having problems with

**Comment by khoanndang** [comment]
> @khoanndang go to the URL that you were having problems with

![bug3](https://user-images.githubusercontent.com/39475107/103074679-b4a94780-45fc-11eb-83c1-f521bf2adb52.png)
I still get this error  :(

**Comment by LukeTowers** [comment]
Do any of the other plugins work or is it just the builder plugin?

**Comment by khoanndang** [comment]
The plugins built from the Builder Plugin still work fine. Only the Builder Plugin has problems. 
Currently I can only use the builder plugin on the local server

**Comment by LukeTowers** [comment]
@khoanndang what are all the other plugins you have installed? And what is the APP_ENV set to on your linux server?
