### ISSUE TITLE
The image is uploaded but not recorded in the database

### ISSUE THREAD

**Issue by SciCrea** [rainlab/builder-plugin#343]
I upload the image, in the backend it is, but in the frontend it is not.

I looked at the database, in the plugin table, in the column with the image empty.

The image is uploaded but not recorded in the database. Why don't I know.

**Comment by LukeTowers** [comment]
@SciCrea what field type are you using? See https://github.com/octobercms/docs/commit/a2ec0ef13bbb32b514f00392d639f656e1e1a1a0 and make sure you're following the instructions on how to use `fileupload` vs `mediafinder` fields properly.
