### ISSUE TITLE
Setting language string / label on model gives JavaScript error

### ISSUE THREAD

**Issue by FrontEndStudio** [rainlab/builder-plugin#35]
When I try to set a language string via Builder -> Models -> Forms -> Label: Title [+] sign

I get an error when I have filled in the String key and String value and hit the ok button:

TypeError: this.options is null
http://hostname/plugins/rainlab/builder/assets/js/build-min.js?v1.0.5
Line 2

Is there away to test with an unminified build-min.js version ?

I am using:

FireFox 44.0.2 (Google Chrome also gives the same TypeError)
Builder 1.0.5
October Build 316

**Comment by alekseybobkov** [comment]
Can you please post the call stack from Chrome console? You can expand the exception message in the console to see the stack. Thanks.

**Comment by FrontEndStudio** [comment]
Have set some breakpoints but the stacktrace does not reveile much:

Uncaught TypeError: Cannot read property 'plugin' of nulli.onSubmitPopupForm @ build-min.js?v1.0.5:2n.event.dispatch @ jquery.min.js?v316:3r.handle @ jquery.min.js?v316:3

TypeError: this.options is null
i.prototype.onSubmitPopupForm()
 build-min.js:2
n.event.dispatch()
 jquery.min.js:3

Don't bother too much.

I started from scratch with a new builder plugin and now I am able to set language strings. The initial setup takes about 20 - 30 seconds probally the first time I was impatient and clicked away while the blue bar was still running.
