### ISSUE TITLE
Creating a migration: creates an error unexpected syntax

### ISSUE THREAD

**Issue by mistahcheong** [rainlab/builder-plugin#351]
After creating a new plugin, then trying to create a new migration. After clicking save and close, a modal pops up and shows the following error:

`syntax error, unexpected '<', expecting function (T_FUNCTION) or const (T_CONST)" on line 8 of /var/www/html/...`

- Plugin is created
- But migration is not made, no table found on MySql

This is the migration code that your plugin created:
`public function up() { Schema::create('solas_testplugin_', function($table) { $table->engine = 'InnoDB'; $table->increments('id'); }); } public function down() { Schema::dropIfExists('solas_testplugin_'); }`

**Comment by mistahcheong** [comment]
I found the error. Plugin does not work with wysiwyg specifically by Anand Patel. Hopefully you guys can override certain plugins; editors and such, when we are using your plugin.

**Comment by daftspunk** [comment]
Thanks for reporting back. Please make sure this information is given to Anand Patel
