### ISSUE TITLE
Question: Does table creation support the use of database schemas?

### ISSUE THREAD

**Issue by mcalexster** [rainlab/builder-plugin#353]
I want to create tables with different schemas in the database, is this possible?  I looked through documentation but it doesn't seem to be supported, at least I couldn't find any references to do this.

If it can't be done by builder-plugin, can you add the schema to the tables externally and still use the plugin for such things as later ddl changes or will builder not see the altered table any more?

Thank yuu

Using: pgsql 13

**Comment by daftspunk** [comment]
Yes, you are able to modify the plugin on the file system to introduce any database schema you like. The builder plugin should be able to detect the schema and changes that you make.

View the documentation for more details on coding this by hand: https://octobercms.com/docs/database/structure

I hope this helps!
