### ISSUE TITLE
Date localization

### ISSUE THREAD

**Issue by SciCrea** [rainlab/builder-plugin#354]
Hello, the date is displayed without localization. The language is installed in the settings. The Blog plugin displays localization.

**Comment by daftspunk** [comment]
Please provide more information on the problem, expectation and current behaviour

**Comment by SciCrea** [comment]
I created a plugin with the "Date and Time" field. Twig:
`{{ record.date|date('d M') }}`

Get:
`12 Apr`

I'm waiting for a date in Cyrillic

**Comment by SciCrea** [comment]
Need more information?

**Comment by SciCrea** [comment]
You need to specify the type of field in the model.
`protected $dates = ["variable"];`
