### ISSUE TITLE
Error when saving plugin with File field

### ISSUE THREAD

**Issue by mistahcheong** [rainlab/builder-plugin#356]
When creating a new record with a file upload field it returns this error:
`"array_flip() expects parameter 1 to be array, null given" on line 86 of /var/www/html/october-cms/solas/vendor/october/rain/src/Database/Behaviors/Purgeable.php`

I already included the input field to the model in `public $attachOne` and removed the field on the database. How can I save files and images?

**Comment by daftspunk** [comment]
Hello @mistahcheong !

What version of Ocrtober CMS are you using? Also what version of RainLab.Translate do you have installed?

**Comment by mistahcheong** [comment]
I'm currently using v2 of octobercms and v1.7.4 for the Rainlab.Translate. Is this the issue? I'll try updating it

**Comment by daftspunk** [comment]
Yes, that would be it, v2 support for Translate was added in v1.8 and above

Thanks
