### ISSUE TITLE
move plugin

### ISSUE THREAD

**Issue by happyprogrammer2020** [rainlab/builder-plugin#357]
hi 
what  ever can i move created plugin in builder to other web site? 
i want this plugin appear to plugin builder and i can change it not as a plugin that instal it and use it.
thanks

**Comment by daftspunk** [comment]
Hi @happyprogrammer2020 

Plugins that you create with the builder plugin should appear in the `/plugins` directory of your website. From here you can transfer them to any other website. 

I hope this helps
