### ISSUE TITLE
Adding form fields to model does not load the .env DB connection variables

### ISSUE THREAD

**Issue by uematsusoft** [rainlab/builder-plugin#359]
Hi.

Since September 1st (back from vacations) I noticed that, in builder plugin, every time I add a form control to a model form and select the "field" field, I get an error before it loads the DB fields list to choose from (auto-complete).

It appears that it can't load the correct .env file DB connection variables since I changed the default values in the config/database .php file and the error stopped. (The DB server is in a different machine and network)
I also noticed that editing the add control fields (Label, Comment, Span, etc.) has become very slow. For example, it takes about a second to change the checked state from the "required" field.

The attached image shows the error.
The error occurs when calling, via XHR, the URL "https://site.test/settings/rainlab/builder".

Can anyone shed some light in how can I resolve this problem?

Thank you in advance.

Best regards,
Domingos

![error_octobercms_builder_plugin](https://user-images.githubusercontent.com/46530682/133772798-3b4f0039-90db-4fd0-831d-0106cf6644ca.jpg)

**Comment by daftspunk** [comment]
Hi Domingos,

Sorry to hear you are having difficulties.

Unfortunately, I was unable to replicate this problem using October CMS v2.1.8 and v1.1.0 of this plugin. The environment variables are used along with the default file-based configuration. The response time is also normal.

The performance seems to be network related and it's possible that your environment variables are getting emptied somehow, which resorts to the default values being used.

If you have any more information we can use to troubleshoot, that would be helpful. If you are able to share your environment, feel free to send details to us via email.
