### ISSUE TITLE
How to add comment for field via UI of Database?

### ISSUE THREAD

**Issue by CockyCat** [rainlab/builder-plugin#367]
I just only add column, but i can't add comment via UI.

**Comment by CockyCat** [comment]
have been supported

**Comment by CockyCat** [comment]
I have upgrade 1.1.4, but i still cant add comment on UI.

**Comment by daftspunk** [comment]
Hello, this feature is enabled in the Builder Settings. Navigate to Settings → Builder

![image](https://user-images.githubusercontent.com/1392869/163146513-eafe2ad2-95c9-4321-9fac-76a64c0a2aab.png)

Enable the setting in the screenshot for the comment feature to be activated.

I hope this helps!
