### ISSUE TITLE
BadMethodCallException: Method October\Rain\Validation\Validator::validateReserved does not exist

### ISSUE THREAD

**Issue by dathwa** [rainlab/builder-plugin#369]
Hi. 
I've got an issue trying to create a new plugin. When i try to save it.
BadMethodCallException: Method October\Rain\Validation\Validator::validateReserved does not exist. in \public_html\vendor\laravel\framework\src\Illuminate\Validation\Validator.php:1307

OCMS 2.2.32 - all other plugins up-to-date.
Was working a few days ago.
Any ideas anyone?
Thanks

**Comment by daftspunk** [comment]
Hey @dathwa 

Thanks for the bug report; try updating to v1.2.4 of this plugin to see if it helps.
