### ISSUE TITLE
Reorder Controller?

### ISSUE THREAD

**Issue by tsioukas** [rainlab/builder-plugin#37]
Does options in list controller "Show sorting, Show tree, Tree expanded" creates sorting lists? 
https://octobercms.com/docs/backend/reorder

If yes there is a bug on that, looks like that it doesn’t work. If no can you add that on future features.

Thanks

**Comment by alekseybobkov** [comment]
Those options do not create sorting lists. http://octobercms.com/docs/backend/lists#configuring-list

There's another controller behavior - ReorderController, which creates a separate page that implements the sorting. @gpasztor87 is working on integrating the behavior to the Builder.
