### ISSUE TITLE
Error when creating a new plugin in the newest update [version: 3.1.22]

### ISSUE THREAD

**Issue by Thulaa123** [rainlab/builder-plugin#370]
"Undefined constant Backend\Behaviors\FormController::CONTEXT_CREATE" on line 39. ..../plugins/rainlab/builder/classes/IndexOperationsBehaviorBase.php

Please correct this function.

**Comment by daftspunk** [comment]
Hello, thank you for the report. This is fixed in Builder v1.2.6

**Comment by Thulaa123** [comment]
Hello Rainlab/Builder-Plugin team, your last released version is v1.2.5 on
jul 22 2022
