### ISSUE TITLE
Call to undefined method RainLab\Builder\Models\ControllerModel::processImportExportConfig() 

### ISSUE THREAD

**Issue by chiragsenjaliya** [rainlab/builder-plugin#374]
Hi,

Error: Call to undefined method RainLab\Builder\Models\ControllerModel::processImportExportConfig() in [/home2/srv4/vop.srv4.softwareimc.dev/plugins/rainlab/builder/models/ControllerModel.php:416](javascript:)

It should be **_$this->processImportExportBehaviorConfig($configuration, true);_** 

Thanks

**Comment by daftspunk** [comment]
Fixed in 45d869d0481d503a4cbdf452a6bcfb31350da333

Thanks!
