### ISSUE TITLE
Unable to find configuration file - Error in October CMS 3.4.6 install

### ISSUE THREAD

**Issue by RempadDesign** [rainlab/builder-plugin#375]
Hi,

We have a problem after creating a plugin via the Builder plugin.
We get the "Unable to find configuration file" error and didn't manage to find why. We were using the Builder for years and didn't had any issues. Now, in October cms V 3.4.6 we had Fatal Error on instalation and after fixed that we now have this issue.

When we are trying to Create a record, the system throws the "Unable to find configuration file" error like this:
"Unable to find configuration file /home/user/public_html/dev/project-name/plugins/developer/slider/models/slider defined for Backend\Behaviors\FormController." on line 55 of /home/user/public_html/dev/project-name/modules/system/traits/ConfigMaker.php

Is there anyone who has this problem?
Thank you in advance.

**Comment by daftspunk** [comment]
Hey @RempadDesign 

So we can better understand the issue, please can you confirm what version of Builder you are using? And also, what steps are taken to arrive at the error?

Based on the error, you may need to check the `developer/slider` plugin, it appears to be referring to a configuration file without its file extension (.yaml).

Best regards

**Comment by RempadDesign** [comment]
Hi, thanks for your prompt answer.
We are using the latest 2.0.5 Builder version. We have created all the plugin dependencies from the Builder interface (Database, Models, Menus, Controllers etc.) like we did every time we were building a plugin with it for years. When we are trying to Create a record, the error is thrown.

The developer/slider structure is like this: https://snipboard.io/0EbWXL.jpg
We have never manualy created the configuration.yaml file you are reffering to.. we don't understand why is now missing.

Thank you in advance.

**Comment by daftspunk** [comment]
Hi @RempadDesign 

It is still possible to enter a file without the `.yaml` at the end using builder. Please check all the controller YAML files since they make reference to the model YAML files. Specifically, can you share the contents of the file **plugins/developer/slider/controllers/sliders/config_form.yaml** and **config_list.yaml**

**Comment by RempadDesign** [comment]
Hi and sorry for the late answer.
The cont on the specified files is for config_form.yaml:
name: Sliders
modelClass: Developer\Slider\Models\Slider
form: $/developer/slider/models/slider
defaultRedirect: developer/slider/sliders
create:
    redirect: 'developer/slider/sliders/update/:id'
    redirectClose: developer/slider/sliders
update:
    redirect: developer/slider/sliders
    redirectClose: developer/slider/sliders
preview: {  }

And for the config_list.yaml:
list: $/developer/slider/models/slider/columns.yaml
modelClass: Developer\Slider\Models\Slider
title: Sliders
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'developer/slider/sliders/update/:id'

Thank you in advance.
