### ISSUE TITLE
Builder Plugin Reorder is missing

### ISSUE THREAD

**Issue by ibrarartisan** [rainlab/builder-plugin#376]
In the latest update. The builder plugin is missing the reorder Controller scaffolding.

**Comment by daftspunk** [comment]
Hi @ibrarartisan 

The builder plugin has been updated to the latest specification, where `ReorderController` is no longer used. Take a look at the `structure` option in the `ListController` instead.

**Comment by ibrarartisan** [comment]
> Hi @ibrarartisan
> 
> The builder plugin has been updated to the latest specification, where `ReorderController` is no longer used. Take a look at the `structure` option in the `ListController` instead.


Thank you. However this functionality doesnt work. Even after checking the checkboxes in structure option in the ListController, it comes back as default checked.

**Comment by daftspunk** [comment]
Can you provide more information?
