### ISSUE TITLE
New plugins not showing in plugins list

### ISSUE THREAD

**Issue by H-sans** [rainlab/builder-plugin#379]
I have previously been able to create plugins without any issues. However, now new plugins does not appear in the list after creation, and I am unable to create a database, etc. The plugin is also not visible under system settings. However, I can see the plugin in the plugin folder on the server.  My plugin is matching the configured Builder author namespace .I am using version 3.5.12.

**Comment by daftspunk** [comment]
Hello @H-sans,

Please make sure to check the case sensitivity of the folder names. They should be entirely in lowercase.he folder names should be entirely lowercase.

**Comment by H-sans** [comment]
Thanks for the swift reply @daftspunk. I've checked the case of the folder names, I've also tried combinations with both lower and uppercase, and still getting the same issue. The strange thing is that previously there hasn't been any issue creating plugins.

**Comment by daftspunk** [comment]
Make sure to check the author namespace in Settings → Builder to match expectations.

**Comment by H-sans** [comment]
I did that
![BuilderSettings](https://github.com/rainlab/builder-plugin/assets/48982008/ff60527c-ee82-4fb4-aa0d-b1b3484959b1)
![Builder](https://github.com/rainlab/builder-plugin/assets/48982008/2386eb9a-ff08-4790-8b87-affe47965860)

**Comment by H-sans** [comment]
Upgraded to 3.5.13 and now they are visible.

**Comment by H-sans** [comment]
I need to force update to make my new plugins show
