### ISSUE TITLE
undefined method System\Classes\VersionManager::listNewVersions()

### ISSUE THREAD

**Issue by ardani** [rainlab/builder-plugin#4]
i try to use builder at first time but when i create plugins show that error not found listNewVersions();
i hope it can solve quickly. 
thanks

**Comment by vojtasvoboda** [comment]
You should update your OctoberCMS because in last version, there is definitely method listNewVersions():

https://github.com/octobercms/october/blob/master/modules/system/classes/VersionManager.php#L107

**Comment by ardani** [comment]
i try to run php artisan october:update
and result.
`Updating October...No new updates found`
i dont know what happen with update process on octobercms. should i do change it manually?

**Comment by daftspunk** [comment]
Try now. Build 316 should be released.

**Comment by vojtasvoboda** [comment]
Btw what branch should be used for new projects? Master or stable? Master seems to be little bit behind. Is it safe to use stable?

**Comment by daftspunk** [comment]
Both are OK fine to use, master is RC, stable is v1.0.0 and uses Laravel 5.1 (LTS) and will be available in April and it requires PHP 5.5.9.
