### ISSUE TITLE
[question] What about plugin.yaml?

### ISSUE THREAD

**Issue by ametad** [rainlab/builder-plugin#46]
Great plugin, it really saves time!!

I have a question I cannot find an answer for; hopefully someone can help me out here. Building a plugin with Builder also makes a file in the plugin root called: "plugin.yaml" . Does this plugin work on other systems without the Builder plugin as well? In other words; is this YAML file fully compatible with Octobercms?..or must the content be refactored into the plugin.php once ready for deployment?

**Comment by merodeador** [comment]
i've just tried this. 
The plugins will work, just make sure your main october install is version 316 (or newer, whenever that happens).

**Comment by alekseybobkov** [comment]
@merodeador is right - plugin.yaml is now supported by October core.

**Comment by ametad** [comment]
Thank you!
