### ISSUE TITLE
Can't add a third Timestamp

### ISSUE THREAD

**Issue by Hambern** [rainlab/builder-plugin#49]
Thanks for a fantastic plugin.

I usually define Created_at, Updated_at and Published_at as timestamps for my user to be able to publish the content later. Therefore I need to be able to create three timestamp columns, it always makes the published_at a DateTime. And if I open old plugins i made the plugin do not show that the column is a timestamp. Instead the Builder plugin interface sais that the column is a Date-column.

Why can't I have more than two Timestamp-columns? :)

**Comment by alekseybobkov** [comment]
There's a technical issue with determining (mapping) DB column types to Doctrine column types. It's not reliable in some cases, so the common timestamp column names are used. I will add published_at column to the list, it seems to be common.

**Comment by Hambern** [comment]
Well done :D
