### ISSUE TITLE
Unable to Select a plugin

### ISSUE THREAD

**Issue by pastorryanhayden** [rainlab/builder-plugin#5]
Created plugin using thing > on the left but cannot select it to work with it and add models.

**Comment by daftspunk** [comment]
Try updating to Build 316

**Comment by methodicool** [comment]
I installed the plugin from the CMS backend. Attempted to create a plugin. After plugin is created, I try to access the database or controller options and it says "Plugin is not selected".

I updated to build 316. Uninstalled the builder plugin, reinstalled, created plugin again, and it still says "Plugin is not selected".

**Comment by codebugs** [comment]
I have the same problem... :( I updated to Build 316 but still not works

**Comment by firemankurt** [comment]
I keep getting "Cannot determine the currently active plugin."

**Comment by daftspunk** [comment]
So I'm following these steps.

1. Click the chevron arrow icon to show the plugin list
1. Click "Create plugin" and fill out the form
1. Click the newly generated plugin
1. Click the overlay to close the plugin list
1. Click database > Add

All is working. Are you following these steps and still producing the error?

**Comment by firemankurt** [comment]
Yes.  It always says "Plugin is not selected"

**Comment by daftspunk** [comment]
Just one thing to check, clear your browser cache (or hit refresh 2--3 times on the Builder page) and see if that fixes it.

**Comment by firemankurt** [comment]
I reopend page in "incognito" mode in Chrome.  
Also cleared file cache. 
Also tried reloading page several times.  
Still same result.

**Comment by firemankurt** [comment]
FYI. 
When I click plugin in list here is the Form Data:

search:te
pluginCode:KurtJensen.Test
updatePluginList:0

**Comment by codebugs** [comment]
@daftspunk I just made a brand new fresh installation of October on my localhost and on my hosted server as well and the Builder works on my localhost but it does NOT work on the hosted server.
Here you can find the php info of these servers:
From hosted server (where the Builder does NOT work): http://info.cikkelde.hu/hosted.jpg
From my localhost (where the Builder works fine): http://info.cikkelde.hu/localhost.jpg

I hope it will help you a bit to troubleshoot the problem... ;)

**Comment by joe-conigliaro** [comment]
Same issue here

**Comment by SndrL** [comment]
Same issue. Build 316.

**Comment by alekseybobkov** [comment]
I can't replicate it on my end. Can someone give me access to October installation on a server where it doesn't work? I don't need the server file system access, only October back-end credentials with the CMS permissions. Please send to hello [at] octobercms.com

**Comment by Hoodognik** [comment]
Я могу дать доступ

**Comment by alekseybobkov** [comment]
@Hoodognik  - please send it to `hello [at] octobercms.com`  (replace [at] with @)

**Comment by Hoodognik** [comment]
I sent an email.

**Comment by firemankurt** [comment]
Works for me now.  Thank you alekseybobkov

**Comment by intositeme** [comment]
I know this is closed, but am facing this issue as well. After i refreshed the backend page, my plugin now is not listed on the left and i've got no idea how to get it back.

**Comment by JeyKeu** [comment]
I'm having the same issue on Build number `419` with my locally installed plugin.

**Comment by LukeTowers** [comment]
@JeyKeu that's probably because the Vendor name you have in your builder settings and your plugin is different. Click on the filter button in the plugin listing of the builder plugin to view all plugins.

**Comment by JeyKeu** [comment]
Well, fo me turns out, a stupid mistake may be, or may be my unfamiliarity with the different UI provided by October lead to this confusion. After digging through code it turns out I have filter turned on and I had not set default Author name and namespace under the Builder settings.

![peek 2017-09-25 22-48](https://user-images.githubusercontent.com/642353/30823060-73f5bd9a-a244-11e7-9801-1de681c7df64.gif)
