### ISSUE TITLE
Uncaught TypeError when adding a new string

### ISSUE THREAD

**Issue by Hambern** [rainlab/builder-plugin#50]
I'm trying to use the localization feature by using the new string feature when I create form element tabels. The site just keeps loading after I have entered my string. If I open up the javascript console I get this error:

Uncaught TypeError: Cannot read property 'plugin' of nulli.onSubmitPopupForm @ build-min.js?v1.0.8:2n.event.dispatch @ jquery.min.js?v317:3r.handle @ jquery.min.js?v317:3

I'm using swedish as my default and only language.

**Comment by alekseybobkov** [comment]
Duplicate: #41 

Please post detailed instructions for reproducing the problem to #41.

Thanks
