### ISSUE TITLE
Problem about show "Backend menu" 

### ISSUE THREAD

**Issue by vmdao** [rainlab/builder-plugin#51]
Create new Plugin by Builder, Have problem about show "Backend menu" when allow permission. It is't show. How to you fix it? 
Thank you RainLab. Builder is useful!

**Comment by alekseybobkov** [comment]
Do you mean that a menu item is not shown although the user is allowed to see it?

**Comment by vmdao** [comment]
Yes! User is allowed not see.

**Comment by alekseybobkov** [comment]
I can't replicate the problem. Please make sure that you use latest version of the Builder and core. Submit steps for replicating the problem. If you can - please create a new plugin and attach it as a ZIP file here.

**Comment by vmdao** [comment]
Ok, I uploaded google driver
https://drive.google.com/folderview?id=0B3lfds0CCdr7OFZFLWk4aUVxcVk&usp=sharing

**Comment by vmdao** [comment]
@alekseybobkov, Can you look problem?

**Comment by alekseybobkov** [comment]
I can't confirm the problem. I can see the menu item under the administrator user account and it's expected. When I sign in as another user, I don't see the menu item because the user doesn't have the corresponding permission.

**Comment by ametad** [comment]
I too have a similar problem; hopefully this adds positively to the conversation. With Builder I first create permissions. Then I have set the permissions for backend menus to my controllers in the plugin. 

Example, define the permission:
![image](https://cloud.githubusercontent.com/assets/1582541/13602094/c37f3266-e534-11e5-964c-cbeb068cf333.png)

Then use it for menu:
![image](https://cloud.githubusercontent.com/assets/1582541/13602120/0406cc2c-e535-11e5-804f-0c9b2cdcc2aa.png)
(the companyname is deliberately crossed)

When a user now gets the permission to '..test.access_test' the menu is NOT shown! When I remove the permission from the menu or when I make the user a superuser; the menu is shown again. 

Do I perhaps forget a step or something?

**Comment by alekseybobkov** [comment]
I still can't reproduce it. That's how I test:

* Install a test plugin from https://github.com/rainlab/builder-plugin/issues/51#issuecomment-190512438 (I had to remove updates to not pollute my database).
* Go to Settings / Administrators.
* Assign "Allow" value to Other Brands / Manage Orders permission for a test administrator.
* Log in as the test administrator.
* Make sure that I see the Manage Orders menu item.

If I change "Allow" to "Deny" I don't see the menu item.

**Comment by ametad** [comment]
Thank you for your response!

I will try the same test plugin as you did, with the same steps and report back. 

What do you mean with: "I had to remove updates to not pollute my database". What updates exactly, or does this not concern anyone else you think?

**Comment by ametad** [comment]
Perhaps you mean this:

> Rolled back: Daovm.OrderBrand
> Reinstalling plugin...
> PHP Fatal error:  Cannot declare class Daovm\OrderBrand\Updates\BuilderTableUpdateDaovmOrderbrandOrder4, because the nam
> e is already in use in /home/vagrant/Code/ubpweb2/plugins/daovm/orderbrand/updates/builder_table_update_daovm_orderbrand
> _order_4.php on line 17

**Comment by ametad** [comment]
My test fails unfortunately. The results (if you miss something, please just ask):

This will test the permissions of another administrator then the account I am logged in; for "Manager Orders" are allowed and denied, to see if the menu items appear.

The other account settings:
![image](https://cloud.githubusercontent.com/assets/1582541/13667534/2650ceee-e6b7-11e5-9c52-9dac4191a1cc.png)

Permission "Allow":
![image](https://cloud.githubusercontent.com/assets/1582541/13667650/c50bb116-e6b7-11e5-9cce-59308d1706c8.png)

The account belongs to the "Owners" group, the permission for "Manager Orders" in the group is not selected. 

Now to test the appearance of the menu item, I log into the backend with this other administrator account: the menu item is NOT shown:
![image](https://cloud.githubusercontent.com/assets/1582541/13667841/d4a8d42c-e6b8-11e5-832b-68ce058060bd.png)

But with...
![image](https://cloud.githubusercontent.com/assets/1582541/13667878/19ea3f12-e6b9-11e5-80f1-6df1e469e9dc.png)


The menu item is shown correctly:
![image](https://cloud.githubusercontent.com/assets/1582541/13667921/66c73434-e6b9-11e5-8022-21b3d72186b6.png)

**Comment by ametad** [comment]
Could this perhaps be a caching / cookie problem..?

**Comment by ametad** [comment]
Some more testing data: I have tested if the controller/action is available for the logged in non-super-user, by going to that url (backend/daovm/orderbrand/orders):

Permission 'daovm.orderbrand.manager_order' for user:
- denied: access is denied (as intended!)
- allowed: access is allowed and the page is shown (as intended!)

The only thing that is not correctly working is showing the right menu items, accordingly to the permissions set.

**Comment by ametad** [comment]
Deeper into the code of October we dive...

Dump in \Backend\Classes\NavigationManager registerMenuItems()
of $owner and $definitions:

```
"Daovm.OrderBrand"

array:1 [▼
  "manager_orders" => array:5 [▼
    "label" => "Manager Orders"
    "url" => "http://localhost/backend/daovm/orderbrand/orders"
    "icon" => "icon-bookmark"
    "permissions" => array:1 [▼
      0 => "http://localhost/backend/daovm.orderbrand.manager_order"
    ]
    "sideMenu" => array:1 [▼
      "orders" => array:4 [▼
        "label" => "Orders"
        "url" => "http://localhost/backend/daovm/orderbrand/orders"
        "icon" => "icon-ticket"
        "permissions" => array:1 [▼
          0 => "http://localhost/backend/daovm.orderbrand.manager_order"
        ]
      ]
    ]
  ]
]
```
```
"October.Backend"

array:1 [▼
  "dashboard" => array:5 [▼
    "label" => "backend::lang.dashboard.menu_label"
    "icon" => "icon-dashboard"
    "url" => "http://localhost/backend/backend"
    "permissions" => array:1 [▼
      0 => "backend.access_dashboard"
    ]
    "order" => 1
  ]
]
```

The "permissions" are way different. Is this maybe a problem?

**Comment by alekseybobkov** [comment]
@ametad, please make sure that you're running the latest build of October. There was an issue #30, which is already fixed, where URLs were applied to permissions.

**Comment by ametad** [comment]
Thank you for pointing that out. Once updated correctly the problem is gone! Permissions and the showing/hiding of menu's works correctly.
