### ISSUE TITLE
get data from outside alive possible?

### ISSUE THREAD

**Issue by dbYoung** [rainlab/builder-plugin#52]
I'm going to use javascript library to show data on front-end page.

and I want to get data from outside(google speadsheets or other services API).

inerval timing and cycic get & stored data from outside source...

**Comment by alekseybobkov** [comment]
I think it's a wrong place to ask this question. Builder's purpose is creating plugins and back-end user interfaces. What you are looking for is the front-end functionality. Please see the [theming documentation](http://octobercms.com/docs/cms/themes).
