### ISSUE TITLE
[Feature Request] Manage model relations

### ISSUE THREAD

**Issue by robinbonnes** [rainlab/builder-plugin#53]
Hello,

Could it be possible to manage the relations (hasOne/hasMany/belongsTo/BelongsToMany) per model, so then we can use the relation option in a model list column.

Would be great!

- Robin

**Comment by alekseybobkov** [comment]
Duplicate: #21 

Managing relations would require editing the model class file (PHP). By design Builder doesn't edit PHP files. Please see the plugin documentation and explanations in #21.
