### ISSUE TITLE
Missing 'html' type in model lists

### ISSUE THREAD

**Issue by robinbonnes** [rainlab/builder-plugin#54]
When I want to show the richeditor content in a list column it shows the raw html when the text type is selected.

This can be avoided by making a 'html' option, which renders the html content in the list column.

**Comment by alekseybobkov** [comment]
Displaying non-sanitized content from the database is not safe and can introduce security vulnerabilities. Please use the [partial](http://octobercms.com/docs/backend/lists#column-partial) column type instead.
