### ISSUE TITLE
Menu item settings modal not displaying

### ISSUE THREAD

**Issue by oadslug** [rainlab/builder-plugin#6]
When attempting to add a new menu item from 'Backend Menu', clicking on the newly created menu item does not display the menu settings modal window. The screen dims slightly but no settings window. 

October Build 314; Builder v1.0.1; Mac Safari Version 9.0 (10601.1.56.2)

**Comment by daftspunk** [comment]
Please confirm what browser and October build you are using.

**Comment by oadslug** [comment]
October Build 314; Builder v1.0.1; Mac Safari Version 9.0 (10601.1.56.2)

**Comment by daftspunk** [comment]
Please update to Build 316 and ensure the browser cache is cleared (or refresh the page 2-3 times). Then try again.

**Comment by oadslug** [comment]
That worked. Thank you!
