### ISSUE TITLE
Already created tables not visible

### ISSUE THREAD

**Issue by maesklaas** [rainlab/builder-plugin#61]
Hello

I am new to OctoberCMS. I created a new plugin added migrations and added those in versions.yaml. After that i did a refresh, tables were created perfectly but on the backend in builder the tables are not showing. How can i make them show?

Thanks

**Comment by alekseybobkov** [comment]
Builder looks for tables with names prefixed with the author and plugin namespaces. For example if your plugin was maesklaas.library, the expected prefix would be maesklaas_library_. Please make sure that you have correct table prefixes.
