### ISSUE TITLE
Failed to save image information

### ISSUE THREAD

**Issue by dev-lav** [rainlab/builder-plugin#65]
I have tried to upload image using file upload field, upload file to server is success but failed to save image information (file name) to database. thank's

**Comment by alekseybobkov** [comment]
It might be not related to the Builder plugin. Did you create a relation in your model class? Please see Builder's documentation (http://octobercms.com/plugin/rainlab-builder) and October documentation (http://octobercms.com/docs/database/attachments#file-attachments) for details.

**Comment by dev-lav** [comment]
Thank's for reply,
I have added this in my model class :
public $attachOne = [
        'photo' => ['System\Models\File']
    ];

My table structure :
$table->engine = 'InnoDB';
$table->increments('id')->unsigned();
$table->string('name', 50);
$table->text('photo')->nullable();

**Comment by dahLucky** [comment]
The relation for files are stored in the system_files table, therefore you do not need an extra column. This might cause your troubles. I would recommend you to use the official forum: [https://octobercms.com/forum]. I am sure we can solve your issue there. 

Suggesting to close this issue.

**Comment by warkarth** [comment]
hello, I have a problem with the same file upload field, already add attachOne in my model class, the error is: "copy (); filename can not be empty" and once I select my image is displayed.
anyone has a solution ?, I think it is server problem, already check the file upload capability in php.ini
I do not know what else can be.
Thank you for your help

**Comment by warkarth** [comment]
how can i display an image stored in my db, with the recordlist component?

**Comment by alekseybobkov** [comment]
Are you referring to the back-end list behavior (http://octobercms.com/docs/backend/lists#column-partial)? There is a way to render a partial (HTML file) in a list column. Inside the partial you can access the model and all its relations. Example:

```
<?php
    if ($image = $record->hero_image()->first())
        $thumb = $image->getThumb(48, null, 'landscape');
    else
        $thumb = 'http://placehold.it/48x48';
?>

<div style="padding: 5px">
    <img src="<?= $thumb ?>" alt="<?= $record->title ?>" />
</div>
```

**Comment by warkarth** [comment]
![img](https://cloud.githubusercontent.com/assets/6380641/14624092/03e30a2a-059d-11e6-95b0-22e4ff23676a.png)
@alekseybobkov I don´t know, what I want is to attach my picture, I keep in the base with a ImageUploader, when I access my attribute image through attribute (record, img) returns a JSON or associative arrays with path field, which is i want to access in order to show my image
