### ISSUE TITLE
Something wrong with permissions 

### ISSUE THREAD

**Issue by boowee** [rainlab/builder-plugin#67]
I made all actions in builder plugin.

Created permission.
When I add permission for backend menu item, this item not displayed for backend user (not super user) which has this permission. Including for main menu & side menu.
core build 316
builder 1.0.8

**Comment by Alexandre-Gadiou** [comment]
I have the same issue. There is a hack to bypass plugin.yaml data. You can override public function registerNavigation() in plugin.php

`public function registerNavigation()
//    {
//        return [
//            'calendar' => [
//                'label' => 'algad.bootstrap::lang.menu.calendar',
//                'url' => Backend::url('algad/bootstrap/events'),
//                'icon' => 'icon-calendar',
//                'permissions' => ['algad.bootstrap.manage_events'],
//                'sideMenu' => [
//                    'events' => [
//                        'label' => 'algad.bootstrap::lang.menu.events',
//                        'url' => Backend::url('algad/bootstrap/events'),
//                        'icon' => 'icon-tag',
//                    ]
//                ]
//            ]
//        ];
//    }`

**Comment by alekseybobkov** [comment]
Please see this issue #51. Make sure that you use the latest build of October.

**Comment by Alexandre-Gadiou** [comment]
hi you were right aleksey, I was not up to date.
Now everything works

thank you

Alex
