### ISSUE TITLE
Bug: ApplicationException Datetime Error

### ISSUE THREAD

**Issue by lionax** [rainlab/builder-plugin#68]
Following Situation:

Table with a "date" column of type datetime.

Model with
- fields.yaml: "date picker" in datetime mode referencing date column in table.
- columns.yaml: column of type datetime referencing date column in table

One entry created in the backend with the date picker.

Verified, that an entry is generated in the table and that the column is of type datetime.

When attempting to visit the backend list view again, after inserting the first entry, I receive an ApplicationException.

Here is the stack trace
[Exception.pdf](https://github.com/rainlab/builder-plugin/files/186792/Exception.pdf)

**Comment by alekseybobkov** [comment]
Sometimes you need to edit models manually. Builder doesn't (and won't) edit PHP files - it's one of its design concepts. In your case you need to add the field to the $dates property of the model, as the exception suggests.
