### ISSUE TITLE
[Feature Request] Extend another Plugin

### ISSUE THREAD

**Issue by lionax** [rainlab/builder-plugin#69]
It would be very nice, if I simply could create a Plugin and extend an existing one.

Example:

I want to extend the User Plugin with my own fields, functions etc. Like in the Video on Vimeo [Extending the User Plugin](https://vimeo.com/108040919) there are two ways of doing this. Both would be nice if they were included in the builder.

If I'm wrong, please correct me :)

**Comment by alekseybobkov** [comment]
This is out of scope of the Builder. Builder is a tool for bootstrapping/scaffolding new plugins. It intentionally has some limitations, such as PHP code generating. One reason why such features are not going to be implemented is that we develop a CMS platform. Builder is a helper tool, we can't devote resources to turn it into an advanced development environment.
