### ISSUE TITLE
Unknown database type enum requested

### ISSUE THREAD

**Issue by boowee** [rainlab/builder-plugin#7]
It happens when I'm trying to save new table.

"Unknown database type enum requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it." on line 423 of vendor\doctrine\dbal\lib\Doctrine\DBAL\Platforms\AbstractPlatform.php

Windows 7,10
PHP 5.6
MySQL 5.6

**Comment by alekseybobkov** [comment]
The enum column type is not currently supported and cannot be managed with the Builder UI. But we improved the error handling and now it triggers the error only when you try to open a table which contains enum columns.

**Comment by boowee** [comment]
Awesome. Now I can save table.

**Comment by dmeijboom** [comment]
@alekseybobkov Would je be willing to accept a pull-request which adds support for enum? And if so are there things I need to know before implementing this?

**Comment by LukeTowers** [comment]
@dmeijboom it'd have to be implemented in Doctrine

**Comment by dmeijboom** [comment]
@LukeTowers It seems like they do have some sort of 'workaround' for enums though: https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/cookbook/mysql-enums.html . Is there any way we could implement this or is this simply not possible due to poor enum support by Doctrine?

**Comment by LukeTowers** [comment]
@dmeijboom you're welcome to give it a try and submit a PR for review
