### ISSUE TITLE
Autofill columns.yaml using model definitions

### ISSUE THREAD

**Issue by dudheit** [rainlab/builder-plugin#73]
After defining all fields in the database section it is necessary to list the fields again in the models section when defining the columns.yaml. I know that there is auto completion but I think it would be helpful if there was a possibility to insert all the field names defined in the database with one click to the columns.yaml. That would avoid typing all the field names again (or typing one letter and autocomplete them one after the other).

**Comment by alekseybobkov** [comment]
This feature is now supported. 

![screen shot 2017-01-25 at 8 17 02 pm](https://cloud.githubusercontent.com/assets/481606/22319842/4c5e7a38-e33b-11e6-8df4-4b00915c98a4.png)
