### ISSUE TITLE
Can't save fields.yaml using builder if there's a repeater in a tab

### ISSUE THREAD

**Issue by arikw** [rainlab/builder-plugin#74]
Add a repeater in a tab and try to save.
An error message will pop with: "Lists in control list containers should have names, and the name should be equal for all lists in a container."

**Comment by canthis** [comment]
I can confirm this. Getting exactly the same exception.

**Comment by intositeme** [comment]
Getting this issue as well

**Comment by gavinworks** [comment]
+1

**Comment by quackpack** [comment]
Same here

**Comment by lackneets** [comment]
+1

**Comment by Roywcm** [comment]
+1

**Comment by gerbertsantos** [comment]
+1

**Comment by reg2005** [comment]
+1

**Comment by nerijunior** [comment]
+1

**Comment by Asinox** [comment]
+1
