### ISSUE TITLE
Not Records when Soft Deleting is present in the model

### ISSUE THREAD

**Issue by Asinox** [rainlab/builder-plugin#75]
Maybe this is just a thing that i'm missing somewhere, but i was having "not records" in listing view (backend) when the "Soft Deleting"is present in the model like this:

`use \October\Rain\Database\Traits\SoftDeleting;`
    `protected $dates = ['deleted_at'];`

Any idea?, i don't know if this is a bug of what..

Thank you

BTW: i love this plugin guys!!

**Comment by alekseybobkov** [comment]
This issue is not relevant to the Builder plugin. Please move it to the October repository: https://github.com/octobercms/october/issues. Thanks.
