### ISSUE TITLE
Can´t upload a image with file upload field "copy (); filename can not be empty"

### ISSUE THREAD

**Issue by warkarth** [rainlab/builder-plugin#77]
hello, I have a problem with the file upload field, already add 
public $attachMany = [
    'image' => 'System\Models\File'
];
 in my model class, the error is: "copy (); filename can not be empty" and once I select my image is displayed.
anyone has a solution ?, I think it is server problem, already check the file upload capability in php.ini ,and also check my folder permissions "storage/app"
I do not know what else can be.
Thank you for your help

**Comment by alekseybobkov** [comment]
This issue is not relevant to the Builder plugin. Please move it to the October repository: https://github.com/octobercms/october/issues. Thanks.
