### ISSUE TITLE
Create new string feature lacks editing

### ISSUE THREAD

**Issue by trsh** [rainlab/builder-plugin#79]
1) Got to some columns.yaml editor in builder.
2) Press + in "Labels" create a new String.
3) Input data, press OK, and Save.
4) Click again on "Label", there is "+" again-, ideally should be some edit icon.
5) When pressing on +, empty String creation from appears, ideally should be with already set data, not rewriting all.

**Comment by alekseybobkov** [comment]
You can edit existing strings from the Localization tab. See the Managing Localization section in the plugin documentation (http://octobercms.com/plugin/rainlab-builder). When you save a localization file it automatically updates all strings in the user interface.

**Comment by trsh** [comment]
I know, but that was not the point.
