### ISSUE TITLE
Backend submenus not displaying

### ISSUE THREAD

**Issue by oadslug** [rainlab/builder-plugin#8]
I have defined a backend menu with 3 submenus for a plugin, carefully following the 'Say hello to Builder' video tutorial. However, when selecting the plugin menu (top menu bar), no submenus are displayed (left menu bar is not displayed at all). In addition the plugin menu item (top menu bar) does not highlight as selected.

**Comment by alekseybobkov** [comment]
Did you select the menu item in the Create Controller form?

![select-menu-item](https://cloud.githubusercontent.com/assets/481606/12967312/7b9da9ac-d01a-11e5-8071-2ae8a1cf3cf0.png)

If you didn't select it in the form, you can update the controller class code manually:

    public function __construct()
    {
        parent::__construct();
        BackendMenu::setContext('RainTest.MyLibraryPlugin', 'main-menu-item', 'side-menu-item');
    }

Please see the documentation for details: http://octobercms.com/docs/backend/controllers-ajax#navigation-context

**Comment by oadslug** [comment]
For some reason the product class name was incorrect in the BackendMenu as you suspected. Thank you!
