### ISSUE TITLE
Can not create new String for Label in from editor

### ISSUE THREAD

**Issue by trsh** [rainlab/builder-plugin#80]
1) Open Form editor in builder
2) Press + on Label
3) Input and save
4) Page hangs

**Comment by trsh** [comment]
This is with popup, stacked works ok. I think the bug is because to modals.

**Comment by lionax** [comment]
I can confirm this Bug. It happens every time I use the + symbol when there is content already in the label field. Without content in the label field it works like a charm.

**Comment by alekseybobkov** [comment]
I believe it's the same issue as #41. There is a temporary solution see https://github.com/rainlab/builder-plugin/issues/41#issuecomment-217600900
