### ISSUE TITLE
Primary key creation from two DB fields fails

### ISSUE THREAD

**Issue by trsh** [rainlab/builder-plugin#81]
manage_photoalbum_albums_albumtypes_album_id_albumtype_id_primary' is too long

Some overkill on concating a unique index name here. Migration/update file was not created. Table was.

**Comment by alekseybobkov** [comment]
I don't think compound primary keys will be ever supported in the Builder. But we will update the code to prevent possible errors.

**Comment by trsh** [comment]
But it part of the thing right now. Just click PK on two fields. 

_"I don't think compound primary keys will be ever supported in the Builder"_

What the point than of migration, if part is done automatically and other you must do by hand (indexes etc). It than just creates more haox. Must thrive for the full package :)

**Comment by chrisvidal** [comment]
facing the same issue with 2 fields being a primary key.
The use case is quite common I think.
the identifier name is limited to 64 characters by mysql and it is quickly reached with a double primary key 'author_plugin_tablename_field1_id_field2_id_primary'

**Comment by trsh** [comment]
@chrisvidal sadly mindset of authors is some-have limited. They just say this and that can't be done, and goodbye. In the same time frameworks like Yii and Django have almost perfect migration tools, that have all of these problems covered.  :/
