### ISSUE TITLE
Models :: Create new string (localization) : this.options is null

### ISSUE THREAD

**Issue by dotMastaz** [rainlab/builder-plugin#84]
Hello,

When i create a new string for localization and after i complete 'String key' field and 'String value',
i have a 'this.options is null' ??

Thank you for your help !!
![2016-05-06_10-52-17](https://cloud.githubusercontent.com/assets/1413375/15068704/7a20929a-1379-11e6-82f1-56d2c3b40a38.jpg)

**Comment by alekseybobkov** [comment]
Duplicate: #41
