### ISSUE TITLE
Builder forces migration version spam

### ISSUE THREAD

**Issue by trsh** [rainlab/builder-plugin#85]
Every time I do some small changes to tables with builder (especially often in project initial phase), I'm forced to have a new version. 

> 1.0.2:
    - 'Updated table manage_photoalbum_orders'
    - builder_table_update_manage_photoalbum_orders.php
1.0.3:
    - 'Created table manage_photoalbum_albums'
    - builder_table_create_manage_photoalbum_albums.php
1.0.4:
    - 'Updated table manage_photoalbum_albums'
    - builder_table_update_manage_photoalbum_albums.php

Ideally would be to find a way to accumulate multiple changes in one version 

> 1.0.2:
    - 'Updated table manage_photoalbum_orders_01939012903290'
    - builder_table_update_manage_photoalbum_orders.php
    - 'Created table manage_photoalbum_albums_01939012903291'
    - builder_table_create_manage_photoalbum_albums.php
    - 'Updated table manage_photoalbum_albums_01939012903293'
    - builder_table_update_manage_photoalbum_albums.php

and then apply in one run in respecting order.
I know I can do this manually, but we are talking about Builder here.

**Comment by alekseybobkov** [comment]
Duplicate, please see #63

**Comment by trsh** [comment]
Ou, sorry
