### ISSUE TITLE
Can't use underscore on model form configuration file name

### ISSUE THREAD

**Issue by jfoliveira** [rainlab/builder-plugin#87]
Reproducing steps:
`Builder->Select Plugin->Models->Select Model->Forms->Plus Button to add new file`

Name the file `my_fields.yaml` and hit the `Save` button.

Error message:

> The file name can contain only Latin letters, digits, **underscores**, dots and hashes.

**Comment by alekseybobkov** [comment]
Fixed in 81bd6f31989be5f4b8a559ae9f8a59e0ab6e17ed
