### ISSUE TITLE
Database Table Relations and Contraints

### ISSUE THREAD

**Issue by lionax** [rainlab/builder-plugin#88]
As in #63 Indices and Foreign Keys are planned.

The Question: Will there be support for Unique-Constraints between selected columns, Composit-Primary keys, Column with Increment but without Primary (tricky with lavarel)?

These are special cases or advanced needs but typical for complex systems. It would be nice if they could be prototyped in the Builder plugin.

I implemented a database schema containing all the above concepts. If there are any questions I'm willing to help out ;)

**Comment by alekseybobkov** [comment]
This won't be implemented in Builder and should be managed with manual migrations. The database management is a very broad topic and tools that implement it are complicated. It's relatively easy to implement some features for a single chosen database engine, but it gets tricky when dealing with multiple database systems, even with excellent abstraction layer provided by Eloquent. Even mapping timestamps to native database column types was tricky and we had to hard code typical timestamp column names in Builder to simplify the task. This is not a task we want to spend time in the CMS project. But Builder is open source and your input is always appreciated - please feel free to implement missing features and submit them as a pull request.
