### ISSUE TITLE
Builder fails to load models when using ::class notation

### ISSUE THREAD

**Issue by tobias-kuendig** [rainlab/builder-plugin#90]
When using the `::class` notation inside a model, Builder doesn't display it in the backend anymore.

Model is listed under `Builder -> Models`: 

``` php
class Product extends Model
{
    public $hasMany = [
        'attributes' => 'Namespace\Of\Models\Attribute'
    ];
}
```

Model is **not** listed under `Builder -> Models` anymore: 

``` php
use Namespace\Of\Models\Attribute;

class Product extends Model
{
    public $hasMany = [
        'attributes' => Attribute::class
    ];
}
```

**Comment by alekseybobkov** [comment]
@tobias-kuendig, thanks for the report. We will take a look into it. Builder doesn't execute plugins' PHP files and can only rely on parsing. Resolving class names could be a challenging task.
