### ISSUE TITLE
Cannot setup Reorder Controller

### ISSUE THREAD

**Issue by c-andrews** [rainlab/builder-plugin#91]
Hi, I am trying to setup the reorder controller so that i can order how "Projects" are displayed in on the front end but I cannot seem to get it working.

I've tried to follow the documentation but it doesn't seem to be working.

In my Project Model I have replaced:
**use \October\Rain\Database\Traits\Validation;**
with 
**use \October\Rain\Database\Traits\Sortable;**

Then in my Projects Controller I have added **'Backend\Behaviors\ReorderController'** to the **$implement** and also created the **$reorderConfig**.

Then in my Projects Controller subfolder I have created the **config_reorder.yaml** and the **reorder.htm**.

Can someone tell me what i'm missing?

Thanks in advance
Chris

**Comment by alekseybobkov** [comment]
Hi Chris. This repository should only be used for questions related to the Builder plugin. Try the Forum (http://octobercms.com/forum) or Slack (https://octobercms.slack.com/) to get technical support for general October questions.
