### ISSUE TITLE
Cannot Determine the Currently Active Plugin

### ISSUE THREAD

**Issue by coycash** [rainlab/builder-plugin#92]
90% of the time I get this error while trying to do anything with builder.  Yes I select the plugin first. And the database tab will show already created tables, but when trying to Add+ another I get the error.

**Comment by alekseybobkov** [comment]
What browser and OS you use?

**Comment by coycash** [comment]
Chrome on Windows 10.  I'm trying Firefox now and it seems to be working.

**Comment by alekseybobkov** [comment]
Currently I don't have access to Chrome on Windows 10.  We would greatly appreciate it if you help us to debug the problem.

**Comment by coycash** [comment]
![capture](https://cloud.githubusercontent.com/assets/4764882/15586442/eed13b3c-2349-11e6-830b-efc639ef0939.JPG)

Not sure what to look for, here is my console.  I don't see anything in system.log.

**Comment by alekseybobkov** [comment]
@coycash - there's another relevant issue #128. Could you check if your session lifetime is not zero?

**Comment by alekseybobkov** [comment]
Please reopen this issue if needed.

**Comment by vmee** [comment]
it is same issues;

`storage/framework/sessions`
Directory not writable

use
`chmod -R 777  storage/`
fix it!
