### ISSUE TITLE
Unhandled Error when creating localization sub-keys on existing key

### ISSUE THREAD

**Issue by lionax** [rainlab/builder-plugin#93]
When defining a Localization key `plugin::lang.someKey: value` and then defining more keys with this key as their base: `plugin::lang.someKey.one: value`; `plugin::lang.someKey.two: value` the value of someKey in the localization yaml get's replaced with an array of the new key:value pairs. The Problem is that the old language key is still used in the models yamls and thus an exception is thrown and affected yamls can't be changed anymore.

An error handling would be nice like when I try to define an already existing key.

The Stack-Trace.
[Exception.pdf](https://github.com/rainlab/builder-plugin/files/288502/Exception.pdf)

**Comment by alekseybobkov** [comment]
This is fixed in d57ec1ee1b16e0b41af9269e6cd86b42ed4dfb73.
