### ISSUE TITLE
Create / Update / Preview pages are not automatically created for manually built plugins

### ISSUE THREAD

**Issue by meysammahfouzi** [rainlab/builder-plugin#95]
If I manually develop a plugin, and e.g. create only the "create" page for a controller which has implemented the form and list behaviors, and then open the plugin in the builder, the builder wont recognize that the "update" and "preview" pages are missing and therefore wont create them automatically. It seems that the builder plugin creates "create", "update" and "preview" pages only for the plugins created with it.

**Comment by alekseybobkov** [comment]
That's correct - Builder creates behaviour view files only when the behaviour is created by Builder. That's one of the limitations that allow us to keep Builder simple and maintainable within a CMS project.
